### ISSUE TITLE
 leaf overlapping and occlusion 

### ISSUE THREAD

**Issue by SadafSafder23** [danforthcenter/plantcv#1000]
Hello, I am Sadaf. I am working on identify the counting of leaves, shapes and angles of the leaf on the plant. I am facing leaf overlapping and occlusion problem during the detection and counting of leaf. I am showing the image below.
![Capture](https://user-images.githubusercontent.com/127180363/223338740-12f849e3-bfc2-4c3a-9943-da4c3e3025c1.PNG)
in the image, its wrongly identify the 'ID 2 and ID 3', actually it's one leaf which it consider 2, means while if two leaves are overlapping show in the below image,
![image](https://user-images.githubusercontent.com/127180363/223341056-a5ff944f-3e1e-4fa6-bf87-2269912d3037.png)
 what is the possible function to identify it.

**Comment by HaleySchuhl** [comment]
Hi @SadafSafder23 thanks for opening this issue. 

It's true that overlapping/occlusion has detrimental and often "fatal" effects on the algorithms inside the morphology sub-package. We do have the `pcv.morphology.check_cycles` which can be used to detect complexity which will break the various analysis functions. 

As far as recovering leaf replicated in images where overlapping is a problem, I usually would try to look upstream at the segmentation. Sometimes doing a `pcv.dilate` step can help round sharp features that produce false branch points. Using `pcv.fill_holes` can eliminate any gaps in your plant mask but might have undesirable results still depending on plant complexity. 

Lastly, I might try to increase the size parameter in the `pcv.morphology.prune` step to remove those smaller leaves which are breaking the branching structure logic and instead hopefully get accurate IDs and observations for the more mature leaves.

**Comment by SadafSafder23** [comment]
Thank you for your response @HaleySchuhl.

I am using the _pcv.fill_holes_ and `pcv.dilate` to eliminates the gaps in the plant but result are not accurate, the below image show more branch points during using the pcv.dilate.

![image](https://user-images.githubusercontent.com/127180363/223663995-3d22be93-f649-4aea-a464-3b9c7163fec0.png)
after using "pcv.fill_holes " with three channels `"bsa" `the branch point somewhat better than before. 

![image](https://user-images.githubusercontent.com/127180363/223665343-77794295-7d96-496b-8734-37bfb23315a4.png).
i am also trying to understand the _`pcv.morphology.check_cycles`_ which can be used to detect complexity which will break the various analysis functions.

Thank you 
Sadaf

**Comment by HaleySchuhl** [comment]
Regarding the `check_cycles` function, this is how I have used it to skip complex replicates. 

```
cycle_img = pcv.morphology.check_cycles(skel_img=skeleton, label="default")

# Access data stored out from check_cycles
num_cycles = pcv.outputs.observations['default']['num_cycles']['value']
if num_cycles == 0:
    # Do morphological analysis 
else:
    # Just do pcv.analyze_object, color analysis, or skip
```

**Comment by SadafSafder23** [comment]
ok, thank you @HaleySchuhl

**Comment by SadafSafder23** [comment]
@HaleySchuhl could you add me in slack, it would be helpful for me.
