### ISSUE TITLE
Installation instructions dead link

### ISSUE THREAD

**Issue by tyrwh** [danforthcenter/plantcv#107]
The installation link in the readme is [http://plantcv.danforthcenter.org/pages/documentation/function_docs/installation.html](http://plantcv.danforthcenter.org/pages/documentation/function_docs/installation.html), which gives a 404. It looks like it should be updated to [http://plantcv.readthedocs.io/en/latest/installation/](http://plantcv.readthedocs.io/en/latest/installation/)

**Comment by nfahlgren** [comment]
Thanks @tyrwh. We had updated the link in the README in our dev branch, which will be merged into the master branch in the near future when we release v2.0. In the meantime, I updated the README in the master branch to fix the link as you suggested. If you are interested in installing PlantCV, I recommend using the dev branch version at this point, we are just about done polishing it up for release.
