### ISSUE TITLE
Remove MatPlotLib Plotting

### ISSUE THREAD

**Issue by maliagehan** [danforthcenter/plantcv#11]
We think matplotlib plotting functions are limiting our ability to run PlantCV over 14 cpu. To overcome this we are trying to remove matplotlib functions (or make output optional) wherever possible.

**Comment by maliagehan** [comment]
MG has made pseducoloring of nir and vis images without matplotlib functions. Histogram plotting of signal is now optional.

**Comment by nfahlgren** [comment]
MG made all the matplotlib parts optional and testing with > 12 CPUs now works.
