### ISSUE TITLE
Cuda/GPU support?

### ISSUE THREAD

**Issue by pawelzebrowski** [danforthcenter/plantcv#1100]
I'm trying to make use of GPUs to accelerate my PlantCV processing pipeline (find_objects, object_composition, analyze_object, etc) but can't find any definitive information on Cuda support.

I've compiled (and tested) OpenCV with Cuda support but can't get PlantCV to take advantage of that support.  Does PlantCV support OpenCV + Cuda?

Any hints or ideas appreciated

**Comment by nfahlgren** [comment]
Hi @pawelzebrowski, this is not something we have tried, but it would be interesting to develop a protocol for it.

I assume you are installing PlantCV from source? If so, before installing the package I would edit the `requirements.txt` file to remove `opencv-python`. Just thinking that when PlantCV installs pip could be duplicating OpenCV with the package from PyPI. Or alternatively double check this is not the case by confirming the following is pointing to your compiled version of OpenCV:

```python
import cv2
cv2.__file__
```

**Comment by pawelzebrowski** [comment]
Thanks @nfahlgren, that's exactly what i'm doing - and yes, I had to remove opencv-python and numpy from requirements.txt and install from source.

After a little digging, I think PlantCV would have to explicitly make use of Cuda for numpy operations, maybe with the help of something like CuPy or Numba, otherwise it's all done on CPU as always.

Either way, it sounds like i'm in uncharted waters!

**Comment by Hemilibeatriz** [comment]
Any news about this topic? If anyone wants to join me in applying the necessary changes, contact me!
