### ISSUE TITLE
Make sure all dependencies are listed in package requirements

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#114]
All dependencies should be listed in `setup.py` as `install_requires=['matplotlib', 'numpy']`

**Comment by jshoyer** [comment]
Watch out for watershed.py -- something about one or more SciPy dependencies prevents me from correctly using plantcv after install, though `setup.py` did not complain, if I recall correctly.

Unrelated: I have various typo fixes in dev branch of my fork. I've mixed in some notes on variables that I think are no longer used, but I could separate those out if that would be useful.

**Comment by nfahlgren** [comment]
@jshoyer scipy is one of the dependencies we don't list that should be. I should make a list here that I can (I think) update later:

- [ ] scipy
- [ ] cv2

**Comment by nfahlgren** [comment]
@jshoyer I think it will be okay if those changes are together, or at least not worth the pain of pulling them apart :)

**Comment by jshoyer** [comment]
I think this work would benefit from further documentation, like a sentence or two in the 'Contributing' guide about how and when to add new dependencies.

What are the most important dependencies in order? Why raise an ImportError for cv2 but not numpy etc.?

My least favorite aspect of using python is that I often fall into dependency hell.

**Comment by nfahlgren** [comment]
@jshoyer that's a good idea. For your curiosity, I raised an ImportError for cv2 because it was the only easy way I could deal with it since it's not a PyPi package. If you include it in the install_requires list then setuptools tries to install it. I know it's possible to compile external libraries with setuptools, but it looked pretty complicated and I'm not sure it's worth trying to build OpenCV for people automatically.
