### ISSUE TITLE
Mask saturated pixels

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#119]
Saturated pixels (overexposed) can be a problem because they potentially underestimate the true pixel intensity. This can be a problem later when analyzing color data. Proposed solution:

Create a new function that detects saturated pixels (could be defined as all R = B = G = 255, or alternatively R = 255 OR B = 255 OR G = 255, etc.) and outputs a binary mask indicating which pixels are saturated or not. The saturated mask would be combined with the plant contour mask to remove the saturated pixels. The combined mask would be the mask input to `pcv.analyze_color` so that the output histograms would exclude saturated pixels.

**Comment by bganglia** [comment]
@nfahlgren I can work on this

**Comment by nfahlgren** [comment]
Awesome, thanks @bganglia!

**Comment by nfahlgren** [comment]
Hi @bganglia, I added you as a team member to the GitHub repository. If you would like it will let you directly create branches on this repository so you would not need to maintain a fork. Makes things a bit easier for you but either way is great.

**Comment by bganglia** [comment]
@nfahlgren Thanks! I am adding a note to the contribution guide and will use that to test pushing branches to this repository.

**Comment by bganglia** [comment]
@nfahlgren I am having some trouble getting it to work, but that is OK :) I am used to working on a fork anyway.

My steps:
```
(plantcv) username@pcname:~/plantcv/plantcv$ git remote add upstream https://github.com/danforthcenter/plantcv.git
(plantcv) username@pcname:~/plantcv/plantcv$ git push upstream add-disabling-debug-to-contribution-guide 
Username for 'https://github.com': bganglia
Password for 'https://bganglia@github.com': 
remote: Permission to danforthcenter/plantcv.git denied to bganglia.
fatal: unable to access 'https://github.com/danforthcenter/plantcv.git/': The requested URL returned error: 403
```
I can't create branches on the Github UI either, but again, that is OK; it will not prevent me from contributing or anything.

**Comment by nfahlgren** [comment]
Hi @bganglia, on my end it says you have not accepted the invite yet, I think you have to before the above will work. It might be in your GitHub notifications or an email. If it didn't show up maybe shoot me an email and I can send you the link directly. Thanks!

**Comment by bganglia** [comment]
@nfahlgren Thanks. Accepted now
