### ISSUE TITLE
find_branch_pts.py and find_tips.py save coords so that it creates misaligned columns in multi-value-traits.csv

### ISSUE THREAD

**Issue by bripar** [danforthcenter/plantcv#1191]
When find_branch_pts.py and find_tips.py in the morphology functions add a coordinate to branch_list as (int(x), int(y)) it appears to cause the value column in the multi-value-traits results CSV file to be misaligned as the x and y coordinates end up in different columns which pushes the values over (as shown in attached image). This has caused an issue when I try to open such files in R as it does not like the blank column header. I have got around the issue for a while by changing find_branch_pts and find_tips in my plantcv installation so that the coords values are added as a single string and not a list with a ",". 

Please let me know if this is a genuine error or if I am missing something!
Thank you!

**Local environment (please complete the following information):**
 - OS: Windows
 - PlantCV Version 3.12

![coords error example](https://github.com/danforthcenter/plantcv/assets/136628843/b935ca10-72f8-4530-8070-28737b1251d9)

**Comment by HaleySchuhl** [comment]
Thanks for bringing this to our attention, @bripar ! Are you willing to share your data.json file so I can attempt to replicate this locally? 

Your plantcv version is slightly outdated, but I do not believe those specific functions have been changed in the last year... so it's good to know this bug exists and probably has gone undetected for a long while.

**Comment by bripar** [comment]
Hi @HaleySchuhl,

It appears as though I cannot upload a json file here, is there another way to do it or can I email it to you? 

Thank you!

**Comment by HaleySchuhl** [comment]
@bripar can you try to zip the file and then upload here? Email would also work if not.

**Comment by bripar** [comment]
[Cam2_MAGICFOUNDERS.zip](https://github.com/danforthcenter/plantcv/files/11758530/Cam2_MAGICFOUNDERS.zip)
 does that work?

**Comment by HaleySchuhl** [comment]
Yes I got it! We can replicate this issue with Windows even though there is nothing wrong with your data extraction or the .json file. If you make sure your unicode is being interpreted properly, I think you should be able to resolve this.

**Comment by bripar** [comment]
I do not care about the coordinates, I just needed them to not misalign the columns. For now, for my own use I have 'fixed' the issue by editing find_tips.py and find_branch_pts.py but I am in the process of preparing to hand over my work to someone else and didn't want them to encounter the same problem.

**Comment by nfahlgren** [comment]
We implemented a bugfix in PR #1198. Once we merge it we can release a package for PlantCV v3.15
