### ISSUE TITLE
More flexible image output, especially from 'analyze_object' or related functions

### ISSUE THREAD

**Issue by jshoyer** [danforthcenter/plantcv#121]
This is a general feature request that should not require much coding
I have already tested some possibilities that work well enough for my purposes, but I'd like feedback before adding too many new arguments to the analyze_object function.

Examples of altered output I have been using:
  - I just write just the 'shapes' images to disk, not the 'mask' images. Using two arguments (instead of the current 'filename' argument) would make it easy to do the opposite as well.
  - I avoid the color red for 'shapes' lines, because it becomes color-blind-unfriendly with images that have a dark background (i.e top-down views of plants in soil). I have been using magenta, but the color could be specified as an argument.
  - I skip drawing the (blue) contour/object boundaries, because those lines get in the way when I browse my (relatively small, cropped) images.
  - I have been using thinner lines for the same reason---line thickness could be an additional optional argument. (I care less about this one.)

A somewhat related idea I have mentioned is providing options for image output that uses semitransparent background (using `cv2.addWeighted`) instead of straight-up white-masked background, but I should probably file a separate issue for that one before discussing it further.

**Comment by nfahlgren** [comment]
@jshoyer a few comments:

> I just write just the 'shapes' images to disk, not the 'mask' images. Using two arguments (instead of the current 'filename' argument) would make it easy to do the opposite as well.

Makes sense to me that you would be able to select what kind of output images you want, as opposed to our all-or-none method now. For the next release I wouldn't want to introduce any breaking changes to the API though...

> I avoid the color red for 'shapes' lines, because it becomes color-blind-unfriendly with images that have a dark background (i.e top-down views of plants in soil). I have been using magenta, but the color could be specified as an argument.

I agree, red and green should be avoided. I suggest changing the hard-coded color for now and doing something more comprehensive later (see below).

> I have been using thinner lines for the same reason---line thickness could be an additional optional argument. (I care less about this one.)

We made the lines thicker recently because of Jupyter Notebook integration. When we use Matplotlib to plot images in Jupyter it makes smaller, downsampled images (by default), and it tends to make the lines disappear if they are too thin.

All of the styles like line thickness, color, etc. are hard coded and embedded throughout the code right now. I think rather than adding more inputs to each function to control style parameters we could rework debug to be more comprehensive. We could make debug a class that can contain methods for debug itself (print, plot, all, none, etc.), line thickness, line color, fill color, etc, etc. This would let you initialize the debug class in your script once (or more if you want) and pass the drawing parameters to all functions without any additional inputs.

**Comment by jshoyer** [comment]
Thanks---all that makes sense. I'm agree that this does not fit in version 2.0
I do not really use Jupyter, so I had not thought about down-sampling.
I noticed that Max has also [adapted analyze_image](https://github.com/maxjfeldman/Feldman_Setaria_Height_2016/blob/master/image_analysis/analyze_object_MF.py) for his purposes, so he may have thoughts about splitting the function.

Making debug output more flexible in general sounds great. I have thought about it for a while, but I am not sure what python data structures would work best. Seems related to the idea (#13) of making it easy to selectively (re)generate image output.

**Comment by jshoyer** [comment]
I have thought about this a little more, and I think that it would not be so bad to have a few functions like `analyze_object` geared towards different types of plants and organs. That way people can experiment and increase flexibility without breaking the current API.
I'm still thinking about names, but might pick something long like `calculate_rosette_shape_descriptors`.
I am going to try to add a series of other shape descriptors that others seem to like for rosette analysis, mostly related to bounding circles. The following are the Lemnagrid names and the numbers used by  Camargo et al. 2014. See [Table 1](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0096889#pone-0096889-t001), Table S2, Figure 2, and Figure S1.
- Min.Enclosing.Circle.Diameter (1)
- X2nd.Moment.Principal.Axis.Small.Norm (2)
- X2nd.Moment.Principal.Axis.Large.Norm (3)
- Min.Area.Rectangle.Area (4)
- Centre.Of.Mass.To.Boundary.Distance (5)
- X2nd.Moments.Principal.Axis.Ratio (11)
- Circumference (12)
- Roundness (15; not the same as eccentricity)
- Boundary.Point.Roundness (16)
- Boundary.Points.To.Area.Ratio (18)

**Comment by nfahlgren** [comment]
We could add more outputs from analyze_object without breaking the API. It does currently require modifying `plantcv-pipeline.py`, but it's not so bad.

**Comment by nfahlgren** [comment]
There's not necessarily any harm in doing these measurements on everything.

**Comment by jshoyer** [comment]
I am slowly working on this.
I imagine that identifying minimal bounding rectangles and circles (in addition to ellipses) to calculate some of the alternative metrics listed above will be straightforward.
I think that being able to define arbitrarily oriented rectangular ROIs (possibly using the x1 y1 x2 y2 x3 y3 x4 y4 CSV format provided with the IPPN/plant-phenotyping.org dataset) might be useful.
I still intend to add an alternative way of defining circular ROIs.

A [recent preprint](https://www.biorxiv.org/content/early/2017/09/27/194449) highlights inconsistent terminology across recent _A. thaliana_-focused papers. The authors use morphometric methods based on eleven (manually defined) landmarks: the center of the plant and the tip and base of the blade of each true leaf from 8 to 12. I mention this mainly because my plant segmentation method depends on the plant center landmark (for centering circular each ROI). I am increasingly relying on the pandas `read_csv` function.

(I will probably edit this comment further)

**Comment by HaleySchuhl** [comment]
Looking back on this issue, I wanted to document here that many of you suggestions are now implemented into PlantCV. We have added `pcv.params.line_thickness` to allow for better debugging images as thickness is highly dependent on the image size. We've also replaced (most if not all) instances of red lines that get drawn with fuchsia to be color-blind friendly. Finally, most functions now return the debugging image which allows users to use `pcv.print_image` to save images of interest without saving every single image. Thanks for all the great suggestions @jshoyer !

**Comment by jshoyer** [comment]
Thanks Haley -- I have been very happy to see your progress!

I hope to test the new functionality and report back. (Perhaps I will update the figures in Chapter 3 of my [thesis](https://openscholarship.wustl.edu/art_sci_etds/1188/) or process the large datasets that I recently made public on Zenodo [records [3234035](https://zenodo.org/record/3234035), [3235784](https://zenodo.org/record/3235784), and [3236306](https://zenodo.org/record/3236306)]). You can feel free to close this issue whenever you like though. Thanks again.
