### ISSUE TITLE
Add Tutorial Contribution Guide

### ISSUE THREAD

**Issue by maliagehan** [danforthcenter/plantcv#1299]
**Is your feature request related to a problem? Please describe.**
Currently there is no PlantCV Tutorial contribution guide

**Describe the solution you'd like**
Make a separate contribution guide for Tutorials (separate from contribution guide but linked) 

**Describe alternatives you've considered**
Thought about just adding to contribution guide but that is mainly for adding to code base whereas tutorial guides might be added to by a greater number of people.

Additional context (added to what Noah wrote)
Create a PlantCV tutorial 
=========================

1. Create a new repository on GitHub (for ddpsc contributors in the danforthcenter organization)

The name should start with plantcv-tutorial

2. Clone the template repository

https://github.com/danforthcenter/plantcv-tutorial-template

3. Clone the new tutorial repository

4. Copy the files and folders from the template repository to the new repository clone

5. Update the README and index.ipynb files with your tutorial content, including data (make sure you are updating or using the correct documentation, e.g. release-4.0)

6. Add an image called tutorial_card.png to the repo, this will be used on the gallery web
page. The image should be approximately square and have a width of 200px.

7. Follow the instructions to create a Binder button in the readme

8. Commit the changes to GitHub

9. Test the tutorial on Binder
------------
10. In your PlantCV repo make a new branch (make sure you are based off the version you are working on e.g. release-4.0)

11. Go to /plantcv/docs/tutorials.md , update the binder links and link to your tutorial image

12. Go to /plantcv/docs/tutorials/'yourtutorialname' and update the binder links and nb viewer links for your tutorial 

13. in the plantcv folder check the build of the documentation:  mkdocs serve --theme readthedocs

14.  If everything looks okay then commit changes and do a pull request.

**Comment by HaleySchuhl** [comment]
Closed with #1320
