### ISSUE TITLE
Database Plotting

### ISSUE THREAD

**Issue by maliagehan** [danforthcenter/plantcv#13]
Add scripts to allow plotting from database so you can select images to plot based on more detailed metadata.

**Comment by edvm** [comment]
@maliagehan Hi! Sorry, didnt get the idea, could you please explain your feature request in more detail? If it is possible with an example/use case? :)

**Comment by maliagehan** [comment]
Sorry about the lack of reply! In a new version of PlantCV we make writing output image optional.  The write image option was added because sometimes we want/need a quick analysis of a 'big' dataset but don't need the images. To compliment this new option we are adding a script to write output images from the database information, which also includes metadata on image processing pipeline used to extract the data. My name was totally misleading, it should be called a 'database image tool'
