### ISSUE TITLE
cannot import name 'greycomatrix' from 'skimage.feature' 

### ISSUE THREAD

**Issue by simonm3** [danforthcenter/plantcv#1322]
The name has changed to graycomatrix from skimage 0.19.0.

**Comment by HaleySchuhl** [comment]
Hi @simonm3 ,

What version of PlantCV are you running? Our main stable branch requires skimage v 0.19 or newer and addresses this update.

**Comment by simonm3** [comment]
3.14. I used pip install --no-binary as the standard install fails with messages about visual studio not installed - and I did install it but the message is still there.
