### ISSUE TITLE
Documentation about find_objects and object_composition

### ISSUE THREAD

**Issue by mapapin** [danforthcenter/plantcv#1366]
Hi there :wave:
It seems that `find_objects` and `object_compostion` are no longer available in the last version. Where can I find the documentation to understand how to migrate from 3.14 to 4.0.1 ?

If no documentation exist about these functions, can someone help me get an equivalent please ? 🙏

**Comment by HaleySchuhl** [comment]
Hi @mapapin thanks for opening this issue. I think what you want is documented [here](https://plantcv.readthedocs.io/en/latest/updating/#workflow-updating-an-example). Let us know if this helps or if you have additional questions.

**Comment by mapapin** [comment]
I'm blind ! Thanks <3
