### ISSUE TITLE
Create new Outputs method for "add_metadata" 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1368]
**Is your feature request related to a problem? Please describe.**
When data is collected using annotation, or any lower throughput data collection where params are adjusted per image. There are many cases so far where data collection is happening in a jupyter notebook repeatedly rather than in parallel using plantcv-run-workflow. In these cases, we still want to let users store out metadata.

**Describe the solution you'd like**
Similar to "add_observation" method, we can make a similar method in the Outputs observations class. 

**Describe alternatives you've considered**
`Image` class which stores both numpy array img and image metadata in a specialized data structure. 

**Additional context**

**Comment by HaleySchuhl** [comment]
Right now the `Outputs` class has `measurements, images, and observations` but I'm not sure if it makes more sense to add metadata values into an existing attribute images or measurements or if it's better to add a new attribute called `metadata`?? 

Implementation of this into the `pcv.outputs.save_results` seems very straightforward for `mode="json"` but seems smart to chat about best formatting for CSV output so it's equivalent to the output from running with `plantcv-run-workflow`.

**Comment by nfahlgren** [comment]
You could add a metadata attribute to `Outputs` and then we need to have the `save_results` method merge the `Outputs` metadata in with any preexisting metadata if the results file already exists
