### ISSUE TITLE
Issues when compiling a workflow to .exe using Pyinstaller

### ISSUE THREAD

**Issue by gustafmalone** [danforthcenter/plantcv#1369]
Hello,

I'm learning PlantCV at the moment, and have just been experimenting with compiling PlantCV workflows to .exe files using Pyinstaller, as this is something I will need to be able to do in the future as part of a project I am working on.

I have been working through the [Arabidopsis multi plant tutorial](https://plantcv.readthedocs.io/en/stable/tutorials/arabidopsis_multi_plant_tutorial/) and am beginning to get a decent grasp on PlantCV. I have modified the code in this tutorial to remove any of the debug plotting, and the workflow now simply reads the input image and generates an output file. Github isn't letting me format the code properly in this post for some reason, so I've attached a screenshot. Sorry about that.

![image](https://github.com/danforthcenter/plantcv/assets/78699449/eef271f6-8103-4d83-855f-8eb17385a0f0)

This code works perfectly when I run it using

`python arabidopsis.py`

However, I am having issues when trying to compile it into a .exe using Pyinstaller. I have installed Pyinstaller into my PlantCV Anaconda environment, and am executing the following command from within a Powershell within the same Anaconda environment:

`pyinstaller --onefile arabidopsis.py`

This runs without any issues and successfully builds an exe. However, when I try to run the exe from within command line, I get the following error:

![image](https://github.com/danforthcenter/plantcv/assets/78699449/ee3edc12-ce55-44db-b13b-021e3f6d5e28)

Is there any way I can fix this? I would expect the exe to run and generate the output file just as the normal Python code would.

I suspect the error may have something to do with the fact that my user path is "C:\Users\G Malone" and not "C:\Users\GMALON~1", but that's a complete guess.

**Local environment:**
 - OS: Windows 10
 - Environment: Anaconda3
 - PlantCV Version: 4.0.1
 - Pyinstaller Version: 5.13.0

Many thanks

**Comment by gustafmalone** [comment]
Thanks @HaleySchuhl, I've just tried this but unfortunately am still getting the exact same error.

**Comment by nfahlgren** [comment]
Hi @gustafmalone, are you wanting to hardcode the input image file or are you aiming to have the executable be able to accept inputs?

**Comment by gustafmalone** [comment]
Hi @nfahlgren, for this current test the image file is hardcoded. In the future I will need to be able to have the executable accept the image file name as an input parameter.

**Comment by nfahlgren** [comment]
When I looked at this on my phone I didn't see the error message image. It looks like it's looking for a file called `jobqueue.yaml`. I don't know why or what that is, it's not something we use in PlantCV. We do use dask-jobqueue in the parallel package, but we don't configure dask with a YAML file and you are only importing `WorkflowConfig`, so it shouldn't be doing anything with `jobqueue`. It's possible Pyinstaller is being overzealous and packaging everything it can, but I'm not familiar with it.

The only thing I can suggest is that you are correct that if the path that includes `GMALON-1` is incorrect that would definitely be a problem in general

**Comment by gustafmalone** [comment]
Hi @nfahlgren,

I've tried compiling the .exe by excluding a few of the different dask modules. First I tried excluding just `dask-jobqueue`

`pyinstaller --onefile arabidopsis.py --exclude-module dask-jobqueue`

This returned the same error, which suggested that the `dask-jobqueue` module alone wasn't causing the issue. Next, I tried excluding all dask modules.

`pyinstaller --onefile arabidopsis.py --exclude-module dask --exclude-module dask-core --exclude-module dask-jobqueue --exclude-module distributed`

Once again the .exe compiled successfully, but when I tried to run it I got an error that it couldn't find the module `dask`, suggesting `dask` is required for the code to run.

Finally I tried excluding all dask related modules apart from `dask` itself:

`pyinstaller --onefile arabidopsis.py --exclude-module dask-core --exclude-module dask-jobqueue --exclude-module distributed`

This time, I got the original error once again - which tells me it's probably the `dask` module causing the issue.

I'll ask around for some help on some other forums and report back if I'm able to find a solution. Please do let me know if you have any other ideas. Thank you for all your help so far!

**Comment by nfahlgren** [comment]
Awesome, glad it's working!
