### ISSUE TITLE
error when running PlantCV over a flat directory of images

### ISSUE THREAD

**Issue by annacasto** [danforthcenter/plantcv#1370]
Hi! I'm using the latest version of PlantCV and when I try to run a workflow over a directory of images, I get the following error: 

`File "/Users/anna.casto/Documents/Projects/abiotic_chamber_experiments/light_long_term/light_long_term.py", line 21, in <module>
    img, path, filename = pcv.readimage(filename= args.image)
                                                  ^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'image'. Did you mean: 'images'?`

The beginning of my python workflow looks like this: 

```
from plantcv import plantcv as pcv
from plantcv.parallel import workflow_inputs

args = workflow_inputs()

pcv.params.debug = args.debug     

img, path, filename = pcv.readimage(filename= args.image)
```

Running `plantcv-run-workflow` with my config file does find the correct number of images (workflows?), but I keep getting the error above, and I'm not sure where I need to fix it.

**Local environment (please complete the following information):**
 - OS: macOS
 - Environment: conda
 - PlantCV Version: 4.0

**Comment by HaleySchuhl** [comment]
Hiiiiiii,

Can you send your config file please?

If you define `group_by="auto"` then you'll want to use `args.image1`, but it depends on how you set up your config file. This new feature allows timeseries and other complex image grouping. Also a note, we have released a patch from a small bug we found right after releasing v4. You'll want to update your PCV version to 4.0.1, although I don't think that it's a factor here.

**Comment by annacasto** [comment]
Oh good to know about the 4.0.1 update! Thanks! 

Jorge actually saw this earlier and told me to do the same exact thing you suggested, but he thought it wasn't the recommended way to fix the issue, so I wanted to see what y'all thought. I tried `group_by = auto` and `args.image1` and it's been working great. 
Here's my config file in case it helps to have for reference in the issue: 
[long_term_light_config.json](https://github.com/danforthcenter/plantcv/files/12860835/long_term_light_config.json)

Thanks!
