### ISSUE TITLE
roi2mask documentation needs updating

### ISSUE THREAD

**Issue by kmurphy61** [danforthcenter/plantcv#1371]
**Describe the bug**
[Documentation for release-4.0](https://plantcv.readthedocs.io/en/release-4.0/roi2mask/) describes the following function: 
# Convert the ROI contour into a binary mask
`mask = pcv.roi.roi2mask(img=img, contour=roi)`

Contours are not used in release-4.0 so this code no longer works as described and gives an error. Documentation should be updated.

**Comment by nfahlgren** [comment]
There is a typo on the doc page in the example code block, as Katie posted above
