### ISSUE TITLE
Cropreporter imaging wavelengths

### ISSUE THREAD

**Issue by wurDevTim** [danforthcenter/plantcv#1373]
Hello,

We understand that the cropreporter functionality was originally written for the cropreporter at Danforth.
Now that we are using it more and more with the systems in Wageningen, we notice some small differences. 
This week we are looking at the spectral files and noticed that plantcv assumes specific wavelengths: 

670, 500, 460nm are Red, Green, Blue from the CLR image: https://github.com/danforthcenter/plantcv/blob/21ab67f5109ffc93691243c2ad5ceccde5305eba/plantcv/plantcv/photosynthesis/read_cropreporter.py#L282

550, 700, 800nm are Anthocyanin, red-Edge, NIR from the SPC image:
https://github.com/danforthcenter/plantcv/blob/21ab67f5109ffc93691243c2ad5ceccde5305eba/plantcv/plantcv/photosynthesis/read_cropreporter.py#L289

This turns out to be configurable, in our system it is:
- 640, 550, 475nm are Red, Green, Blue
- 540, 710, 770nm are Anthocyanin, red-Edge, NIR 

This is a bit confusing for the users, and worse, the spectral indexes can be computed wrong, or in our case with suboptimal frames. As a concrete example, the Carotenoid Reflectance Index 550, that analysis will simply be wrong.
https://github.com/danforthcenter/plantcv/blob/21ab67f5109ffc93691243c2ad5ceccde5305eba/plantcv/plantcv/spectral_index/spectral_index.py#L188

Unfortunately I cannot find the exact wavelengths in the INF file of the measurement which makes it challenging to account for this automatically. It is also unclear to me how Phenovation handles this in their Da analyzer software. But I think it's important to know this happens.

**Comment by nfahlgren** [comment]
Hi Tim,

I don't think our wavelength values were based on information from the technical manual, just our educated guess about what representative wavelength would make sense for each channel. I do see in the manual that there are specified wavelengths for each filter that we can update to (that you list above).

**Comment by nfahlgren** [comment]
Updates are implemented in #1374

**Comment by autimator** [comment]
Heey Noah,

Thank you for the quick reply. If it was a guess than I am impressed by how close you got. However it is also possible that Phenovation slightly changed the wavelengths over time, as they found bands with more contrast. 
We are planning to visit phenovation in a week or two, so I can ask just to be sure if you want?

**Comment by wurDevTim** [comment]
Heey Noah,

Thank you for the quick reply. If it was a guess than I am impressed by how close you got. However it is also possible that Phenovation slightly changed the wavelengths over time, as they found bands with more contrast. 
We are planning to visit phenovation in a week or two, so I can ask just to be sure if you want?
