### ISSUE TITLE
pcv.transform.find_color_card gives error "No color card found under current parameters"

### ISSUE THREAD

**Issue by ParmaJonEman** [danforthcenter/plantcv#1377]
**Describe the bug**
Using the tutorial found here: 
https://plantcv.readthedocs.io/en/v3.11.0/find_color_card/
I tried to detect a color card. The I was given the error: "No color card found under current parameters"

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Starting with image:
![lightimage](https://github.com/danforthcenter/plantcv/assets/55207608/e2c96b4a-1acd-4ed9-8757-37c81c6fbb1f)

2. I used code: 
`img, path, filename = pcv.readimage(target) `
`df, start, space = pcv.transform.find_color_card(rgb_img=img)`

Passing in the correct image as the target. I verified that it is actually opening the image. I tried different lighting. I tried photoshopping out the tape. I tried photoshopping out the entire left side of the card and the tape. All attempts resulted in the same error message.

**Expected behavior**
I expect it to auto-detect the color card.

**Local environment (please complete the following information):**
 - OS: Windows 11
 - Environment: Virtualenv
 - PlantCV Version 4.0.1

**Additional context**
The color card we used was the Calibrite ColorChecker Passport Photo 2, one of the listed compatible cards.

**Comment by ParmaJonEman** [comment]
@nfahlgren I've tried photoshopping out that half, as well as cropping the picture so that only the right side of the picture with the right side of the color card is showing, but still get the same error message.

**Comment by HaleySchuhl** [comment]
Hi @ParmaJonEman I tested your image to see what contours are getting recognized by the detector algorithm. It looks like the edge detection is just picking up a lot of noise, and once it does filtering for "square-like" shapes there is nothing left. Can you try with a higher resolution image? 


![image](https://github.com/danforthcenter/plantcv/assets/44006936/b6c50b7e-4741-4683-9c39-4be32c3c8e29)

**Comment by ParmaJonEman** [comment]
I actually just tried with doubling the size of the image (in MSPaint, nothing fancy) and I think its detecting the color card now. I think you're right, we probably just need a higher resolution webcam.

**Comment by HaleySchuhl** [comment]
Awesome! Glad that was able to resolve. I'm also wondering if it could make sense to widen the filtering parameters and allow for smaller color card chips. We have researchers interesting in using the new "nano" color cards but currently we cannot detect them. Thanks for opening this issue! Very relevant to current work as Noah mentioned.
