### ISSUE TITLE
Cannot open images in PlantCV 4.0.1

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#1380]
**Describe the bug**

I am creating my first pipeline in for PlantCV 4. Images are stored at /home/amdimech/projects/my_experiment/img/exp/. CHMOD is set to -rw-r--r-- for all.

A comprehensive pipeline was created in Jupyter Notebooks and it worked. But the production script gets stuck at image import.

To test this, I have created a bare-bones script to analyse them, based off [this tutorial](https://plantcv.readthedocs.io/en/4.x/parallel_workflow_inputs/). It is called plantcv_mre.py

```
#!/usr/bin/env python
# coding: utf-8
from plantcv import plantcv as pcv
from plantcv.parallel import workflow_inputs

# Parse command-line arguments
args = workflow_inputs(*["rgb"])

def main():

    # Workflow
    pcv.params.debug = args.debug

    print(args.__dict__)

    args.images = str(args.images)

    rgb_img, rgbpath, rgbname = pcv.readimage(filename=args.images)

    print(rgbname)

if __name__ == '__main__':
	main()
```

A configuration file, in JSON format, has been created following the steps in the tutorial. It is called exp_mre.json

```
{
    "input_dir": "/home/amdimech/projects/my_experiment/img/exp/",
    "json": "/home/amdimech/projects/my_experiment/output/2023/10/30/test.json",
    "filename_metadata": ["other"],
    "workflow": "/home/amdimech/projects/my_experiment/code/plantcv_mre.py",
    "img_outdir": "/home/amdimech/projects/my_experiment/output/2023/10/30/",
    "include_all_subdirs": true,
    "tmp_dir": null,
    "start_date": null,
    "end_date": null,
    "imgformat": "JPG",
    "delimiter": "_",
    "metadata_filters": {},
    "timestampformat": "%Y-%m-%dT%H:%M:%S.%fZ",
    "writeimg": true,
    "other_args": {},
    "groupby": [
        "filepath"
    ],
    "group_name": "imgtype",
    "cleanup": true,
    "append": true,
    "cluster": "LocalCluster",
    "cluster_config": {
        "n_workers": 1,
        "cores": 1,
        "memory": "1GB",
        "disk": "1GB",
        "log_directory": null,
        "local_directory": null,
        "job_extra_directives": null
    },
    "metadata_terms": {
        "camera": {
            "label": "camera identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "imgtype": {
            "label": "image type",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "zoom": {
            "label": "camera zoom setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "exposure": {
            "label": "camera exposure setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "gain": {
            "label": "camera gain setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "frame": {
            "label": "image series frame identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "rotation": {
            "label": "sample rotation in degrees",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "lifter": {
            "label": "imaging platform height setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "timestamp": {
            "label": "datetime of image",
            "datatype": "<class 'datetime.datetime'>",
            "value": null
        },
        "id": {
            "label": "image identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "barcode": {
            "label": "plant barcode identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "treatment": {
            "label": "treatment identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "cartag": {
            "label": "plant carrier identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "measurementlabel": {
            "label": "experiment identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "other": {
            "label": "other identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        }
    }
}
```

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Activate the environment in Ubuntu `source ~/PlantCV-4.0.1/bin/activate`
2. Run the following command: `plantcv-run-workflow --config ~/projects/my_experiment/pcv_template/exp_mre.json`
3. Receive error on the command line:

```
Starting run 2023-10-30_16-07-08

Reading image metadata...
Reading image metadata took 0.0024251937866210938 seconds.
Building job list...
Task list includes 4 workflows
Building job list took 0.004963397979736328 seconds.
Processing images...
[                                        ] | 0% Completed |  1.8s{'images': ['/home/amdimech/projects/my_experiment/img/exp/DSC00001.JPG'], 'names': 'none', 'result': '/tmp/2023-10-30_16-07-08_xzykpl07/2530adc0-811a-470b-922b-43bf6179fbbd.json', 'outdir': '/home/amdimech/projects/rhizotron/output/2023/10/30/', 'writeimg': True, 'debug': None, 'rgb': None, 'none': '/home/amdimech/projects/my_experiment/img/exp/DSC00001.JPG'}
[ WARN:0@1.620] global loadsave.cpp:248 findDecoder imread_('['/home/amdimech/projects/my_experiment/img/exp/DSC00001.JPG']'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/home/amdimech/projects/my_experiment/code/plantcv_mre.py", line 23, in <module>
    main()
  File "/home/amdimech/projects/my_experiment/code/plantcv_mre.py", line 18, in main
    rgb_img, rgbpath, rgbname = pcv.readimage(filename=args.images)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amdimech/PlantCV-4.0.1/lib/python3.11/site-packages/plantcv/plantcv/readimage.py", line 51, in readimage
    fatal_error("Failed to open " + filename)
  File "/home/amdimech/PlantCV-4.0.1/lib/python3.11/site-packages/plantcv/plantcv/fatal_error.py", line 13, in fatal_error
    raise RuntimeError(error)
RuntimeError: Failed to open ['/home/amdimech/projects/rhizotron/img/exp/DSC00001.JPG']
....
```

When I run `test -f /home/amdimech/projects/my_experiment/img/exp/DSC00001.JPG && echo "$FILE exists."`, I get a response "exists". The file path is correct.

**Expected behavior**
A statement printing the image name indicating that the image has been successfully read.

**Local environment (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - Windows Subsystem for Linux 2 on Windows 10, packages installed with pip
 - PlantCV Version 4.0.1

**Additional context**
The tutorials are a bit of hard work. For instance in [Workflow Parallelisation](https://plantcv.readthedocs.io/en/4.x/pipeline_parallel/), there is no explanation of what `save_config` is or how to use it. 

I have to set `args.images = str(args.images)` so I don't get a "can only concatenate str (not "NoneType") to str" error. 

The example in [Parallel workflow inputs management](https://plantcv.readthedocs.io/en/4.x/parallel_workflow_inputs/) references `args.rgb` which doesn't exist when you run `print(args.__dict__)`. 

I am finding this very confusing, so I hope someone can help!

**Comment by HaleySchuhl** [comment]
Hi @AdamDimech , thanks for opening this issue. 

It's good for us to know where more detail is needed in the documentation. 

First, in v4 you will no longer wrap your workflow in a `main` function (documented all the way at the bottom of [this page](https://plantcv.readthedocs.io/en/latest/jupyter/#converting-jupyter-notebooks-to-plantcv-workflow-scripts)) but maybe should be referenced elsewhere in the docs too.

Since I think you have just one image per workflow (rather than RGB/NIR for example where you would use `args.rgb` and `args.nir` where that metadata is in the filename), you can update in your config file to `"group_name": "auto"` and then inside your workflow the argument will be automatically named `image1` so you would have this instead. 
```
rgb_img, rgbpath, rgbname = pcv.readimage(filename=args.image1)
``` 

The `save_config` method is documented separately [here](https://plantcv.readthedocs.io/en/latest/parallel_config/) with an example of use. We tried to add a section in the docs [here for updating to v4](https://plantcv.readthedocs.io/en/latest/updating/#updating-to-v4) and we can totally add more detail to hopefully make it less confusing.

**Comment by AdamDimech** [comment]
Thanks for your help @HaleySchuhl. I managed to get it working.

I actually like to write my PlantCV workflows in functions, as I add a lot of custom processes and it's a nice and tidy way of doing things. But the tip to take `pcv.readimage()` out was the key step.

I missed the specific [Updating to PlantCV 4](https://plantcv.readthedocs.io/en/latest/) information. I wonder if it needs a dedicated page on ReadTheDocs rather than as an add-on to the general updating page? Just a suggestion.

**Comment by HaleySchuhl** [comment]
Thanks Adam, I think that's a good suggestion; I had been thinking that we could link to this section of that doc in more locations, such as the homepage. You're definitely not the first person I've shared that link with haha.

Please reopen this issue with anything further
