### ISSUE TITLE
Color correction with colorcard detection produces weird results in some lighting scenarios

### ISSUE THREAD

**Issue by ParmaJonEman** [danforthcenter/plantcv#1384]
**Describe the bug**
I implemented the color correction with color card detection as specified in the PlantCV documentation. It seems to work okay with small variations of light, but has trouble with images that are darker or have weird shadows. Is there any other plantcv features I should be using for those scenarios?

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Starting with images:
![clear2plants](https://github.com/danforthcenter/plantcv/assets/55207608/4400c5dc-9f2a-4af4-9179-61f8617c3c8e)
![dark2plants](https://github.com/danforthcenter/plantcv/assets/55207608/eca6a52c-758c-488b-9581-ae7aabf8ebfa)

3. Run code:
```
    source, _, _ = pcv.readimage(sourceImg)
    target, _, _ = pcv.readimage(targetImg)
    df, start, space = pcv.transform.find_color_card(rgb_img=target, label="prefix")
    mask = pcv.transform.create_color_card_mask(rgb_img=target, radius=10, start_coord=start, spacing=space, ncols=4,
                                                nrows=6)
    target_matrix, source_matrix, transformation_matrix, corrected_img = pcv.transform.correct_color(target, mask,
                                                                                                     source, mask,
                                                                                                     output_directory)
```
4. See result
<img width="589" alt="image" src="https://github.com/danforthcenter/plantcv/assets/55207608/4c4d8ef6-7f9e-43c4-97d1-386fea35e214">

**Expected behavior**
I'd like to produce a usable image that looks similar to the source image.

**Local environment (please complete the following information):**
 - OS: Windows
 - Environment virtualenv
 - PlantCV Version 4.0.1

**Additional context**
This is in a greenhouse, so lighting will always be changing. Is this going to stop us from creating usable PlantCV workflows?

**Comment by HaleySchuhl** [comment]
Hi, thanks for opening this issue. It's possible that you'd have a better result with [affine color correction](https://plantcv.readthedocs.io/en/latest/transform_affine_color_correction/) but this is assuming that the color card mask is good (and not picking up any of the borders). We do also have a [white balance](https://plantcv.readthedocs.io/en/latest/white_balance/) function which can be helpful in preprocessing images with inconsistent lighting. 

Does the output of `pcv.transform.create_color_card_mask` appear to be accurate? If the borders are getting selected at all it can give an inaccurate sample of observed color card chip values.

**Comment by nfahlgren** [comment]
We can also get the new color card detector method merged soon: https://github.com/danforthcenter/plantcv/pull/1362

**Comment by ParmaJonEman** [comment]
<img width="112" alt="image" src="https://github.com/danforthcenter/plantcv/assets/55207608/b7b1197b-be6e-436b-99dd-6aa6bc51e57a">
Looks like its picking up the borders a little bit. Is there a way to make the samples smaller, or do I need to make sure the card is perfectly straight?

**Comment by HaleySchuhl** [comment]
I think making your radius smaller would be a suitable short term fix. As Noah mentioned, we do hav an updated algorithm that's a lot more robust to tilted color cards. While this function isn't merged into the main package at the moment, we can get it merged very soon, and in the meanwhile the code is usable on the branch called `add-detect_color_card`.

**Comment by HaleySchuhl** [comment]
We have merged in `pcv.transform.detect_color_card` with https://github.com/danforthcenter/plantcv/pull/1362 so I'm going to close this issue for now, but please don't hesitate to reopen with further questions.
