### ISSUE TITLE
Save metadata with "print_results" 

### ISSUE THREAD

**Issue by vektorious** [danforthcenter/plantcv#1389]
Hello dear plantCV devs!

I'm looking into other ways of parallelizing workflows and stumbled over this:
If I'm producing multiple results files without using the plantcv-workflow.py helper script, the files lack the metadata (which is bad because I need something to differentiate the measurements). I looked into how you get and incorporate the metadata in job_builder.py, but I wondered if it would make sense to add the possibility to include metadata to the "print_results" function as well.

print_results could get an additional, optional input (probably a dict) and add this to the results file. 

Does this make sense? Am I overlooking something?

**Comment by nfahlgren** [comment]
Hi @vektorious, this definitely makes sense and coincidentally is something we are actively working on in #1375. It should be added to PlantCV4 soon!

**Comment by vektorious** [comment]
Hey @nfahlgren,
thanks! I'm really sorry, I thought that I looked through the issues, but it seems like I missed that one. It even looks like it is basically done.

**Comment by nfahlgren** [comment]
Not a problem at all, thanks for asking about it!
