### ISSUE TITLE
Define Region of Interest (ROI) Documentation poor explanation

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#139]
Hello guys,
Another suggestion here. I believe the explanation on how to define the ROI on the fly should be better explained. I dont think the examples are good for that. Also i dont think that the descrptions:
x_adj- adjust center along x axis
y_adj- adjust center along y axis
w_adj- adjust width
h_adj- adjust height

Are well explained.

From what i understood for the rectangle case x and y are the coordinates of the top left corner while the w and h of the bottom down rectangle. I think this is quite important to mention.
0 ,0,0, -925 i dont find a good example. Maybe 100,0 -50, -925.
Also a duplicate example before that like 100,0 300, 400 or something similar would be nice.

I just feel like i spent to much time understanding this "obvious" thing.

**Comment by nfahlgren** [comment]
@MjBordalo thanks for the feedback, it's definitely appreciated. I will take a look at the documentation and see what we can do to make it more clear. Somewhat longer term I think we plan on changing the ROI function to specify the points as you suggest (upper left, lower right for rectangles for example). For v2 we made a decision to leave the function interfaces intact, so this kind of breaking change would be implemented post-v2.

**Comment by maliagehan** [comment]
We've added a figure to the documentation to (hopefully) better explain how to define an ROI for v2.0. Like Noah said the feedback is great, so that we can change that in future versions.
