### ISSUE TITLE
Error in batch processing with 'NoneType' object has no attribute 'run_line_magic'

### ISSUE THREAD

**Issue by connornelle** [danforthcenter/plantcv#1418]
When I run the command to batch process image folder in the Jupyter notebook, there are no output images despite the program completing. Definitely some problem with MPL/Ipython,  but I cannot figure it out. 

Here is the .py file I am using: 
`       
        from IPython import get_ipython
        get_ipython().run_line_magic('matplotlib', 'inline')
        import os
        import sys, traceback
        import cv2
        import numpy as np
        import argparse
        import string
        from plantcv import plantcv as pcv
        import matplotlib
        from matplotlib import pyplot as plt
        
        debug = 'plot'                                # Plot debug images to the notebook
        img_file = 'input_color_img.jpg'              # Example image
        
        def options():
            parser = argparse.ArgumentParser(description="Imaging processing with opencv")
            parser.add_argument("-i", "--image", help="Input image file.", required=True)
            parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
            parser.add_argument("-r","--result", help="result file.", required= False )
            parser.add_argument("-w","--writeimg", help="write out images.", default=False, action="store_true")
            parser.add_argument("-D", "--debug", help="can be set to 'print' or None (or 'plot' if in jupyter) prints intermediate images.", default=None)
            args = parser.parse_args()
            return args
        
        matplotlib.rcParams['figure.figsize'] = [6,6]
        
        def main():
          
            args = options()
        
            pcv.params.debug=args.debug #set debug mode
            pcv.params.debug_outdir=args.outdir #set output directory
        
            
            img, path, filename = pcv.readimage(filename=args.image, mode='rgb')
        
        class options:
            def __init__(self):
                self.image = "/Users/conno_pd3n2r6/OneDrive/Pictures/jpg/IMG_a_IGP9834.jpg"
                #self.image = "/Users/conno_pd3n2r6/OneDrive/Pictures/pentaxPicsJune12_2023b/originalPics/IMG_1_IGP9934.jpg"
                #self.image = "/Users/conno_pd3n2r6/OneDrive/Pictures/originalPics/IMG_2_IGP0002.jpg"
                self.debug = "plot"
                self.writeimg = False
                self.result = "results.txt"
                self.outdir = "."
        args = options()
        pcv.params.outdir = args.outdir
        pcv.params.debug = args.debug
        
        
        pcv.params.text_size = 20
        pcv.params.text_thickness = 10
        
        img, path, img_filename = pcv.readimage(filename=args.image)
        
        rotate_img = pcv.transform.rotate(img, 90, False)
        
        df, start, space = pcv.transform.find_color_card(rgb_img=rotate_img, threshvalue=125)
        
        mask_color = pcv.transform.create_color_card_mask(rgb_img=rotate_img, radius=10, start_coord=start, spacing=space, ncols=6, nrows=3)
        avg_chip_size = pcv.outputs.observations['default']['color_chip_size']['value']
        
        cs_plot = pcv.visualize.colorspaces(rgb_img=img, original_img=False)
        
        a = pcv.rgb2gray_lab(img, 'a')
        
        a_thresh = pcv.threshold.binary(gray_img = a, threshold= 127, object_type="dark")
        
        a_fill = pcv.fill(bin_img=a_thresh, size = 1000)
        
        roi = pcv.roi.rectangle(img, 1600, 1000, 600, 600)
        
        mask_bin = pcv.roi.filter(mask=a_fill ,roi = roi, roi_type = "partial")
        
        shape_img = pcv.analyze.size(img=img,labeled_mask=mask_bin, n_labels=1)
        
        pcv.outputs.save_results(filename="results.txt", outformat="json")
        
        if __name__ == "__main__":
            main()'

**To Reproduce**
I run the function
` plantcv-run-workflow --config "C:\Users\conno_pd3n2r6\OneDrive - Montana State University\Documents\Lachowiec Lab\config.json"` 
in the Jupyter lab notebook and get the error: 
`AttributeError: 'NoneType' object has no attribute 'run_line_magic'
Traceback (most recent call last):
  File "C:\Users\conno_pd3n2r6\OneDrive - Montana State University\Documents\Lachowiec Lab\wildOatsTest2.py", line 6, in <module>`
This occurs for every image in the batch. The line in question is:

`get_ipython().run_line_magic('matplotlib', 'inline')`

It confuses me because this needs IPython to run, but even if I run the command within IPython in the Jupyter terminal, it says invalid syntax. 

 I am on Windows 10, running PlantCV 4.0.1. Hopefully this is just user error, I am stumped!

Thank you for the help!
Connor

**Comment by nfahlgren** [comment]
Hi @connornelle, when you convert from Jupyter to a Python script, the line `%matplotlib inline` is converted to Python code `get_ipython().run_line_magic('matplotlib', 'inline')`. That code is specific to Jupyter and should be commented out or deleted in the Python script.

Also note that in PlantCV4, you do not need to create the class `options` or group your code into a `main` function anymore: https://plantcv.readthedocs.io/en/stable/jupyter/

That being said, one update to your code is required to save output images (`shape_img` for example). Minimally you will need to add one line of code to save the image (`pcv.print_image`), or a couple if you want it to be controllable:

```python
if args.writeimg:
    pcv.print_image(shape_img, os.path.join(args.outdir, f"{img_filename[:-4]}_shapes.png"))
```

**Comment by connornelle** [comment]
Thank you for the response, I've updated the code but I am still running into errors. The new code is:

`
    from IPython import get_ipython
    import os
    import sys, traceback
    import cv2
    import numpy as np
    import argparse
    import string
    from plantcv import plantcv as pcv
    from plantcv.parallel import workflow_inputs
    import matplotlib
    from matplotlib import pyplot as plt
    
    args = workflow_inputs()
    
    #matplotlib.rcParams['figure.figsize'] = [6,6]
    
    pcv.params.debug=args.debug #set debug mode
    pcv.params.dpi = 100
    pcv.params.text_size = 20
    pcv.params.text_thickness = 20
    
    img, path, filename = pcv.readimage(filename=args.image, mode='rgb')
    
    rotate_img = pcv.transform.rotate(img, 90, False)
    
    df, start, space = pcv.transform.find_color_card(rgb_img=rotate_img, threshvalue=125)
    
    # Use these outputs to create a labeled color card mask
    mask_color = pcv.transform.create_color_card_mask(rgb_img=rotate_img, radius=10, start_coord=start, spacing=space, ncols=6, nrows=3)
    avg_chip_size = pcv.outputs.observations['default']['color_chip_size']['value']
    
    cs_plot = pcv.visualize.colorspaces(rgb_img=img, original_img=False)
    
    a = pcv.rgb2gray_lab(img, 'a')
    
    a_thresh = pcv.threshold.binary(gray_img = a, threshold= 127, object_type="dark")
    
    a_fill = pcv.fill(bin_img=a_thresh, size = 1000)
    
    roi = pcv.roi.rectangle(img, 1600, 1000, 600, 600)
    
    mask_bin = pcv.roi.filter(mask=a_fill ,roi = roi, roi_type = "partial")
    
    shape_img = pcv.analyze.size(img=img,labeled_mask=mask_bin, n_labels=1)
    
    pcv.outputs.save_results(filename="results.txt", outformat="json")
    
    if args.writeimg:
        pcv.print_image(shape_img, os.path.join(args.outdir, f"{id[:-4]}_shapes.png"))
    
    #if __name__ == "__main__":
        #main()
`

and the error is 

`
      Traceback (most recent call last):
        File "C:\Users\conno_pd3n2r6\OneDrive - Montana State University\Documents\Lachowiec Lab\wildOatsRedo.py", line 25, in <module>
          img, path, filename = pcv.readimage(filename=args.image, mode='rgb')
                                                       ^^^^^^^^^^
      AttributeError: 'Namespace' object has no attribute 'image'. Did you mean: 'images'?
`

Trying to understand the workings behind this, does the workflow_inputs() function pull from the config.json? There is no attribute "images" in the config. When converting from juptyer notebook to .py I don't see how the `names = "image"` is retained. I see in the documentation the kwargs parameter, but I am not sure how to use it. The images I am running this over are unfortunately not descriptively named (ex: IMG_a_IGP9743), which is why I opted to just use "id" in the config.json. 

Thank you for your help, I really appreciate it.

**Comment by nfahlgren** [comment]
In your config file I would recommend setting `group_name` to `"auto"`, then in your Python script change `args.image` to `args.image1`.

When `group_name` is set to auto it numbers the input images from 1 to n (though typically most people only have one image). Otherwise `group_name` can be used to parameterize the `names` input option using metadata terms.
