### ISSUE TITLE
Improve Multiplant pipeline 

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#142]
Hello guys,
Part of my project is about measuring the lettuce area (weight actually). I have several so i ran the multiplant pypeline and afterwards the VIS one. Atough i am having some difficulties now that the size of the lettuce are getting bigger.
1) The lettuce are overlaping. I tought about drwaing a whitle grid on top of the image so at least i got 4 different zones

2) The thresholds are not perfect. I would like to know for example on the vis pipeline with does some of the regions (that i draw with paint in red) are afterwards considered as plant and other not? altought the size of the regions look smaller even tought these regions do not disapear.

3) Why does multipipline does a threshold based on a LAB conversion image and VIS pipeline based on HSV conversion

4) Should i think about the ideia of putting a blue blackground or something like that?

Thanks. I am not sure if i express myself properly enought. Let me know if that is the case 

![2_whitebalance](https://cloud.githubusercontent.com/assets/24882807/25178729/f0d9e93a-24fe-11e7-9dfd-040c3ef648a3.png)
![12_clusters](https://cloud.githubusercontent.com/assets/24882807/25178783/2eb956e6-24ff-11e7-8c89-cf89df52abed.png)
![22_objcomp_mask](https://cloud.githubusercontent.com/assets/24882807/25179419/bf47d104-2501-11e7-9766-9cb41bad2cec.png)
![23_shapes](https://cloud.githubusercontent.com/assets/24882807/25178785/2ebbac16-24ff-11e7-81c4-a7087a49db79.jpg)

**Comment by jshoyer** [comment]
1.  Plants that touch or occlude each other can definitely be challenging to disambiguate/segment individually. I do not think that there is a single clear consensus method for dealing with this. [Kelly et al.](http://doi.org/10.1007/s00138-015-0728-4) list it as a major priority for research. I do not entirely understand your white grid idea, but splitting up the image is one approach.
2.  Just how good do you need your segmentation to be, and over what timescale? If your main goal is to estimate fresh or dry weight with this type of spacing their might be inherent limits to this approach. Have you tried calibrating/validating with fresh or dry weight measurements yet? Have you looked at the other tools that PlantCV has for thresholding?
3. I think thresholding based on the saturation channel works best with a white background. Thresholding on the a* component in L\*a\*b* space is more common with top-down images with relatively dark (soil) backgrounds. The Vis pipeline walk-through example uses both HSV and L\*a\*b* spaces.
4. I would guess that a blue background will not help much, though it is possible that it could reduce mis-segmentation of those shadowy areas in between leaves.

**Comment by maliagehan** [comment]
@MjBordalo can you include your processing script? It could also work to do an dilation/erosion, then to use the resulting masks as ROIs. But @jshoyer is correct, as soon as the objects touch they will be merged.

**Comment by jshoyer** [comment]
Hi @MjBordalo, I poked around and found the [compute_LAI.py](https://github.com/MjBordalo/hgco/blob/master/scripts/compute_LAI.py) script you pushed to GitHub. I see that it is adapted from the [multi-plant image pipeline walkthrough](http://plantcv.readthedocs.io/en/latest/multi-plant_tutorial/).

As Malia and I mentioned, grouping of objects that touch is an inherent limitation of current PlantCV-based approaches. PlantCV ROIs are designed to be inclusive of (disconnected) objects that stick out of them, not for defining boundaries between plants or organs. That said, new functions based on defined boundaries (including arbitrary "scribbles") could be added. Alternatively, current object erosion and/or watershed transformation+distance transform functions might help you delay lumping of your plants together.
More information about your goals could help, especially if you are interested in developing new functions yourself.

Thanks again for your feedback.

**Comment by MjBordalo** [comment]
ahaha nice poking indeed.

Sorry for my absence. My thesis project was not really focused on the CV field so i did not wanted to dig it so much further. Therefore i basically went to my greenhouse every time my plants overlapped :).

I have to thank you for your support because with such an easy implementation pipelines i was able to properly follow and model plant growth ( for curiosity using the logistic function).

Therefore, with the conclusion of my thesis, i dont have new goals so far. However, i might continue working in the CV field with plants. And I was really satisfied with PlantCv so maybe I'll stick around.

Just out of curiosity do you guys know if plantCV is being used by the [openag ](https://www.media.mit.edu/) project?

Thanks again for the support.

**Comment by jshoyer** [comment]
Congrats on finishing your thesis. I'm glad the existing functionality was good enough for your purposes.

With regard to the Media Lab OpenAg Initiative, they have written some of their own Python/OpenCV-based code for image analysis. See https://github.com/OpenAgInitiative/openag_cv/tree/master/src
@edcafenet, have you looked at PlantCV at all?

There was also some interest from someone in St. Louis, but I do not know if that led to anything. See http://forum.openag.media.mit.edu/t/cv-and-image-processing-for-the-pfc/273

**Comment by maliagehan** [comment]
Going to close this issue but feel free to re-open.
