### ISSUE TITLE
Problems detecting color card. 

### ISSUE THREAD

**Issue by mariameraz** [danforthcenter/plantcv#1452]
Hi!! I am not able to detect the color card using the function detect_color_card in PlantCV 4.2.1 (Ubuntu 20.04). It gives my a strange output. Any suggestions about how to deal with it please? Thanks!

Here is my code and output:
`pcv.plot_image(crop_img)`

![output](https://github.com/danforthcenter/plantcv/assets/72315459/db157b0d-e87e-4dda-b535-941b79d6594f)

`card_mask = pcv.transform.detect_color_card(rgb_img=crop_img)`
`headers, card_matrix = pcv.transform.get_color_matrix(rgb_img=crop_img, mask=card_mask)`
 
![detect_color_card](https://github.com/danforthcenter/plantcv/assets/72315459/896874e2-73dd-402f-b479-124f5b155aaa)

`std_color_matrix = pcv.transform.std_color_matrix (pos=1)`
`img_cc = pcv.transform.affine_color_correction(crop_img, card_matrix, std_color_matrix)`

![output](https://github.com/danforthcenter/plantcv/assets/72315459/8a0a8397-05c6-465e-b310-aa2aba5232bd)

**Comment by HaleySchuhl** [comment]
Hi @mariameraz thanks for opening this issue. The new `detect_color_card` is recognizing which corner the white chip is in and numbering colors in the same order as is `pos=3` regardless of the card's actual apparent orientation, so I think you will get expected color correction when you change this step:  `std_color_matrix = pcv.transform.std_color_matrix (pos=3)` and please let us know if this resolves it!

**Comment by mariameraz** [comment]
Hi Haley, 

Thank you very much for your help.It solved the problem!! 

`std_color_matrix = pcv.transform.std_color_matrix (pos=3)`
`img_cc = pcv.transform.affine_color_correction(crop_img, card_matrix, std_color_matrix)`
![output](https://github.com/danforthcenter/plantcv/assets/72315459/66d3fd5d-60e0-4df8-9fb9-72ff9408f224)


Have a nice day, 
Alejandra
