### ISSUE TITLE
Problem with transform.merge_images tests

### ISSUE THREAD

**Issue by k034b363** [danforthcenter/plantcv#1479]
**Describe the bug**
Not really a bug, I just realized that the tests for merge_images are structured incorrectly. They have assert statements in the form of: assert image1.all() == image2.all(), which I think is just testing that two things exist? I think they should be: assert (image1 == image2).all() maybe? 

Doesn't really hurt anything, it is just an uninformative set of tests. I will fix in a linked branch.

**Comment by HaleySchuhl** [comment]
Replicated locally and can confirm that the updated syntax is more strict at testing for pixel-by-pixel sameness in images. 
![image](https://github.com/danforthcenter/plantcv/assets/44006936/3512928f-4cad-4bf7-9b4c-5f986b71ab72)
