### ISSUE TITLE
zsh: command not found: plantcv-workflow.py 

### ISSUE THREAD

**Issue by saraqc123** [danforthcenter/plantcv#1485]
Good evening, I have been following the workshop on YouTube (really helpful!) and trying to build my own code to analyze my image pictures. 

However, every time when i try to do the "plantcv-workflow.py --config multi-plant-analysis.config" part, i always get the error massage "zsh: command not found: plantcv-workflow.py ". Does anyone know why? 

I am using Visual Studio Code currently on my Mac. I have tried Anaconda - Jupyter notebook previously and it had the same issue. Thank you!

**Comment by nfahlgren** [comment]
Hi @saraqc123, in PlantCV4 that program was renamed to `plantcv-run-workflow`. Thanks!

**Comment by saraqc123** [comment]
Thank you @nfahlgren ! I was able to run it but run into another issue.... 
<img width="835" alt="Screenshot 2024-04-03 at 11 52 09 PM" src="https://github.com/danforthcenter/plantcv/assets/165905971/09703e0a-7696-4c95-bfe8-9d84caec7509">

**Comment by nfahlgren** [comment]
Great, thanks @saraqc123! You can ignore error messages from the distributed scheduler that occur after the "Processing results" step, sometimes the parallel scheduler throws error messages when it shuts down. It looks like your configuration did not find any images to analyze ("Task list includes 0 workflows"). That would suggest that one of the configuration settings does not match your dataset (e.g. `filename_metadata`, `delimiter`, `imgformat`, etc.).
