### ISSUE TITLE
Batch processing not finding images

### ISSUE THREAD

**Issue by theiamroar** [danforthcenter/plantcv#1486]
I have been trying to use the /path/to/plantcv-run-workflow.py --config path/to/myconfigfile.json to go through a series of images in a folder. I've reduced the directory with images to only one to make processing/testing faster. After that code begins to process the image, it kicks out -> error: the following arguments are required: --image.

The workflow does recognize there is a jpg file and if I change the imgtype then it reverts to zero. Additionally, my results file does pick up on the file metadata so it seems that its not recognizing the image itself.

The image within the folder has a file name of 2024-03-24_09:17:59.jpg

**Local environment:**
 - OS: macOS
 - Environment: I'm using a virtual environment in PyCharm
 - PlantCV Version: 4.2.1

Terminal Output:
(.venv) (base) collin@Collins-MacBook-Pro-2 pythonProject % python3 /Users/collin/PycharmProjects/pythonProject/.venv/bin/plantcv-run-workflow --config workflow.json                                                            
Starting run 2024-04-07_10-02-47

Reading image metadata...
Reading image metadata took 0.0016160011291503906 seconds.
Building job list... 
Task list includes 1 workflows
Building job list took 0.0011029243469238281 seconds.
Processing images... 
[                                        ] | 0% Completed |  1.2susage: plantPictureLabBatch.py [-h] --image IMAGE --result RESULT --outdir OUTDIR [--writeimg] [--debug DEBUG]
plantPictureLabBatch.py: error: the following arguments are required: --image
Processing images took 2.9785962104797363 seconds.
Processing results... 
Processing results took 0.003233671188354492 seconds.

Others:
My config file: {
    "input_dir": "/Users/collin/PycharmProjects/pythonProject/ImageValidationTop",
    "json": "/Users/collin/PycharmProjects/pythonProject/results.txt",
    "filename_metadata": ["timestamp"],
    "workflow": "/Users/collin/PycharmProjects/pythonProject/plantPictureLabBatch.py",
    "img_outdir": "/Users/collin/PycharmProjects/pythonProject/output_images",
    "include_all_subdirs": true,
    "tmp_dir": null,
    "start_date": null,
    "end_date": null,
    "imgformat": ".jpg",
    "metadata_filters": {},
    "timestampformat": "%Y-%m-%d_%H:%M:%S",
    "writeimg": true,
    "other_args": {},
    "groupby": [
        "filepath"
    ],
    "group_name": "imgtype",
    "cleanup": true,
    "append": false,
    "cluster": "LocalCluster",
    "cluster_config": {
        "n_workers": 1,
        "cores": 1,
        "memory": "1GB",
        "disk": "1GB",
        "log_directory": null,
        "local_directory": null,
        "job_extra_directives": null
    },
    "metadata_terms": {
        "camera": {
            "label": "camera identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "imgtype": {
            "label": "image type",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "zoom": {
            "label": "camera zoom setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "exposure": {
            "label": "camera exposure setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "gain": {
            "label": "camera gain setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "frame": {
            "label": "image series frame identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "rotation": {
            "label": "sample rotation in degrees",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "lifter": {
            "label": "imaging platform height setting",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "timestamp": {
            "label": "datetime of image",
            "datatype": "<class 'datetime.datetime'>",
            "value": null
        },
        "id": {
            "label": "image identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "barcode": {
            "label": "plant barcode identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "treatment": {
            "label": "treatment identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "cartag": {
            "label": "plant carrier identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "measurementlabel": {
            "label": "experiment identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        },
        "other": {
            "label": "other identifier",
            "datatype": "<class 'str'>",
            "value": "none"
        }
    }
}

Any help is appreciated and if you need anything else please let me know, thank you!

**Comment by nfahlgren** [comment]
Hi @theiamroar, the error you see is from your Python workflow. The workflow needs to have certain input parameters that are set by plantcv-run-workflow. Documentation on converting from a workflow in Jupyter to a Python script are documented here: https://plantcv.readthedocs.io/jupyter/

**Comment by theiamroar** [comment]
Thank you for the quick response! I did the conversion and I think that helped. However, I'm now getting an error on reading the image while using: img, path, filename = pcv.readimage(filename=args.image) 

which gives me:

Reading image metadata...
Reading image metadata took 0.0016052722930908203 seconds.
Building job list... 
Task list includes 1 workflows
Building job list took 0.0011599063873291016 seconds.
Processing images... 
[                                        ] | 0% Completed |  1.3sTraceback (most recent call last):
  File "/Users/collin/PycharmProjects/pythonProject/plantPictureLab.py", line 171, in <module>
    main()
  File "/Users/collin/PycharmProjects/pythonProject/plantPictureLab.py", line 47, in main
    img, imgpath, imgname = pcv.readimage(filename=args.image)
                                                                                        ^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'image'. Did you mean: 'images'?

I haven't seen the command written as images before, but after adding the 's' I got a different error:

  File "/Users/collin/PycharmProjects/pythonProject/plantPictureLab.py", line 171, in <module>
    main()
  File "/Users/collin/PycharmProjects/pythonProject/plantPictureLab.py", line 47, in main
    img, path, filename = pcv.readimage(filename=args.images)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/collin/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/plantcv/plantcv/readimage.py", line 44, in readimage
    img = cv2.imread(filename, -1)
          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't convert object to 'str' for 'filename'

I'm not sure how to approach this. Additionally, I am using workflow_inputs and args = workflow_inputs() to pass in the config information.

**Comment by nfahlgren** [comment]
Hi @theiamroar, the issue is with the setting `group_name`, which is `"group_name": "imgtype",` by default. For what you are doing the most straightforward setting in the configuration file is:

```
"group_name": "auto",
```

When set to auto, the input image(s) are numbered, so you would update your Python workflow to use `args.image1` instead of `args.image`.

The PlantCV team really needs to change the default value for `group_name` to `auto` because it's a more common setting than `imgtype` or another metadata term.

**Comment by theiamroar** [comment]
That did it! Thank you so much!
