### ISSUE TITLE
Import Error: No module named multiprocessing

### ISSUE THREAD

**Issue by AntonSax** [danforthcenter/plantcv#153]
### Description
I'm currently trying to run the pipeline parallelization, but when I try to run the program I'm told that there is an error importing multiprocessing as mp because there is no module name multiprocessing. 

### Details

Based off of [this webpage](http://plantcv.readthedocs.io/en/latest/pipeline_parallel/) I've created a .sh file to run plantcv-pipeline.py and the VIS pipeline over multiple pictures. I'm using Git Bash and typing in

> sh pipeline_parallelization.sh

to run the file. It immediately tells me the import failed.

> $ sh pipeline_parallelization.sh
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "C:/Users/askz6/plantcv/plantcv-pipeline.py", line 5, in <module>
    import multiprocessing as mp
ImportError: No module named multiprocessing
real    0m0.111s
user    0m0.015s
sys     0m0.015s

I've also run 

> pip install multiprocess

and then rerun the program but nothing changed.

Additionally, this is also on Windows 7.

**Comment by nfahlgren** [comment]
@AntonSax I was not familiar with Git Bash, so I installed it on my Windows test machine but was not able to get it to run Python (at least not the way I needed, though I am probably doing something wrong). I have had the most success on Windows using Anaconda as documented [here](http://plantcv.readthedocs.io/en/latest/installation/#windows). I doubled checked my Anaconda install to make sure that the `plantcv-pipeline.py` script worked with multiprocessing and confirmed that it does work on Windows. In the Anaconda setup I did not use a Bash script however, instead I ran the command directly in the Anaconda console.

Would this work for you or do you have a good Git Bash setup that you would rather not have to move away from?

**Comment by AntonSax** [comment]
@nfahlgren Thanks for your help. I switched to just using the Anaconda console and skipping the Bash script and the `plantcv-pipeline.py ` program seems to work with one exception. The program gathers how many files I have in a folder (48) and then proceeds to run the program. However, instead of running the program once for each image, the program runs 48 times for the one image.

I know the issue is that I have set 

```
# Read image
img, path, filename = pcv.readimage(args.image)
``` 
to
```
# Read image
img_file = "some_image_file.png"
img, path, filename = pcv.readimage(img_file)
``` 
as you suggested here: [https://github.com/danforthcenter/plantcv/issues/151](https://github.com/danforthcenter/plantcv/issues/151)

Do I need to switch this back and add the [`def options():`](http://plantcv.readthedocs.io/en/latest/vis_tutorial/)?

**Comment by nfahlgren** [comment]
@AntonSax in the "pipeline" scripts that are supplied to `plantcv-pipeline.py` with the `-p` option there does need to be the options function (or at least something that will parse the command-line arguments). This is because `plantcv-pipeline.py` builds the individual image processing commands with some expected arguments. The minimum set of options that are currently required are:

```
--image (the input image path and filename)
--outdir (path to where output files should go)
--result (path and filename for the text output from the pipeline script)
```

**Comment by AntonSax** [comment]
I've figured it out. Thank you for your help.
