### ISSUE TITLE
Please Update the NIR Pipeline Tutorial

### ISSUE THREAD

**Issue by AntonSax** [danforthcenter/plantcv#154]
### Description

The page at [http://plantcv.readthedocs.io/en/latest/nir_tutorial/](http://plantcv.readthedocs.io/en/latest/nir_tutorial/) suggests that the erode function takes kernels as input: 

```
# Prepare a few small kernels for morphological filtering
    kern = np.zeros((3,3), dtype=np.uint8)
    kern1 = np.copy(kern)
    kern1[1,1:3]=1
    kern2 = np.copy(kern)
    kern2[1,0:2]=1
    kern3 = np.copy(kern)
    kern3[0:2,1]=1
    kern4 = np.copy(kern)
    kern4[1:3,1]=1

    # Prepare a larger kernel for dilation
    kern[1,0:3]=1
    kern[0:3,1]=1

    # Perform erosion with 4 small kernels
    device, e1_img = pcv.erode(tr_es_img, kern1, 1, device, args.debug)
    device, e2_img = pcv.erode(tr_es_img, kern2, 1, device, args.debug)
    device, e3_img = pcv.erode(tr_es_img, kern3, 1, device, args.debug)
    device, e4_img = pcv.erode(tr_es_img, kern4, 1, device, args.debug)

    # Combine eroded images
    device, c12_img = pcv.logical_or(e1_img, e2_img, device, args.debug)
    device, c123_img = pcv.logical_or(c12_img, e3_img, device, args.debug)
    device, c1234_img = pcv.logical_or(c123_img, e4_img, device, args.debug)
```

but according to this page: [https://github.com/danforthcenter/plantcv/issues/54](https://github.com/danforthcenter/plantcv/issues/54) they 

> only accept odd integers and build the kernels internally.

### Details

This would simply prevent the next person that reads the documentation from confusing themselves on why `erode()` doesn't work with a kernel.

### Completion Criteria
- [ ] Rewrite documentation

**Comment by nfahlgren** [comment]
@AntonSax thanks for pointing this out! The documentation has been updated.
