### ISSUE TITLE
Bug in json2csv

### ISSUE THREAD

**Issue by kmurphy61** [danforthcenter/plantcv#1554]
**Describe the bug**
When converting a results.json file to .csv using `plantcv-utils json2csv` some traits are not in the converted file, i.e. present in json but not in the csv. Namely, center of mass (although there may be others). 

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Starting with the attached config.json file. 
[results_2024-04-12.json](https://github.com/user-attachments/files/15888781/results_2024-04-12.json)

2. Run function `plantcv-utils json2csv -j /results_2024-04-12.json -c /results_2024-04-12.csv'
3. See resulting csv, that does not contain all traits, particularly center of mass. 
[results_2024-04-12.csv-single-value-traits.csv](https://github.com/user-attachments/files/15888784/results_2024-04-12.csv-single-value-traits.csv)

**Expected behavior**
All measurements in json should be in csv. 

**Local environment (please complete the following information):**
 - OS: macOS
 - Environment: conda
 - PlantCV Version '4.0.1'

**Comment by annacasto** [comment]
I think we figured out that the center of mass traits are in the multi-value trait file since they have x and y values. Did that solve the issue or were we still having problems with the conversion?

**Comment by kmurphy61** [comment]
Center of Mass is being left in multi-value traits, since it provides an X,Y coordinate!
