### ISSUE TITLE
pct.segment_image_series

### ISSUE THREAD

**Issue by ski-pow** [danforthcenter/plantcv#1568]
Hi there-   the command    

pcv.segment_image_series 

wants a list of images for the    rois      parameter.  However the pcv.roi.multi   doesn't return a list (but an object class). In 
the old version  it was a list.     Anyone know how convert the output from pcv.roi.multi   for  pcv.segment_image_series.

Thanks!

Mark

ps. I can attache code too. 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Starting with image '...'
2. Run function(s) '....'
3. See error

**Expected behavior**

**Local environment (please complete the following information):**
 - OS: [e.g. Linux, macOS, Windows]
 - Environment [e.g. conda, virtualenv, pip, docker, etc.]
 - PlantCV Version [e.g. 3.6.0]

**Additional context**

**Comment by HaleySchuhl** [comment]
@ski-pow thank you for opening this issue. This function seems to have gotten missed while changing the syntax of multi-object and ROI handling between version 3 and 4 of PlantCV. We can address this and make this function easier to use under the updated syntax. 

In the meanwhile, here's how I got around it. 
```
...
valid_rois = rois.contours

imgs_list = ["./imgs/arabidopsis_tray-Copy1.jpg", "./imgs/arabidopsis_tray-Copy2.jpg"]
masks_list = ["./masks/arabidopsis_tray-Copy1_mask.jpg", "./masks/arabidopsis_tray-Copy2_mask.jpg"]

analysis_image = pcv.segment_image_series(imgs_paths=imgs_list, masks_paths=masks_list, rois=valid_rois, save_labels=True, ksize=3)
```
![arabidopsis_tray-Copy1_mask](https://github.com/user-attachments/assets/2177ee3c-55db-4c82-93c4-c8b4a541c6d2)
![arabidopsis_tray-Copy1](https://github.com/user-attachments/assets/2d50b2b7-43c3-4a85-afa5-f3032e13d2d6)

**Comment by ski-pow** [comment]
Thanks!
________________________________

**Comment by HaleySchuhl** [comment]
Awesome, I'm going to close this issue for now and then link to it a new issue detailing the updating steps for our dev team. Thanks again for bringing this to our attention!
