### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by mohamhedba123** [danforthcenter/plantcv#1579]
Hello GitHub Community,

I am working on a research project that involves high-throughput phenotyping of morphological orange  fruits characteristics using X-Ray computed tomography (CT). I am particularly interested in any available code related to:

- Analyzing 3D images of orange fruits obtained from CT scans
- Extracting morphological features from these images
- Using deep learning techniques for image processing and analysis
- Any open-source libraries or frameworks that can facilitate this research

If anyone has developed or knows of any repositories that might be relevant to this topic, please share the links or resources.

Thank you for your assistance!

Best regards,

**Comment by nfahlgren** [comment]
Hi @mohamhedba123, this is not something PlantCV can do at the moment, but I can suggest looking at this paper by Amézquita and colleagues: https://nph.onlinelibrary.wiley.com/doi/10.1002/ppp3.10333. The code they used is available on GitHub here: https://github.com/amezqui3/vitaminC_morphology. I hope that helps!

**Comment by mohamhedba123** [comment]
Dear  Noah Fahlgren

Thank you very much for your prompt response and for sharing the paper by
Amézquita and colleagues, as well as the GitHub repository. I appreciate
your guidance and will definitely explore the resources you provided.

**Comment by HaleySchuhl** [comment]
Closing this issue for now but please feel welcome to reopen with further questions or suggestions.
