### ISSUE TITLE
Thank you for your work, why can't the public dataset be accessed

### ISSUE THREAD

**Issue by yalungelin** [danforthcenter/plantcv#1581]
Thank you for your work, why can't the public dataset be accessed

**Comment by nfahlgren** [comment]
Hi @yalungelin, the data page moved to a new place: https://datasci.danforthcenter.org/data/. When the PlantCV website was redesigned I forgot to include a page that links to datasets.

**Comment by yalungelin** [comment]
> 您好@yalungelin ，数据页面已移至新位置： https://datasci.danforthcenter.org/data/ 。当 PlantCV 网站重新设计时，我忘记添加一个链接到数据集的页面。

extremely grateful

**Comment by HaleySchuhl** [comment]
Thanks for bringing this to our attention. I'm closing this issue for now but please feel welcome to reopen with further questions and suggestions.
