### ISSUE TITLE
Analysis fails if one ROI is empty

### ISSUE THREAD

**Issue by rayn-alex** [danforthcenter/plantcv#1588]
**Describe the bug**
_roi_filter() fails if ROI is empty and roi_type set to "largest"
line 89:
`index = np.argmax([cv2.contourArea(c) for c in kept_cnt])`
_ValueError: attempt to get argmax of an empty sequence_

_roi_filter() it works if roi_type is set to "partial" or "cutto", however, analyze.spectral_index() fails subsequently if one ROI is empty:
line 89 in _analyze_index:
`observed_max = np.nanmax(masked_array)`
_ValueError: zero-size array to reduction operation fmax which has no identity_

**To Reproduce**
1. Analyze image with an empty ROI
2. Use create_labels() and analyze.spectral_index()
3. See error

![image](https://github.com/user-attachments/assets/075db24d-08b5-4ffe-9b9b-d7b6cf9a8612)

**Expected behavior**
Skip ROI if it is empty

**Local environment (please complete the following information):**
 - OS: ArchLinux
 - Environment: conda venv, plantCV installed via pip
 - PlantCV Version 4.4

**Additional context**
This is relevant if image series are analyzed and ROIs happen to be empty in an image.

**Comment by rayn-alex** [comment]
I can take care of the fix. Can somebody please confirm that these two bugs?

I dug a bit deeper. 

**_analyze_index() bug:**
If the ROI is empty, the masked_array in _analyze_index() (line 77) is empty, which causes the crash. So a simple check of masked_array and adding default outputs for index_mean, index_median, index_std and "hist_percent" should do it. 

Q: What should the default output values be? Is `None` possible? 

**_roi_filter()  bug:**
I guess this one is the easiest. A simple check if kept_cnt is empty should do it:
`if roi_type.upper() == 'LARGEST' and kept_cnt:`

**Comment by HaleySchuhl** [comment]
Hi @rayn-alex thanks for opening this issue. I do not think this is a true bug, as using `_roi_filter` directly is not the intended use. I've attached the jupyter notebook from our [multi-plant tutorial](https://plantcv.readthedocs.io/en/latest/tutorials/arabidopsis_multi_plant_tutorial/), which includes an "empty ROI" example. We instead intend for user to call `pcv.create_labels` when they have more than one ROI. 
 
![arabidopsis_tray](https://github.com/user-attachments/assets/9e11972a-4d9c-4ca2-b354-b31931e541ef)
```

# # Section 1: Importing Image and Libraries
# Set the notebook display method
get_ipython().run_line_magic('matplotlib', 'widget')
# Import libraries
from plantcv import plantcv as pcv 
from plantcv.parallel import WorkflowInputs

# Input/output options
args = WorkflowInputs(
    images=["arabidopsis_tray.jpg"],    
    names="image1",
    result="arabidopsis_results",
    outdir=".",
    writeimg=True,
    debug="plot",
    sample_label="genotype"
    )

# Set debug to the global parameter 
pcv.params.debug = args.debug

# Set plotting size (default = 100)
pcv.params.dpi = 100

# Increase text size and thickness to make labels clearer
# (size may need to be altered based on original image size)
pcv.params.text_size = 10
pcv.params.text_thickness = 20

# Inputs:
#   filename = Image file to be read in 
#   mode     = How to read in the image; either 'native' (default), 
#              'rgb', 'gray', 'csv', or 'envi'
img, path, filename = pcv.readimage(filename="./img/arabidopsis_tray.jpg")

a = pcv.rgb2gray_lab(rgb_img=img, channel='a')

a_thresh = pcv.threshold.binary(gray_img=a, threshold=100, object_type='dark')

# ## Remove small background noise
a_fill = pcv.fill(bin_img=a_thresh, size=200)

rois = pcv.roi.auto_grid(mask=a_fill, nrows=4, ncols=5, img=img)


# Not intended for Multi ROIs 
filtered_mask = pcv.roi.filter(mask=a_fill, roi=rois, roi_type='largest')

# Create a labeled mask, this function works very similarly to the roi.filter step above 
labeled_mask, num_plants = pcv.create_labels(mask=a_fill, rois=rois, roi_type="partial")

shape_img = pcv.analyze.size(img=img, labeled_mask=labeled_mask, n_labels=20)

shape_img = pcv.analyze.color(rgb_img=img, labeled_mask=labeled_mask, n_labels=20, colorspaces="HSV")


# ## Save the results
pcv.outputs.save_results(filename=args.result)

```

**Comment by rayn-alex** [comment]
Hey @HaleySchuhl,
thanks for your quick response.

Please excuse, I should have added more context. The problem does not come up in `analyze.size` for me. I'm also not using `roi.filter` with multiple ROIs. I'm already using `create_labels` and that's where I encountered the first error. 

Both errors only occurred when I was upgrading from pcv 4.1 to 4.4. I saw that you changed ROI handling in the releases. 

#### Error in `create_labels`:

The error occurs **only** if `roi_type="largest"` 

This is the code snipped where I use `create_labels` (see line 123 [here](https://github.com/rayngrowingsystems/RVS-A_analysis_scripts/blob/v1.1.0/base_script/base_script.py)). `process_rois()` is a custom function that processes ROIs with different shapes and combines them (see line 276 [here](https://github.com/rayngrowingsystems/RVS-A_analysis_scripts/blob/v1.1.0/base_script/base_script.py)). 

```python

if roi_items:  # only if ROIs are set
   # process ROI items forwarded from the UI
   rois = process_rois(roi_items, img_labelled, roi_debug=roi_overlay)
   # identify objects in the ROIs
   labeled_objects, n_obj = pcv.create_labels(mask=mask, rois=rois, roi_type=roi_mode)
   # ^^ error here

else:  # if no ROIs are set, no ROI filter is applied
   labeled_objects, n_obj = pcv.create_labels(mask=mask, rois=None)

```
The full traceback shows the following:

```
File "/home/alex/GitHub/analysis_ui/Application/Scripts/development/base_script/base_script.py", line 123, in execute
    labeled_objects, n_obj = pcv.create_labels(mask=mask, rois=rois, roi_type=roi_mode)
File "/home/alex/anaconda3/envs/rvs/lib/python3.10/site-packages/plantcv/plantcv/create_labels.py", line 50, in create_labels
    kept_cnt, _, mask = _roi_filter(img=mask, roi=roi,
File "/home/alex/anaconda3/envs/rvs/lib/python3.10/site-packages/plantcv/plantcv/_helpers.py", line 89, in _roi_filter
    index = np.argmax([cv2.contourArea(c) for c in kept_cnt])
File "/home/alex/anaconda3/envs/rvs/lib/python3.10/site-packages/numpy/_core/fromnumeric.py", line 1298, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
File "/home/alex/anaconda3/envs/rvs/lib/python3.10/site-packages/numpy/_core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
File "/home/alex/anaconda3/envs/rvs/lib/python3.10/site-packages/numpy/_core/fromnumeric.py", line 46, in _wrapit
    result = getattr(arr, method)(*args, **kwds)

ValueError: attempt to get argmax of an empty sequence
```

I understand you are looking for the largest contour with `argmax()` but it fails if the contour is empty. This can be solved by checking if kept_cnt is empty. Maybe I'm missing it, but there is no check for an empty ROI -> sub mask in `create_labels` and/or `_roi_filter`.

Can you reproduce this with:
- use `create_labels` on multiple ROIs with one ROI being empty.
- set `roi_type="largest"` 

I submitted a PR that resolves both problems.

**Comment by HaleySchuhl** [comment]
Apologies for missing part of the issue you had described. Yes, I am able to replicate that error when `roi_type="largest"` for `pcv.create_labels`. That's totally my oversight since we don't expect that `largest` option to be used in the majority of cases but we did just recently update a small bug in that functionality which introduced this new one haha; I can review your open PR and get that added in soon. Thanks for this contribution!

**Comment by rayn-alex** [comment]
Haha, I also missed this bug, and personally, I also never used the `largest` option before. We are currently developing an application for analyzing hyper/multispectral images which is purely based on plantCV ([RAYN Vision System Analytics](https://github.com/rayngrowingsystems/RVS_Analytics)). The testers are fantastic at finding tiny bugs like these.
