### ISSUE TITLE
fill broken

### ISSUE THREAD

**Issue by surh** [danforthcenter/plantcv#16]
I tried to run the fill command, copying the example in the docummentation page:

```python
device, binary_img = pcv.median_blur(img, 5, device, debug=True)
device, mask = pcv.median_blur(img, 5, device, debug=True)
device, fill_image = pcv.fill(binary_img, mask, 200, device, debug=True)
```
The median_blur works fine, but I get the following error from the fill 

```
Traceback (most recent call last):
  File "./test_fill.py", line 39, in <module>
    main()
  File "./test_fill.py", line 37, in main
    device, fill_image = pcv.fill(binary_img, mask, 200, device, debug=True)
  File "/home/sur/lib/plantcv/lib/plantcv/fill.py", line 15, in fill
    ix,iy= np.shape(img)
ValueError: too many values to unpack
```
I'm not a python expert, but I understand this means some problem with assigning variable types.
Thanks

**Comment by maliagehan** [comment]
Hi there, I'm guessing that your binary_image has more than one channel? You can check this running print np.shape(binary_img). If it has more than one channel you will see three numbers printed instead of two. If that is the case you need to run a [RGB-Greyscale command such as RGB-HSV](http://plantcv.danforthcenter.org/pages/documentation/function_docs/rgb2hsv.html) to select one of the channels. For more information you can see the [vis pipeline tutorial](http://plantcv.danforthcenter.org/pages/documentation/function_docs/vis_tutorial.html).

**Comment by maliagehan** [comment]
We've added a check to ensure that the inputs are single channel images, please let us know if that solved your issue, cheers.

**Comment by surh** [comment]
Well, I was trying to follow the tutorial first, but got the same error, and that's when I tried to run only the commands from the documentation page. It doesn't work for me with the greyscale. I'm using the magenta-green instead of the blue channel from the tutorial, though I didn't fully understand why you need to run the same command twice and assign it to different variables:

```python
  # Extract and threshold magenta-green. Couldn't do fill
  device, a = pcv.rgb2gray_lab(img, 'a', device, args.debug)
  device, a_thresh = pcv.binary_threshold(a, 110, 255, 'dark', device, args.debug) 
  device, a_cnt = pcv.binary_threshold(a, 110, 255, 'dark', device, args.debug)

  device, a_fill = pcv.fill(a_thresh, a_cnt, 10, device, args.debug)
```
I get the same error on my script
```
[sur@cyanophage today2] $ ~/rhizogenomics/src/trunk/imaging/vis_pipeline.py -i test_images/test1.jpeg -o out -D
Traceback (most recent call last):
  File "/home/sur/rhizogenomics/src/trunk/imaging/vis_pipeline.py", line 58, in <module>
    main()
  File "/home/sur/rhizogenomics/src/trunk/imaging/vis_pipeline.py", line 47, in main
    device, a_fill = pcv.fill(a_thresh, a_cnt, 10, device, args.debug)
  File "/home/sur/lib/plantcv/lib/plantcv/fill.py", line 20, in fill
    contours, hierarchy = cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack
```

**Comment by maliagehan** [comment]
That's frustrating. Is there any way you can attach the image here (I think you can just drag it into the comment box)? So we can help you debug. Also, what were the results of your np.shape(img) command?

**Comment by surh** [comment]
It is not the image because I cannot run the tutorial image either.

I think I figured it out, it seems like the cv2.findContours() function actually returns a three element tuple, and in the assignment there are only two elements. If I add a third element it works.

```python
>>> import sys, traceback
>>> import cv2
>>> import numpy as np
>>> import argparse
>>> import string
>>> import plantcv as pcv
>>> 
>>> # Read and process
... device = 0
>>> img, path, filename = pcv.readimage("test_images/test1.jpeg")
>>> device, a = pcv.rgb2gray_lab(img, 'a', device, True)
>>> device, a_thresh = pcv.binary_threshold(a,110,255,'dark',device,True)
>>> device, a_cnt = pcv.binary_threshold(a,110,255,'dark',device,True)
>>> 
>>> # Checking np_shape, everything looks normal
... np.shape(img)
(700, 700, 3)
>>> np.shape(a)
(700, 700)
>>> np.shape(a_thresh)
(700, 700)
>>> np.shape(a_cnt)
(700, 700)
>>> 
>>> # This line fails
... device, a_fill  = pcv.fill(a_thresh,a_cnt, 10, device, True)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/sur/lib/plantcv/lib/plantcv/fill.py", line 20, in fill
    contours, hierarchy = cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack
>>> 
>>> # Testing fill code
... size = 10
>>> ix, iy = np.shape(a_thresh)
>>> size1 = ix, iy
>>> background = np.zeros(size1, dtype = np.uint8)
>>> 
>>> # This is the function inside pcv.fill that gives the error
... contours, hierarchy = cv2.findContours(a_cnt,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: too many values to unpack
>>> # with a third element in the left had of the assingnment it works
... a_cnt, contours, hierarchy = cv2.findContours(a_cnt,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
>>> 
>>> # ...the rest of the fill() code works
```

Is it possible to incorporate this change to repository?

**Comment by nfahlgren** [comment]
Are you using OpenCV3? In v3 findContours returns three items but in OpenCV2 it only returns contours and hierarchy.

**Comment by surh** [comment]
yeah, I was using the github version. I downgraded to 2.4.8 and it seems like it works now. Thanks!
