### ISSUE TITLE
Clean windows install testing failures

### ISSUE THREAD

**Issue by yonniejon** [danforthcenter/plantcv#161]
Title: Clean install on Windows 10 failure of tests

### Description
Bug: I installed plantcv using the windows install tutorial found [here](http://plantcv.readthedocs.io/en/latest/installation/#windows), followed all of the steps exactly copy and paste from the instructions, and ran the tests.py script and had 9 tests fail, all with the same error. The error was ` WindowsError: [Error 183] Cannot create a file when that file already exists`

### Details

This is the error preview from the tests.py script of one the failed tests error message:

    ___________________ test_plantcv_cluster_contours_splitimg ____________________

        def test_plantcv_cluster_contours_splitimg():
            img1 = cv2.imread(os.path.join(TEST_DATA, TEST_INTPUT_MULTI), -1)
            contours = np.load(os.path.join(TEST_DATA, TEST_INPUT_MULTI_CONTOUR))
            clusters = np.load(os.path.join(TEST_DATA, TEST_INPUT_ClUSTER_CONTOUR))
            roi_contours = contours['arr_0']
            cluster_contours = clusters['arr_0']
            # Test with debug = "print"
            _ = pcv.cluster_contour_splitimg(device=0, img=img1, grouped_contour_indexes=cluster_contours,
                                             contours=roi_contours, outdir=TEST_TMPDIR, file=None, filenames=None,
                                             debug="print")
            for i in range(1, 19):
    >           os.rename(str(i) + "_clusters.png", os.path.join(TEST_TMPDIR, str(i) + "_clusters.png"))
    E           WindowsError: [Error 183] Cannot create a file when that file already exists

    tests\tests.py:343: WindowsError

### Completion Criteria
- [ ] Now I can run tests.py and have all tests pass.

**Comment by nfahlgren** [comment]
@yonniejon thanks for reporting this. I restructured the tests to fix this problem, so if you update to the latest commit it should work on your system now.
