### ISSUE TITLE
Object Size ECDF page in documents has incorrect function name in example. 

### ISSUE THREAD

**Issue by hkmanching** [danforthcenter/plantcv#1620]
**Describe the bug**
The wrong function name is called in example on page (https://plantcv.readthedocs.io/en/stable/visualize_obj_size_ecdf/), so it won't work. 

Uses: fig_ecdf = pcv.visualize.ecdf.obj_size(mask=mask)
Should be: fig_ecdf = pcv.visualize.obj_size_ecdf(mask=mask)

**Comment by HaleySchuhl** [comment]
@hkmanching thank you for bringing this to our attention. I can fix that.

**Comment by HaleySchuhl** [comment]
https://github.com/all-contributors please add @hkmanching for bug

**Comment by HaleySchuhl** [comment]
@all-contributors please add @hkmanching for bug
