### ISSUE TITLE
Bug: Report Size Marker Limits Circle and Ellipse Location

### ISSUE THREAD

**Issue by AntonSax** [danforthcenter/plantcv#167]
### Description
I am trying to use [`report_size_marker_area`](http://plantcv.readthedocs.io/en/latest/report_size_marker/) to define (not detect) a circle in a picture. The function prevents the `x_adj` and `y_adj` parameters from being negative. This works for the when the `shape` parameter is set to `rectangle`, but prevents the `circle` and `ellipse` cases from having a focus at any location above or to the left of the center of the picture.

#### Examples

`device, marker_header,marker_data,images=pcv.report_size_marker_area(img, 'circle', device, debug, marker='define', x_adj=0, y_adj=0, w_adj=-450, h_adj=-450, base='white', objcolor='light', thresh_channel='s', thresh=120, filename=False)`
![269_marker_shape](https://user-images.githubusercontent.com/9059836/27875250-22c27772-6178-11e7-94fb-ba26f5790cdd.png)

`device, marker_header,marker_data,images=pcv.report_size_marker_area(img, 'circle', device, debug, marker='define', x_adj=400, y_adj=0, w_adj=-450, h_adj=-450, base='white', objcolor='light', thresh_channel='s', thresh=120, filename=False)`
![266_marker_shape](https://user-images.githubusercontent.com/9059836/27875254-27038ce0-6178-11e7-8623-37a26c36f99a.png)

`device, marker_header,marker_data,images=pcv.report_size_marker_area(img, 'circle', device, debug, marker='define', x_adj=0, y_adj=400, w_adj=-450, h_adj=-450, base='white', objcolor='light', thresh_channel='s', thresh=120, filename=False)`
![272_marker_shape](https://user-images.githubusercontent.com/9059836/27875257-296a43a2-6178-11e7-940d-a6c0d0df8740.png)

`device, marker_header,marker_data,images=pcv.report_size_marker_area(img, 'circle', device, debug, marker='define', x_adj=0, y_adj=0, w_adj=-300, h_adj=-300, base='white', objcolor='light', thresh_channel='s', thresh=120, filename=False)`
![275_marker_shape](https://user-images.githubusercontent.com/9059836/27875262-2aef6c20-6178-11e7-9b8b-a93eb12eeccb.png)

`device, marker_header,marker_data,images=pcv.report_size_marker_area(img, 'circle', device, debug, marker='define', x_adj=-100, y_adj=0, w_adj=-450, h_adj=-450, base='white', objcolor='light', thresh_channel='s', thresh=120, filename=False)`
RuntimeError: Adjusted ROI position is out of frame, this will cause problems in detecting objects

### Details
This would be helpful to me because I cannot currently define a circle that is not in the fourth quadrant of a picture. 

### Completion Criteria
- [ ] I can set the focus of a circle/ellipse to be in any quadrant.

**Comment by maliagehan** [comment]
@AntonSax your merge fixes this issue, so i'll close it, but feel free to reopen it if you find anything else.
