### ISSUE TITLE
image_analysis scripts have wrong analyze_color() call

### ISSUE THREAD

**Issue by yanliu-chn** [danforthcenter/plantcv#17]
In the current plantcv version, the function analyze_color() is changed to have 11 parameters, while all the scripts in scripts/image_analysis still use 12. Please make it consistent.

**Comment by maliagehan** [comment]
Hi Yanliu, Sorry the documentation isn't up to date (we're working on it). We've pushed a new parallelization script image_analysis.py in dev that is much more efficient. Part of the increase in efficiency was changing some of the parameters for the modules, which isn't reflected yet in the documentation. We're working on updating all of this to make a version 2.0 release, but if you want working modules with the perl script you can check-out the version 1.0 release. If you are interested in 2.0 (sans documentation for now) you can use the new image_analysis.py script and compatible pipeline scripts (compatible pipeline scripts here /scripts/dev/gehan-brachy/).

**Comment by yanliu-chn** [comment]
I see. I will use 1.0 for now. Thanks for the quick reply!

**Comment by maliagehan** [comment]
No problem! Let us know if you run into anything else! cheers!
