### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by bttalisman** [danforthcenter/plantcv#177]
### Description
I'm trying to install on Ubuntu.  I tried both methods, the bash script and the setup.py.  Both appeared to complete without errors.  I'm able to import plantcv, but none of the methods I expect are present in the package.

### Details

I tried to look inside the plantcv package:
>>> import plantcv
>>> print(dir('plantcv'))
['__add__', '__class__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getslice__', '__gt__', '__hash__', '__init__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_formatter_field_name_split', '_formatter_parser', 'capitalize', 'center', 'count', 'decode', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'index', 'isalnum', 'isalpha', 'isdigit', 'islower', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

Not what I expect.  Any help greatly appreciated!  Thanks.

**Comment by bttalisman** [comment]
Hi Noah, thanks for the response.  The OS is Ubuntu 16.04 LTS.  As to the
user privileges, I dont understand the distinction.  My user is a member of
the super user group, but I did not prepend 'sudo' when running the
install.  I'll try that, though.  Thanks!

**Comment by nfahlgren** [comment]
Hi @bttalisman, did that work or still having issues? Thanks!

**Comment by bttalisman** [comment]
Actually I was wrong, I believe I followed the installation instructions correctly, regarding sudo.  So, no, it didn't help.  I've since realized that the package works fine, when imported from code existing in the plantcv folder.  This is workable for now, but not ideal.

Just so you know, the company I work for is building a system that will do cv analysis on greenhouse plants on a large scale.  At this time we're focusing on supporting code, but it seems plantcv may fit in quite nicely, so we appreciate the work you've done.

Thanks again

**Comment by nfahlgren** [comment]
Thanks, that's cool to hear! I will install an Ubuntu 16.04 VM and do an install and see what I can figure out. Your preference is a system-level installation correct? Just asking because there are three general options: system-level package (install with admin privilege, import from anywhere), local-user package (no install required, import from anywhere), or Python virtual environment package (install within virtualenv, import from anywhere after virtualenv activation).

**Comment by bttalisman** [comment]
System or virtualenv is fine.  A college of mine got it going in a docker
container, so I'm under no pressure, though I am still curious why my
install didnt work.

**Comment by nfahlgren** [comment]
@bttalisman I did things a bit different than described in our documentation. Starting with a clean install of Ubuntu Server 16.04.3 I ran:

```
# Install system dependencies
sudo apt-get install git libopencv-dev python-opencv sqlite3 python-setuptools libpython2.7-dev python-pip

# Check the OpenCV installation
python -c 'import cv2; print(cv2.__version__)'
# Returns: 2.4.9.1

# Clone PlantCV
git clone https://github.com/danforthcenter/plantcv.git
cd plantcv

# Install Python dependencies
sudo pip install -r requirements.txt

# Install pytest (needs to be added to requirements)
sudo pip install pytest

# Install PlantCV
sudo python setup.py install

# Test the installation
python setup.py test
```

Hopefully that's helpful but let me know if not!

**Comment by ic** [comment]
Is there any issue with the Bash install script? Testing here too, the module seems functional.

@bttalisman What did you expect when issueing `print(dir('plantcv'))` in your review? After importing the PlantCV module, the API is available. Would you be referring to inspecting the module? Like in:

```
>>> import plantcv
>>> import inspect
>>> inspect.getmembers(plantcv, predicate=inspect.isfunction)
[('acute', <function acute at 0x113510500>), ('acute_vertex', <function acute_vertex at 0x1133e3c08>), ('adaptive_threshold', <function adaptive_threshold at 0x1133e3758>), ('analyze_NIR_intensity', <function analyze_NIR_intensity at 0x1133e3398>), ('analyze_bound', <function analyze_bound at 0x1133e3140>), ('analyze_color', <function analyze_color at 0x1133e3320>), ('analyze_object', <function analyze_object at 0x1133e30c8>), ('apply_mask', <function apply_mask at 0x10ff15578>), ('auto_crop', <function auto_crop at 0x113510398>), ('background_subtraction', <function background_subtraction at 0x113510230>), ('binary_threshold', <function binary_threshold at 0x1133d69b0>),...
```

**Comment by nfahlgren** [comment]
Closing this for now, feel free to reopen if the issue wasn't resolved
