### ISSUE TITLE
Disease feature 

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#194]
Hello guys,

Is there any plan for a disease identification  feature in the future?

Thanks

**Comment by maliagehan** [comment]
I would recommend seeing the multi-class naive bayes function. see tutorial here: http://plantcv.readthedocs.io/en/latest/machine_learning_tutorial/

**Comment by maliagehan** [comment]
I'll close this thread for now, but if you have any questions about multi-class naive bayes feel free to reopen
