### ISSUE TITLE
Real time and crop CV applictions

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#196]
Hello, i would like to know if plantCv suits the real time CV aplications puropose.

Could you tell me some libraries that do it. For example, detecting diseases or unwanted weeds on the field.

Thanks

**Comment by MjBordalo** [comment]
Thanks 4 the reply.

1. Indeed what i mean with real time was about video CV. And also, i agree that the image processing with PlantCV tends to be quite heavy and indeed i dont find it to video CV with plantCV that feasible.  For example, one of my ideias would be to put a camera on a moving robot that would identify weeds and mechanically remove them. rather then just spray around with herbicide.
I already used cron tab and topview camera with raspberry pi to follow crop growth in a small greenhouse + hydroponic application.

2.nice going to check

3.no, but i will

4. that would be nice

thanks 4 your reply once again

**Comment by maliagehan** [comment]
Will close this issue for now but feel free to re-open.
