### ISSUE TITLE
Raspberry Pi PlantCv installation 

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#197]
Hello,
I am once again struggling with the installation of plantCV on the raspberry Pi (the present version: STRETCH ).

I was able to install all the dependencies. sometimes using pip other using apt-get .
Runing the `sudo python setup.py install ` command gives me:
```
...other lines...
copying plantcv.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying plantcv.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying plantcv.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying plantcv.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/plantcv-2.1-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing plantcv-2.1-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/plantcv-2.1-py2.7.egg
Copying plantcv-2.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
plantcv 2.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/plantcv-2.1-py2.7.egg
Processing dependencies for plantcv==2.1
Searching for scikit-image
Reading https://pypi.python.org/simple/scikit-image/
Downloading https://pypi.python.org/packages/83/2a/c5a39c12c196c19a443fa4d17c0768a24231e46ae952930a9d66bad45557/scikit-image-0.13.1.tar.gz#md5=39df2916bd949c2a622f932e0e07cf63
Best match: scikit-image 0.13.1
Processing scikit-image-0.13.1.tar.gz
Writing /tmp/easy_install-79QtNT/scikit-image-0.13.1/setup.cfg
Running scikit-image-0.13.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-79QtNT/scikit-image-0.13.1/egg-dist-tmp-XWXyMP
error: SandboxViolation: mkdir(u'/root/.config', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```
What this really means?

I also thing it should be very important to do have a section on the installation documentation focusing on the raspberry Pi. I believe the Pi has a lot of interesting applications where it could be usefull running th PlantCv software on it.

**Comment by nfahlgren** [comment]
@MjBordalo I was able to get PlantCV installed on JESSIE using the following:

```
# Update package lists
sudo apt-get update
# Upgrade packages
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install git libopencv-dev python-opencv sqlite3 python-setuptools python-dev libblas-dev liblapack-dev gfortran
sudo pip install --upgrade numpy
git clone https://github.com/danforthcenter/plantcv.git
cd plantcv
sudo python setup.py install
```

However, it might be easier to use the newer requirements file to install Python dependencies after installing system package dependencies with apt-get:

```
git clone https://github.com/danforthcenter/plantcv.git
cd plantcv
sudo pip install -r requirements.txt
sudo python setup.py install
```

We are going to start working on updates that will be in PlantCV3 soon. One plan I have is to rework the installation instructions to simplify things. I will make sure that Raspberry Pi is either included explicitly or that the methods are generalized to work well across systems.

**Comment by MjBordalo** [comment]
Thanks @nfahlgren  i was actually able to install plantCV even with those "errors" i came across. 
Maybe if i had done `sudo pip install --upgrade numpy` the installation process would have been more smooth.

The secound approach you posted I tryied. however, with pip some of the packages do not install. Again maybe preceeding with`sudo pip install --upgrade numpy` would help. dunno.

Already thinking about plantCV3? nice. Will it be working with OpenCV3?
Thanks again.
