### ISSUE TITLE
Update Jupyter documentation on conversion between notebooks and scripts

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#199]
### Description

Converting from a Jupyter notebook to a Python script for PlantCV processing purposes requires some reformatting (some of which is unavoidable). One shortcut that could help is to define an options processing class in Jupyter that would prevent the need to do variable renaming in scripts. This is discussed in issue #198.

### Details

The idea would be to format inputs like this in notebooks:

```python
%matplotlib inline  # Added this line
import cv2
import plantcv as pcv
import numpy as np
import argparse

# Instead of the args inputs you could define an args class with the manual inputs
class options:
    def __init__(self):
        self.image = "image.png"
        self.debug = "plot"
        self.writeimg = False
        self.result = "test_results.txt"
        self.coresult = "test_coresults.txt"

# Parse options
args = options()

# The code below here is from the "main" function in the script
device = 0

# Read image (note that args.image and args.debut are replaced with image and debug)
img, path, filename = pcv.readimage(filename=args.image, debug=args.debug)
```

### Completion Criteria

- [ ] Update documentation
- [ ] Test mkdocs build
- [ ] Pull request and merge

**Comment by HaleySchuhl** [comment]
Documentation for conversion to Jupyter notebooks to Python scripts has been updated to reflect the current version of PlantCV in pull request #388  . The documentation now contains slightly more detail and links to the various tutorial pages which contain full, correctly formatted scripts at the bottom as further examples.
