### ISSUE TITLE
plantcv-pipeline.py

### ISSUE THREAD

**Issue by IshfaqArif** [danforthcenter/plantcv#204]
hello sir I am facing a problem while executing the code 
 program stops here 

    args = parser.parse_args()

error :

usage: plantcv-pipeline.py [-h] -d DIR [-a ADAPTOR] -p PIPELINE -s DB
                           [-i OUTDIR] [-T CPU] [-c] [-D DATES] [-t TYPE]
                           [-l DELIMITER] [-f META] [-M MATCH] [-C COPROCESS]
                           [-w] [-o OTHER_ARGS]
plantcv-pipeline.py: error: argument -d/--dir is required

**Comment by nfahlgren** [comment]
Hi @IshfaqArif, if you run `plantcv-pipeline.py` without any arguments it will print out the help text that you are seeing. If you run `plantcv-pipeline.py -h` it will print out more detailed instructions.

**Comment by IshfaqArif** [comment]
well Sir @nfahlgren   its really helpful for me.....
now new list is generated after using this instruction  plantcv-pipeline.py -h
list:

usage: plantcv-pipeline.py [-h] -d DIR [-a ADAPTOR] -p PIPELINE -s DB
                           [-i OUTDIR] [-T CPU] [-c] [-D DATES] [-t TYPE]
                           [-l DELIMITER] [-f META] [-M MATCH] [-C COPROCESS]
                           [-w] [-o OTHER_ARGS]

Parallel imaging processing with PlantCV.

optional arguments:
  -h, --help            show this help message and exit
  -d DIR, --dir DIR     Input directory containing images or snapshots.
                        (default: None)
  -a ADAPTOR, --adaptor ADAPTOR
                        Image metadata reader adaptor. PhenoFront metadata is
                        stored in a CSV file and the image file name. For the
                        filename option, all metadata is stored in the image
                        file name. Current adaptors: phenofront, filename
                        (default: phenofront)
  -p PIPELINE, --pipeline PIPELINE
                        Pipeline script file. (default: None)
  -s DB, --db DB        SQLite database file name. (default: None)
  -i OUTDIR, --outdir OUTDIR
                        Output directory for images. Not required by all
                        pipelines. (default: .)
  -T CPU, --cpu CPU     Number of CPU to use. (default: 1)
  -c, --create          will overwrite an existing databaseWarning: activating
                        this option will delete an existing database!
                        (default: False)
  -D DATES, --dates DATES
                        Date range. Format: YYYY-MM-DD-hh-mm-ss_YYYY-MM-DD-hh-
                        mm-ss. If the second date is excluded then the current
                        date is assumed. (default: None)
  -t TYPE, --type TYPE  Image format type (extension). (default: png)
  -l DELIMITER, --delimiter DELIMITER
                        Image file name metadata delimiter character.
                        (default: _)
  -f META, --meta META  Image file name metadata format. List valid metadata
                        fields separated by the delimiter (-l/--delimiter).
                        Valid metadata fields are: timestamp, frame, lifter,
                        gain, measurementlabel, cartag, id, exposure, zoom,
                        plantbarcode, camera, treatment, imgtype, other
                        (default: imgtype_camera_frame_zoom_id)
  -M MATCH, --match MATCH
                        Restrict analysis to images with metadata matching
                        input criteria. Input a metadata:value comma-separated
                        list. This is an exact match search. E.g.
                        imgtype:VIS,camera:SV,zoom:z500 (default: None)
  -C COPROCESS, --coprocess COPROCESS
                        Coprocess the specified imgtype with the imgtype
                        specified in --match (e.g. coprocess NIR images with
                        VIS). (default: None)
  -w, --writeimg        Include analysis images in output. (default: False)
  -o OTHER_ARGS, --other_args OTHER_ARGS
                        Other arguments to pass to the pipeline script.
                        (default: None)
The thread 'MainThread' (0x2e6c) has exited with code 0 (0x0).
The program '[7628] python.exe' has exited with code 0 (0x0).

**Comment by maliagehan** [comment]
Hi @IshfaqArif you are again getting the help menu. The parallelization script won't run unless you include the settings. Please see http://plantcv.readthedocs.io/en/latest/pipeline_parallel/ for more information. Cheers.
