### ISSUE TITLE
how to apply plantcv train.py for my own data of images?

### ISSUE THREAD

**Issue by hajar-65** [danforthcenter/plantcv#206]

**Comment by nfahlgren** [comment]
Hi @hajar-65, the documentation for the `plantcv-train.py` program is here: http://plantcv.readthedocs.io/en/latest/machine_learning_tutorial/

**Comment by hajar-65** [comment]
Hi @nfahlgren m thank you for the link, 
but still I don't know how I can use plantcv-train.py!!
help please?!

**Comment by nfahlgren** [comment]
Happy to help but I am not sure where you are stuck. If you could post what you are trying to do and what parts are not working it would point me in the right direction. Thanks!

**Comment by hajar-65** [comment]
Actually I have images on palm leaves with infected spots that I want to
detect  features  of interest on my image data, for that I want to use
naive bayse classifier on plantcv.

I hope now is clear for you.
Kind regards

**Comment by nfahlgren** [comment]
Okay, sounds great. You will want to use the `naive_bayes_multiclass` subcommand that is described here: http://plantcv.readthedocs.io/en/latest/machine_learning_tutorial/#naive-bayes-multiclass. That section of the documentation walks through how to collect the training data and an example command. It's mostly the same information, but I made a few slides that walk through the process (with notes) also: https://docs.google.com/presentation/d/1A9Sv4gQYyS6QKBxRGVfo_7fUAyDtBj4a5-Xu9J5BPsA/edit?usp=sharing. Note that for collecting the training data itself, prior to running the `plantcv-train.py` script, we recommend using the ImageJ Pixel Inspection Tool.

**Comment by hajar-65** [comment]
That is so helpful, thank you @nfahlgren

**Comment by nfahlgren** [comment]
Closing for now, but feel free to reopen as needed.
