### ISSUE TITLE
OpenCV 3.x

### ISSUE THREAD

**Issue by yanliu-chn** [danforthcenter/plantcv#21]
Hi,

Do you have a plan to upgrade plantcv to support opencv 3.x which has quite a few API changes? We tried to deploy plantcv on some HPC clusters which have GPU/CUDA 7.0 deployed. But opencv 2.x is too old for the cuda api version supported.

Or opencv 3.x is already supported by a branch?

Thanks,
Yan

**Comment by nfahlgren** [comment]
We just got a one-year grant to update PlantCV to OpenCV3/Python3. I don't think it will be too difficult but we haven't dug into it yet.

**Comment by yanliu-chn** [comment]
I see. We have opencv 3.0 installed on ROGER. once you get access to the cluster, please feel free to try it out.
