### ISSUE TITLE
Analysising BIL files from multispectral scanner

### ISSUE THREAD

**Issue by emmasmithscience** [danforthcenter/plantcv#212]
Our multi spectral scanner produces three BIL files for each tray of Arabidopsis plants:
1. The image of the plants
2. White calibration
3. Dark calibration

I have tried the VIS pipeline tutorial and found that that PlantCV "failed to open filename.bil"

First, is it possible to analysis BIL files?

If this is possible, I want to create a mask for the plants and analysis the wavelengths present as a whole for a lawn of Arabidopsis seedlings, per plant and if possible per leaf. 

If this is possible then there are a lot of people part of my lab group who would be interested in using PlantCV in the future.

Thanks,
Emma

**Comment by nfahlgren** [comment]
After discussion with @emmasmithscience we are going to test tools @maliagehan is developing for issue #203

**Comment by nfahlgren** [comment]
@emmasmithscience I'm hopeful because it looks to me like the Python package @maliagehan is using can read BIL files: http://www.spectralpython.net/fileio.html
