### ISSUE TITLE
Add 'conda env create' to windows install instructions

### ISSUE THREAD

**Issue by krismatson** [danforthcenter/plantcv#213]
## Description
Recommend adding conda env create to windows installation instructions, after "Install prerequisite Python packages ..." and preceeding installation with ```git clone <repo>```. 

```
conda env create -f requirements.txt -n plantcv
```

### Details
This command should obviate the pip install list:
```
pip install argparse
pip install matplotlib
pip install numpy
pip install pandas
pip install pytest
pip install python-dateutil
pip install scikit-image
pip install scipy
```

And should ensure no collisions with opencv versions. 

Here is order of the plantcv installation commands I used on Windows 7 Enterprise:
```
> git clone https://github.com/danforthcenter/plantcv.git
> cd plantcv
> conda env create -f requirements.txt -n plantcv
> activate plantcv
> python setup.py install
> conda install -c menpo opencv=2.4.11
> conda install -c blaze sqlite3
> python -c "import plantcv"
```

This procedure successfully installed plantcv on opencv2.

**Comment by krismatson** [comment]
To ensure env plantcv is accessible in jupyter notebooks:
```
> conda install ipykernel
```

**Comment by maliagehan** [comment]
Working on all new installation instructions that will include these fixes.

**Comment by nfahlgren** [comment]
@krismatson I have a pull request that updates the installation instructions based on your feedback. The updated page can be previewed at https://github.com/danforthcenter/plantcv/blob/0f7735c30f1f5b51660de36cabcf3cae29cd9cde/docs/installation.md. Thanks for your help! Let us know if you have other suggestions.

**Comment by maliagehan** [comment]
@nfahlgren's new installation instructions have solved this issue, closing, but feel free to reopen if there are any further issues.
