### ISSUE TITLE
MacOS: Anaconda3.6, openCV 3.3.1 successful install!!!

### ISSUE THREAD

**Issue by austinmeier** [danforthcenter/plantcv#214]
Here is how I successfully installed plantCV using Anaconda 3.6:

Install most recent version of Anaconda (3.6 at the time Feb 2018) - done using the Anaconda wizard.
Use conda to install OpenCV 3 (3.3.1)

`conda install -c menpo opencv`

Note: I did not specify the version of opencv to use, and conda chose 3.3.1 on it's own.

Clone the plantCV repo:

`git clone https://github.com/danforthcenter/plantcv.git`

`cd plantcv`

use your Anaconda python3 to run the install.py script

`~/path/to/anaconda3/bin/python setup.py install`

Make sure it works:

`/path/to/anaconda3/bin/python -c 'import plantcv'`

**Comment by austinmeier** [comment]
Update:  Attempted to repeat this process for my iMac - ran into this error while attempting `conda install -c menpo opencv` immediately:


```
UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

This was solved by upgrading conda from version-  4.3.25   to version - 4.4.10

`conda update conda`  

did the trick for me!  All other steps above work as advertised.

**Comment by maliagehan** [comment]
Working on all new installation instructions that will include these fixes. Thanks @austinmeier

**Comment by nfahlgren** [comment]
@austinmeier I have a pull request that updates the installation instructions based on your feedback. The updated page can be previewed at https://github.com/danforthcenter/plantcv/blob/0f7735c30f1f5b51660de36cabcf3cae29cd9cde/docs/installation.md. Thanks for your help! Let us know if you have other suggestions.

**Comment by maliagehan** [comment]
@nfahlgren's new installation instructions have solved this issue, closing, but feel free to reopen if there are any further issues.
