### ISSUE TITLE
homebrew/science has deprecated

### ISSUE THREAD

**Issue by tweeraratne** [danforthcenter/plantcv#215]
**Bug:** To install opencv, I ran `tap homebrew/science`, and it showed that "homebrew/science was deprecated. This tap is now empty as all its formulae were migrated."

A solution to this bug will help python 3.6 users to install opencv and then plantcv

python 3.6, opencv, plantcv, homebrew, homebrew/science

**Comment by maliagehan** [comment]
Working on all new installation instructions that will include these fixes.

**Comment by nfahlgren** [comment]
@tweeraratne we are in the process of updating our installation guide to discontinue the use of Homebrew on OSX/macOS. The updated page can be previewed at https://github.com/danforthcenter/plantcv/blob/0f7735c30f1f5b51660de36cabcf3cae29cd9cde/docs/installation.md. Thanks for your help! Let us know if you have other suggestions.

**Comment by maliagehan** [comment]
@nfahlgren's new installation instructions have solved this issue, closing, but feel free to reopen if there are any further issues.
