### ISSUE TITLE
Error installing on Mac OS HighSierra

### ISSUE THREAD

**Issue by chiragh241** [danforthcenter/plantcv#216]
After running: `python setup.py install`

It always stops here: 

Installed /Library/Python/2.7/site-packages/plantcv-2.1-py2.7.egg
Processing dependencies for plantcv==2.1
Searching for scikit-image
Reading https://pypi.python.org/simple/scikit-image/
Best match: scikit-image 0.13.1
Downloading https://pypi.python.org/packages/83/2a/c5a39c12c196c19a443fa4d17c0768a24231e46ae952930a9d66bad45557/scikit-image-0.13.1.tar.gz#md5=39df2916bd949c2a622f932e0e07cf63
Processing scikit-image-0.13.1.tar.gz
Writing /tmp/easy_install-2fiQu0/scikit-image-0.13.1/setup.cfg
Running scikit-image-0.13.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2fiQu0/scikit-image-0.13.1/egg-dist-tmp-DOlFfD
Killed: 9

Any idea how to get around this?

**Comment by maliagehan** [comment]
Working on all new installation instructions that will include these fixes.

**Comment by nfahlgren** [comment]
@chiragh241 we are in the process of updating our installation guide. The updated page can be previewed at https://github.com/danforthcenter/plantcv/blob/0f7735c30f1f5b51660de36cabcf3cae29cd9cde/docs/installation.md. The Anaconda-based method worked for me on macOS High Sierra. If this doesn't work for you though please let us know.

**Comment by maliagehan** [comment]
@nfahlgren's new installation instructions have solved this issue, closing, but feel free to reopen if there are any further issues.
