### ISSUE TITLE
Arent cv2 and openCV the same thing?

### ISSUE THREAD

**Issue by Mahi-Mai** [danforthcenter/plantcv#237]
### Details

Question:  I'm trying to get plantCV up and running on my MacBook.  Going over the details for installation, dependencies mention both cv2 and openCV.  Are these two the same?  I think I figured out that this package isn't supposed to play nice with python3, so I'm running a python2 notebook instead on a cloud platform.

But now I just reread part of the installation guide and it says it should work find with python3.

I don't know anymore.  I'm so confused.  I install the latest versions of opencv and plant cv, but when I launch a notebook and try to import cv2, it fails.

I just want it to work.  It's driving me a little mad.

### Completion Criteria

I get it to WORK.

**Comment by nfahlgren** [comment]
@Mahi-Mai you are correct, cv2 is the name of the Python package built by/provided by the OpenCV package.

For versions, I recommend everyone use Python 3 unless you have a specific reason to use Python 2.

I'm assuming you used the Anaconda installation method, if so did you install the `nb_conda` package? It's required to use Jupyter notebooks in conjunction with Anaconda environments. If you installed it in the plantcv environment you need to run `source activate plantcv` before you run `jupyter notebook`.

**Comment by Mahi-Mai** [comment]
Thanks so much for your help!  I managed to get it working with the proper sys.path.append('dir') lines.

I've tried installing nb_conda in the past, but each time I do I get an HTTP error.  Things seem to be running in Jupyter Lab okay, but will there be things under the hood that won't work without nb_conda?

The big issue I've run into so far- running a slightly modified version of the VIS pipeline given on the main site- is objects in the image not being identified. It highlights the entire image instead of the disparate parts, so when I try to use a circular ROI it grab's nothing.  Here's the code used:
```
# Identify objects
device, id_objects,obj_hierarchy = pcv.find_objects(masked2, ab_fill, device, debug)
```
  I've attached a screen below:

![badid](https://user-images.githubusercontent.com/17129394/42170611-a5d306b4-7ddc-11e8-972b-23d3f3767b88.png)

**Comment by nfahlgren** [comment]
Great, glad it's working! Everything should be functional without `nb_conda`, the only extra thing that `nb_conda` provides is awareness of conda environments (if you are using them).

Based on what you posted I think the problem is that the image `ab_fill` is a color image and not a binary image, but I could be wrong.

**Comment by Mahi-Mai** [comment]
If it helps, here's what comes before those steps:

```
# Convert RGB to LAB and extract the Green-Magenta and Blue-Yellow channels
device, masked_a = pcv.rgb2gray_lab(masked, 'a', device, debug)
device, masked_b = pcv.rgb2gray_lab(masked, 'b', device, debug)

# Threshold the green-magenta and blue images
device, maskeda_thresh = pcv.binary_threshold(masked_a, 120, 255, 'dark', device, debug)
device, maskeda_thresh1 = pcv.binary_threshold(masked_a, 120, 255, 'light', device, debug)
device, maskedb_thresh = pcv.binary_threshold(masked_b, 150, 255, 'light', device, debug)

# Join the thresholded saturation and blue-yellow images (OR)
device, ab1 = pcv.logical_or(maskeda_thresh, maskedb_thresh, device, debug)
device, ab = pcv.logical_or(maskeda_thresh1, ab1, device, debug)
device, ab_cnt = pcv.logical_or(maskeda_thresh1, ab1, device, debug)

# Fill small objects
device, ab_fill = pcv.fill(ab, ab_cnt, 200, device, debug)

# Apply mask (for vis images, mask_color=white)
device, masked2 = pcv.apply_mask(masked, ab_fill, 'white', device, debug)
```
This results in the following outputs:
![grab1](https://user-images.githubusercontent.com/17129394/42175054-e37ed0e4-7de9-11e8-830f-8b4466104e92.png) <br>
![grab2](https://user-images.githubusercontent.com/17129394/42175076-f2b37506-7de9-11e8-8c79-2829240a7918.png)<br>
![grab3](https://user-images.githubusercontent.com/17129394/42175080-f7952556-7de9-11e8-9083-bece226802bc.png)

I think those last 3 must be where the problem is...

**Comment by Mahi-Mai** [comment]
Oh, it didn't upload my image??
Outputs one:
![grab1](https://user-images.githubusercontent.com/17129394/42175117-19c98a2c-7dea-11e8-9485-442c2083d6fe.png)

**Comment by nfahlgren** [comment]
@Mahi-Mai okay, got it. I think the logical_or functions are returning an empty binary image, so find_objects then has nothing to find. It looks to me like for your images a shorter workflow would work:

```python
# Convert RGB to LAB and extract the Green-Magenta
device, masked_a = pcv.rgb2gray_lab(masked, 'a', device, debug)

# Threshold the green-magenta
device, maskeda_thresh = pcv.binary_threshold(masked_a, 120, 255, 'dark', device, debug)

# Fill small objects
device, a_fill = pcv.fill(masked, np.copy(maskeda_thresh), 200, device, debug)

# Apply mask (for vis images, mask_color=white)
device, masked2 = pcv.apply_mask(masked, a_fill, 'white', device, debug)
```

**Comment by Mahi-Mai** [comment]
Unfortunately, this gives me an error.  

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-1155f6201232> in <module>()
      1 # Fill small objects
----> 2 device, a_fill = pcv.fill(masked, np.copy(maskeda_thresh), 200, device, debug)
      3 
      4 # Apply mask (for vis images, mask_color=white)
      5 device, masked2 = pcv.apply_mask(masked, a_fill, 'white', device, debug)

~/plantcv/plantcv/plantcv/fill.py in fill(img, mask, size, device, debug)
     33     device += 1
     34     if len(np.shape(img)) >= 3:
---> 35         fatal_error("Image is not binary")
     36     else:
     37         ix, iy = np.shape(img)

~/plantcv/plantcv/plantcv/fatal_error.py in fatal_error(error)
     12     """
     13 
---> 14     raise RuntimeError(error)

RuntimeError: Image is not binary
```

If I change the argument in pcv.fill to 'masked_a' instead of 'masked,' it runs, but I get another "all white" output again.

![grab4](https://user-images.githubusercontent.com/17129394/42176912-380119be-7df0-11e8-984d-73d7d8d21547.png)

**Comment by nfahlgren** [comment]
Oops, sorry, the first argument should also be a binary mask. I would use this instead:

```
# Fill small objects
device, a_fill = pcv.fill(np.copy(maskeda_thresh), np.copy(maskeda_thresh), 200, device, debug)
```

We will change this function at some point to just take in the mask once. For now it has to accept it twice because both get modified for different reasons, which is also why I use np.copy so that it doesn't modify the inputs.

**Comment by Mahi-Mai** [comment]
It's working!! Thank you so much!  This tool is going to be SO helpful.

**Comment by nfahlgren** [comment]
Great!

**Comment by maliagehan** [comment]
Sounds like this issue is resolved so I will close but feel free to reopen.
