### ISSUE TITLE
Acute function- whole plant morphological landmark detection

### ISSUE THREAD

**Issue by jgerardhodge** [danforthcenter/plantcv#24]
A method that uses localized contour shape for segmenting out regions of high contrast within contours of plant masks.  This method has shown some initial success with _Setaria viridis_ for tracking discrete regions within plants during tiller exertion and with further development it may become a more flexible tool that can be broadly applied to other systems and distinct organ types (grass inflorescences, complex dicot leaves, etc...).

**Comment by jshoyer** [comment]
Hi John,   did your pull request #26 solve this to your satisfaction or are you still actively working on it?
