### ISSUE TITLE
Test Problem: Python & MatPlot compatibility

### ISSUE THREAD

**Issue by asumann** [danforthcenter/plantcv#243]
**Description**

I am using Anaconda on MacOSx and have two different environments with Python2.7 and Python3.7. Everything works well except I get warning for matplotlib for Py2.7. It looks matplotlib is compatible with Py3.7. However I don't want to go with Py3.7 since it hasn't been tested for PlantCV,yet(I have seen that note in plantcv documentation). I am also new to this area and that is my hesitation to work with untested version. 

Should I try to fix the problem with matplotlib or go with using Py3.7? What is a possible solution in matplotlib case? I hope I understood the problem correctly.

Thanks,
Asuman

**Details**

Matplotlib Warning using Py2.7:

> tests/tests.py::test_plantcv_fluor_fvfm
>   /.local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
>     warnings.warn(message, mplDeprecation, stacklevel=1)
> 
> tests/tests.py::test_plantcv_triangle_threshold
>   /.local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
>     warnings.warn(message, mplDeprecation, stacklevel=1)

**Comment by nfahlgren** [comment]
Hi @asumann, you are right, we have not tested with Python 3.7 yet but we could enable that test in our automated testing suite and can update this issue with the result. That being said, you can ignore those matplotlib warnings in 2.7, they don't affect functionality, they are just soft warnings that a method that is going to be removed from matplotlib in the future is being used presently.

**Comment by asumann** [comment]
Thank you @nfahlgren!! I’ll keep working with2.7 for now. It would be great if you update the issue after the test.

**Comment by nfahlgren** [comment]
Hi @asumann, sorry this took awhile but our automatic testing now includes Python 3.7 in addition to 3.6 and 2.7, so I can safely say that 3.7 is safe to use.
