### ISSUE TITLE
UnboundLocalError: Local variable 'nirpath' referenced before assignment

### ISSUE THREAD

**Issue by hasifzulkifli95** [danforthcenter/plantcv#250]
Hello all,

Ive been learning the code provided by plantcv and I got stucked with the nir section. Is there any reason why? 

`device,nirpath = pcv.get_nir(path,filename,device,debug)`

and the error is..

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-53-7f9bbbcb7d9a> in <module>()
      1 print(path)
      2 print(filename)
----> 3 device,nirpath = pcv.get_nir(path,filename,device,debug)

~\AppData\Local\Continuum\anaconda3\envs\plantcv\lib\site-packages\plantcv-3.0.dev1+14.g26b15ea-py3.6.egg\plantcv\plantcv\get_nir.py in get_nir(path, filename, device, debug)
     55                     nirpath = os.path.join(str(path), str(n))
     56 
---> 57     return device, nirpath

UnboundLocalError: local variable 'nirpath' referenced before assignment`

If someone has a solution for this, could you elaborate more on how and what to change in the code as I don't really familiar with the python jargon.

Thanks!

**Comment by maliagehan** [comment]
Hi @hasifzulkifli95, it looks as though you are attempting to use the VIS/NIR dual pipeline tutorial. This tutorial makes the assumption that the VIS and NIR images are in the same folder and are named the same way (e.g. VIS_SV_90_z2500_h2_g0_e100_4323.png and NIR_SV_90_z2500_h2_g0_e10000_4328.png ) see: https://plantcv.readthedocs.io/en/latest/get_nir/ for more information. If you only have NIR images then I would suggest looking at the NIR only pipeline. Let me know if that answers your problem, or if you are running into some other issue. Cheers, Malia
