### ISSUE TITLE
VIS Image Pipeline - output image writing issue

### ISSUE THREAD

**Issue by ferrucciosarra** [danforthcenter/plantcv#251]
Hi,
I am new to Python and to plantcv. Hope to get some help here!

### Description

Trying to use -w flag. 

When I execute the pipeline.py script by typing: 
python pipeline.py -i VR000.png -o /~/Downloads/plantcv -r results.txt -w -D 'print'

the following error is displayed: 
pipeline.py: error: argument -w/--writeimg: expected one argument

Wtihout -w flag the code runs pretty smooth.

As an example I used a pipeline.py file including VIS Pipeline Tutorial code:   

#!/usr/bin/python
import sys, traceback
import cv2
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv

def options():
    parser = argparse.ArgumentParser(description="Imaging processing with opencv")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-r","--result", help="result file.", required= False )
    parser.add_argument("-w","--writeimg", help="write out images.", default=False)
    parser.add_argument("-D", "--debug", help="Turn on debug, prints intermediate images.", default=None)
    args = parser.parse_args()
    return args

def main():
    # Get options
    args = options()

    # Read image
    img, path, filename = pcv.readimage(args.image, 'print')
    
    # Pipeline step
    device = 0
 
    debug=args.debug 

    # Convert RGB to HSV and extract the Saturation channel
    device, s = pcv.rgb2gray_hsv(img, 's', device, debug)

    # Threshold the Saturation image
    device, s_thresh = pcv.binary_threshold(s, 85, 255, 'light', device, debug)

if __name__ == "__main__":
    # execute only if run as a script
    main()

**Comment by nfahlgren** [comment]
Hi @ferrucciosarra, to fix the issue the argument line for -w would look like this:

`parser.add_argument("-w","--writeimg", help="write out images.", default=False, action="store_true")`

Without the `action="store_true"` argparse thinks there should be some input value after the -w option.

**Comment by ferrucciosarra** [comment]
Thank you very much Noah,
now the script works fine ...but one thing:
both the new output file and the intermediate images (the -D flag is on) have been placed in the Downloads/plantcv folder and not in Downloads/plantcv/output_images as I expected.
Can you figure out why?

**Comment by nfahlgren** [comment]
Currently the outdir option only controls where the results of the analyze functions are stored. Intermediate images created by the debug option are always placed in the current working directory. However, the next release which will be done in the next few days (progress here: https://github.com/danforthcenter/plantcv/pull/249) will add the ability to specify where the debug images are stored.

This features is documented here (https://plantcv.readthedocs.io/en/latest/params/) but will only work on most functions after we merge Pull Request #249 with the master branch. We are trying to wrap up this and other changes before September 4 when we are having a PlantCV WebEx session to discuss these changes and future directions with the community: https://twitter.com/plantcv/status/1034517028395274240. You are welcome to call in if you would like! If so just DM me on Twitter or send me an email at nfahlgren@danforthcenter.org and I can send you the WebEx call-in details.

**Comment by maliagehan** [comment]
Hi @ferrucciosarra now that PlantCV v3.0.2 dev is available, you can direct where the output images go if you update. I'm going to close your issue for now, but if you continue to have issues with debug output directory feel free to open this issue up again.
