### ISSUE TITLE
Update random.random_integers to random.randint 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#258]
### Description

line 55
currently: fg = fg[np.random.random_integers(0, len(fg) - 1, int(len(fg) / 10))]
updated should be: fg = fg[np.random.randint(0, len(fg) - 1, size = int(len(fg) / 10))]

same goes for line 57

### Completion Criteria
Update function and rerun test. Not a bug yet but might become one. Purpose is to get rid of a depreciation error.

**Comment by nfahlgren** [comment]
Fixed by pull request #270
