### ISSUE TITLE
pcv.cluster_contour_splitimg

### ISSUE THREAD

**Issue by clairemcwhite** [danforthcenter/plantcv#266]

**Comment by nfahlgren** [comment]
Hi @clairemcwhite, were you having issues with the `pcv.cluster_contour_splitimg` function? Happy to help!

**Comment by clairemcwhite** [comment]
Oh, I hadn't mean to submit this yet.  

Anyway, I've been using pcv.cluster_contours then pcv.cluster_contour_splitimg to split up a pot of plants to individuals and save the images, then reading them back in to get size measurement of each plant. 

I was wondering if there's a similar functionality to pcv.cluster_contour_splitimg that would return the clustered images in a list instead of just saving them? pcv.cluster_contour_splitimg returns the saved filepaths, not the images.

**Comment by nfahlgren** [comment]
Good question! We don't have a function that returns a list of the images per se, but you can work with the individual plants after clustering without saving the images. I have done this by taking the output clustered contours from pcv.cluster_contours, per plant, and create a per plant mask. I wrote a Jupyter notebook example to demonstrate how I did this: https://github.com/nfahlgren/shared_jupyter_notebooks/blob/master/arabidopsis-multiplant.ipynb

**Comment by clairemcwhite** [comment]
Thanks so much! This cell is exactly what I was looking for. 

```
# Loop over clusters
# Each cluster is a list of contour indices
for cluster in clusters:
    # Skip if the cluster is empty
    if len(cluster) > 0:
        # Initialize an empty mask image
        mask = np.zeros(shape=np.shape(img)[:2], dtype=np.uint8)
        # Loop over each cluster index
        for i in cluster:
            # Draw contour i on the mask
            cv2.drawContours(mask, contours, i, (255), -1, hierarchy=hierarchy)
        # Plot each plant mask
        # Other analysis code could go here
        pcv.plot_image(mask)

```
