### ISSUE TITLE
access files from database

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#283]
Hi - I was wondering if you always access your files directly from the harddrive or also through a database. I believe you have a LemnaTec system too, so I'm asking if you already have snippets that provide access to a lemna db. Ours is currently setup as a postgresql.
I've accessed our db through R so presumably I could track down some basic db access functions for python but I thought I'd ask here first.
Thanks
Dominik

**Comment by nfahlgren** [comment]
Hi @dschneiderch, I wrote a Python script that fetches data from our LemnaTec postgresql database server and converts them to PNG. It also grabs the metadata and saves it to a CSV file. The code is here: https://github.com/danforthcenter/pheno-data-service

Note: the output directory structure mimics an older system we used. At some point we could arrange things differently, there's just inertia keeping it the way it is.

**Comment by dschneiderch** [comment]
Awesome, Thanks!
