### ISSUE TITLE
Possible changes to sobel and scharr filter functions 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#295]
### Description

* Would using a scikit backend improve the sobel function?
* Could sobel_filter and scharr_filter be combined into one function where method is a new parameter for users to choose between? 

Please use boxes like:

For a discussion:
- [ ] Discuss and develop plan

For a new feature (if combined):
- [ ] Create algorithm/method
- [ ] Update test
- [ ] Write documentation
- [ ] Add to the package (pull request)
- [ ] Edit updates doc 
- [ ] Remove old references if changes are made 
--->

**Comment by HaleySchuhl** [comment]
Functions could be easily combined with an `if` statement. The only difference in the functions are the following lines: 
`sr_img = cv2.Scharr(src=gray_img, ddepth=-1, dx=dx, dy=dy, scale=scale)`
`sb_img = cv2.Sobel(src=gray_img, ddepth=-1, dx=dx, dy=dy, ksize=k)` 

Might be more confusing in docs to tell endusers that the last parameter is scale if they choose scharr and kernel size if they choose sobel? There also seems to be different limitations on `dx` and `dy` depending on method used. For example, in scharr `dx >= 0 && dy >= 0 && dx+dy == 1 in function getScharrKernels` but sobel requires `ksize > order` where order is the largest derivative. It is probably simpler to keep the two functions separate and add a note on each doc to warn of parameter limitations.

**Comment by nfahlgren** [comment]
Good call on keeping them separate then!
