### ISSUE TITLE
Add canny edge detection 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#296]
Title: Add canny edge detection 

Labels: Proposed new function 

### Description

Add canny edge detection (OpenCV or scikit-image?) to PlantCV package.

### Details

Canny edge detection is used within the color card auto-detection function but would be useful for endusers as another method to threshold their images. 

### Completion Criteria

How will we know when this is done?

For a new feature:
- [ ] Choose backend method
- [ ] Create algorithm/method
- [ ] Write test
- [ ] Write documentation
- [ ] Add to the package (pull request)

**Comment by HaleySchuhl** [comment]
Using skimage for the backend would have less required parameters compared to cv2.Canny while still having basically all the same optional parameters. cv2.Canny works on color images but otherwise they are very similar in results. Since skimage would be easier to use, and is still as customizable as cv2, it seems to be a slightly better backend method. 

Gray image:
![image](https://user-images.githubusercontent.com/44006936/51620091-4848d980-1ef7-11e9-8e17-1c9702eb4445.png)

skimage (`feature.canny(gray_img, sigma=2)`):
![image](https://user-images.githubusercontent.com/44006936/51620137-5b5ba980-1ef7-11e9-8880-fe56b09c4d75.png)

cv2 (`cv2.Canny(img, 140, 200)`):
![image](https://user-images.githubusercontent.com/44006936/51620299-ac6b9d80-1ef7-11e9-88cc-1d87e37f6080.png)

**Comment by nfahlgren** [comment]
The skimage option sounds good to me!
