### ISSUE TITLE
Restructuring how results/measurements are captured and stored

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#304]
People should feel free to propose additions/revisions to the ideas below.

# The Problem
Output data from PlantCV is generated by several functions including: 

* `plantcv.analyze_object`: shape data
* `plantcv.analyze_bound_horizontal`: height and vertical distribution data
* `plantcv.analyze_bound_vertical`: left/right distribution data
* `plantcv.analyze_color`: color/color properties distribution data
* `plantcv.analyze_nir_intensity`: NIR distribution data
* `plantcv.fluor_fvfm`: PSII Fv/Fm distribution data
* `plantcv.report_size_marker_area`: Reference size marker area data
* `plantcv.watershed_segmentation`: Segmented object count
* Landmark data from several functions
* Others?

We have a coded mechanism for capturing these data during parallel analysis, but it requires the user to format the output using a code block like this:

```python
result=open(args.result,"a")
result.write('\t'.join(map(str, shape_header)) + "\n")
result.write('\t'.join(map(str, shape_data)) + "\n)
for row in shape_img:  
    result.write('\t'.join(map(str, row)) + "\n")
    result.write('\t'.join(map(str, color_header)) + "\n")
    result.write('\t'.join(map(str, color_data)) + "\n")
    for row in color_img:
        result.write('\t'.join(map(str, row)) + "\n")
result.close()
```

It's not ideal to have users do this manually and the variables that need to be output depend on which of the `analyze_*` functions are run by the user. In principle we have a method `plantcv.print_results` that could do this work for the user but it's somewhat complicated by the fact that running any particular analysis function is optional.

Furthermore, all measurements we output have to be hardcoded into the `plantcv-pipeline.py` parallelization script because we store the outputs into a SQLite database, so we have to map all measurements to a field in the database structure. This makes adding new measurements harder because they need to be coded into the results output files correctly, printed out correctly, and programmed to be captured by `plantcv-pipeline.py` correctly.

Changing all this will require multiple changes to different areas of PlantCV. I will outline some thoughts on ways we could tackle these issues. Once we agree on a strategy we can create one or more smaller issues to tackle specific, achievable tasks that relate back to this epic.

# Automatic Capture of Measurement Data

I think we can automatically log measurement data from all functions that are designed to produce measurements we track. To do this we could create a new global class, e.g. `Outputs`. The `Outputs` class can be set up to collect data from the various `analyze_*` functions. The class would be defined and initialized in the `plantcv/plantcv/__init__.py` file just like the class `Params`. What might this look like?

```python
class Outputs:
    def __init__(self):
        self.measurements = {}
        self.images = []

outputs = Outputs()
```

The `outputs` instance of the `Outputs` class is then accessible in a PlantCV module, e.g. `analyze_objects`:

```python
from plantcv.plantcv import outputs
# Lots of code here, then we get to the measurements
if not "shapes" in outputs.measurements:
    outputs.measurements["shapes"] = {}
outputs.measurements["shapes"]["area"] = area
outputs.measurements["shapes"]["hull-area"] = hull_area
# etc., and any output images
outputs.images.append(analysis_images)
# etc.
```

Then data could be printed to the results files like we currently do but using a function like:

```python
pcv.print_results(outputs)
```

For now we can format the output data in a way that is compatible with `plantcv-pipeline.py` but this gives us easy control to change the output to something more useful later without disrupting what the user is doing.

# Flexible measurement storage/organization

I'm less certain about how we can change `plantcv-pipeline.py` to be measurement-agnostic. My rough thought is that we could store the output measurements in JSON format so that we could accommodate the hierarchical nature of the data (e.g. we could store multiple timepoints for the same plant within a nested structure. We could also store measurements from multiple cameras together within a "snapshot"). We would just have to think about what's the best way to collect data and then feed it into R or other analysis platforms that expect tabular data.

**Comment by dschneiderch** [comment]
> We would just have to think about what's the best way to collect data and then feed it into R or other analysis platforms that expect tabular data.

for what its worth, both python (pandas) and R (rjson) have functions  to read json

**Comment by nfahlgren** [comment]
Awesome, thanks @dschneiderch
