### ISSUE TITLE
Revise process for creating/updating SVG colorbar graphs

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#307]
### Description

From #306:

In the `plantcv.fluor_fvfm` function, 

>the svg colorbar does not update if it is already present because you are checking for the file. i'd propose rewriting it regardless if it exists since there is no way to check if the cmap is the same.

### Completion Criteria

ACTION: remove `if not os.path.isfile(os.path.join(path, fig_name)):`

Alternatively, do we need the colorbar at all? We added the colorbar into the `matplotlib` image recently. @dschneiderch would that be a desirable way to keep the colorbar associated with the image rather than creating one or more separate SVG files?

**Comment by dschneiderch** [comment]
I don't need a separate colorbar, i think its better as part of the png but assumed someone else wanted it.

i added the cmap value to the fig_name and prepended the filename argument:
https://github.com/dschneiderch/plantcv/blob/43fa7b783c19ee904623a85d63fece2d04a2cfab/plantcv/plantcv/fluor_fvfm.py#L161

I would be fine removing the separate colorbar as svg.

**Comment by dschneiderch** [comment]
I also added some scaling to the colorbar in the .png so its not so big:
https://github.com/dschneiderch/plantcv/blob/43fa7b783c19ee904623a85d63fece2d04a2cfab/plantcv/plantcv/fluor_fvfm.py#L145

**Comment by HaleySchuhl** [comment]
@dschneiderch We merged the `pcv.pseudocolor` function yesterday, and this will plot/print the colorbar with the pseudocolored image. I included your scaling of the colorbar too! I'll be updating the other functions that currently return pseudocolored images today, so they instead return the grayscale image that could be used in `pcv.pseudocolor`. 

Is there any situation in where someone wouldn't want the color bar in the pseudocolored image?

**Comment by dschneiderch** [comment]
Awesome!
Yes I'm sure there are - maybe for example when you are going to show several pseduo color images in a paper/poster you'd only need the colorbar once. However, I think its easy enough for the user to crop the scale bar as needed. on the other hand, having a vector graphic of the scalebar could potentially be useful. I guess it depends how much work it is. Alternatively, if you provided a  dpi argument for the print function it would server a similar purpose and improve the quality of the image itself.
