### ISSUE TITLE
Issue with plotting images/histograms in PSII function

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#308]
### Description

From #306:

In `plantcv.fluor_fvfm` 
> if debug = 'plot' then the histogram gets messed up. maybe there is a figure counter missing...i'm not sure how this works exactly. see attached image.

### Completion Criteria

Identify why the output for @dschneiderch is not working but is for us. Maybe the 8-bit vs 16-bit format is still an issue? Or an image input format issue?

**Comment by dschneiderch** [comment]
@nfahlgren i'm seeing the same warning as reported in issue #243  - could this cause the histogram/plotting issue?

```
sys.version
Out[297]: '3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)]'
import matplotlib as mpl
mpl.__version__
Out[301]: '3.0.1'

```

**Comment by nfahlgren** [comment]
@dschneiderch, @HaleySchuhl figured out the problem here. We plot both the histogram and an image and we are not properly closing the figure between plots so they get overlaid. This won't be an issue once we refactor the PSII function to output the image and histogram plots but definitely currently a bug.

**Comment by dschneiderch** [comment]
@nfahlgren nice work!
Was this by chance only an issue if you were running fluor_fvfm a second time without manually closing the figure window? that was my guess but I didn't get a chance to test that.

**Comment by nfahlgren** [comment]
Good question, not totally sure but could definitely be. We were using `plt.clf`, which just clears the figure but not the plot device, so any new plot just layers on top. It definitely might carry through between functions or function executions.

**Comment by nfahlgren** [comment]
This should be resolved now in the current version, but feel free to reopen of course.
