### ISSUE TITLE
Document/refactor filename argument parameters

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#309]
### Description

From #306:

> the filename argument for fluor_fvfm is confusing. looks like it can be a path or filename with or without extension. for most of the output figures (pseudo_fvfm, fvfm_hist, and fv_img), a filename of "test" becomes the prefix e.g. "test_pseudo_fvfm.png" but the code suggests you are expecting a directory too? at the moment it just gets saved in my working directory.
confusingly, the FvFm_pseudocolor_colorbar is saved without the prefix in the root project directory. can we add the prefix? could we also create the directory if it doesn't exist? updating the input description to specify path and filename where the path already exists would probably be helpful too.

The filename argument is also used similarly in several functions including `analyze_objects`, `analyze_color`, etc. Any solution here applies to all of these functions.

### Completion Criteria

ACTION: at least clarify input description. add prefix to colorbar svg ?

**Comment by dschneiderch** [comment]
more explicit documentation could look like this:
https://github.com/dschneiderch/plantcv/blob/43fa7b783c19ee904623a85d63fece2d04a2cfab/plantcv/plantcv/fluor_fvfm.py#L21

And then we could change fig_name for the colorbar (or get rid of it all together):
fig_name = os.path.splitext(os.path.basename(filename))[0] + '_FvFm_pseudocolor_'+ cmap + '_colorbar.svg'

in my mind the best solution would be to have separate arguments for path and prefix but that would probably breaks things in existing uses so maybe just handle it in the fiunction documentation

**Comment by nfahlgren** [comment]
For images that are print using the `debug="print"` option we refactored it to allow the user to specify the output directory globally using `pcv.params.debug_outdir = "path"`. We could potentially either use the same output path (renamed) or have a separate outputs directory parameter. The nice thing about this option is that there isn't an extra input to each function that has the filename parameter. We could set it up so the output directory gets created automatically also.

**Comment by dschneiderch** [comment]
Pcv.params.outdir could work – but it depends if people would want to save output from different cameras in different directories? In this case a path for the given function might be better I think.

**Comment by HaleySchuhl** [comment]
The current version includes updates to `pcv.print_image` that allows the funtion to handle different types of images (in addition to ndarrays it can now save out matplotlib figures, like those returned by various analyze* functions, and plotnine ggplots, which is the type of image for all histograms). These updates allow users to include `pcv.print_image` lines into pipelines which allows images to get saved with more descriptive filenames and in more specific locations. 

Feel free to reopen with any additional discussion or concerns!
