### ISSUE TITLE
Analyze color - Mean hue and other statistics

### ISSUE THREAD

**Issue by JLJ90** [danforthcenter/plantcv#314]
### Description

This is somewhere between a feature request and a discussion. I am interested in analysing how color changes over time. Say I have these images how would be the best way to analyse them?

At the moment my idea, and what I have been testing, is to extract the hue channel from the image, after it has been masked, then counting all the pixels that are from the plant tissue, adding them to an array then calculating the circular mean of the array using scipy's stats.circmean(array, high = 180). After this I would do Statistics on these means to find out if there is a significant difference in colour.

The results from this tally to what I can see looking at histograms, so I beleive it to be a reasonable method, but I thought I would try and get the opinion of others on this idea.

I think it would be a nice addition to the analyze color function, if others agree that this is a reasonable approach to measuring colour.

 Perhaps further statisitics such as median, range etc, would also be helpful.

Something similar to this site http://mkweb.bcgsc.ca/color-summarizer/? 

I am happy to take this on as a project, so long as it seems like a reasonable idea. There may be some logic that I am missing so please critique.

**Comment by JLJ90** [comment]
Yes, for most green plants I can't imagine the circular mean making much difference, but when red is concerned the results may become strange without it. Okay, I shall get to work adding this feature, it will be a nice small project for me.

I enjoyed the plots in your paper, I am going to have to use that for my own data, did you use joyplots for that? 

I am looking forward to the next release!

**Comment by JLJ90** [comment]
I have done the code for my proposed addition to the analyse color function, I am going to post it here for criticism as this will be my first time contributing.

`
 Analyze Color of Object

import os
import cv2 , statistics
import numpy as np
import pandas as pd
from plantcv.plantcv import print_image
from plantcv.plantcv import plot_image
from plantcv.plantcv import fatal_error
from plantcv.plantcv import plot_colorbar
from plantcv.plantcv import params
from collections import Counter, OrderedDict  # new
from scipy import stats # new





def analyze_color_test(rgb_img, mask, bins, hist_plot_type=None):
    """Analyze the color properties of an image object

    Inputs:
    rgb_img          = RGB image data
    mask             = Binary mask made from selected contours
    bins             = number of color bins the channel is divided into
    hist_plot_type   = 'None', 'all', 'rgb','lab' or 'hsv'

    Returns:
    hist_header      = color histogram data table headers
    hist_data        = color histogram data table values
    analysis_image   = histogram output
    stats_dict       = dictionary containing mean, std and median hue

    :param rgb_img: numpy.ndarray
    :param mask: numpy.ndarray
    :param bins: int
    :param hist_plot_type: str
    :return hist_header: list
    :return hist_data: list
    :return analysis_images: list
    ::return stats_dict: dict
    """
    import matplotlib
    matplotlib.use('Agg', warn=False)
    # from matplotlib import pyplot as plt
    from plotnine import ggplot, aes, geom_line, scale_x_continuous, scale_color_manual

    params.device += 1

    if len(np.shape(rgb_img)) < 3:
        fatal_error("rgb_img must be an RGB image")

    masked = cv2.bitwise_and(rgb_img, rgb_img, mask=mask)
    b, g, r = cv2.split(masked)
    lab = cv2.cvtColor(masked, cv2.COLOR_BGR2LAB)
    l, m, y = cv2.split(lab)
    hsv = cv2.cvtColor(masked, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    # Color channel dictionary
    norm_channels = {"b": np.divide(b, (256 / bins)).astype(np.uint8),
                     "g": np.divide(g, (256 / bins)).astype(np.uint8),
                     "r": np.divide(r, (256 / bins)).astype(np.uint8),
                     "l": np.divide(l, (256 / bins)).astype(np.uint8),
                     "m": np.divide(m, (256 / bins)).astype(np.uint8),
                     "y": np.divide(y, (256 / bins)).astype(np.uint8),
                     "h": np.divide(h, (256 / bins)).astype(np.uint8),
                     "s": np.divide(s, (256 / bins)).astype(np.uint8),
                     "v": np.divide(v, (256 / bins)).astype(np.uint8)
                     }

    # Histogram plot types
    hist_types = {"all": ("b", "g", "r", "l", "m", "y", "h", "s", "v"),
                  "rgb": ("b", "g", "r"),
                  "lab": ("l", "m", "y"),
                  "hsv": ("h", "s", "v")}

    # # If the user-input pseudo_channel is not None and is not found in the list of accepted channels, exit
    # if pseudo_channel is not None and pseudo_channel not in norm_channels:
    #     fatal_error("Pseudocolor channel was " + str(pseudo_channel) +
    #                 ', but can only be one of the following: None, "l", "m", "y", "h", "s" or "v"!')
    # # If the user-input pseudocolored image background is not in the accepted input list, exit
    # if pseudo_bkg not in ["white", "img", "both"]:
    #     fatal_error("The pseudocolored image background was " + str(pseudo_bkg) +
    #                 ', but can only be one of the following: "white", "img", or "both"!')
    # # If the user-input histogram color-channel plot type is not in the list of accepted channels, exit
    if hist_plot_type is not None and hist_plot_type not in hist_types:
        fatal_error("The histogram plot type was " + str(hist_plot_type) +
                    ', but can only be one of the following: None, "all", "rgb", "lab", or "hsv"!')
    histograms = {
        "b": {"label": "blue", "graph_color": "blue",
              "hist": cv2.calcHist([norm_channels["b"]], [0], mask, [bins], [0, (bins - 1)])},
        "g": {"label": "green", "graph_color": "forestgreen",
              "hist": cv2.calcHist([norm_channels["g"]], [0], mask, [bins], [0, (bins - 1)])},
        "r": {"label": "red", "graph_color": "red",
              "hist": cv2.calcHist([norm_channels["r"]], [0], mask, [bins], [0, (bins - 1)])},
        "l": {"label": "lightness", "graph_color": "dimgray",
              "hist": cv2.calcHist([norm_channels["l"]], [0], mask, [bins], [0, (bins - 1)])},
        "m": {"label": "green-magenta", "graph_color": "magenta",
              "hist": cv2.calcHist([norm_channels["m"]], [0], mask, [bins], [0, (bins - 1)])},
        "y": {"label": "blue-yellow", "graph_color": "yellow",
              "hist": cv2.calcHist([norm_channels["y"]], [0], mask, [bins], [0, (bins - 1)])},
        "h": {"label": "hue", "graph_color": "blueviolet",
              "hist": cv2.calcHist([norm_channels["h"]], [0], mask, [bins], [0, (bins - 1)])},
        "s": {"label": "saturation", "graph_color": "cyan",
              "hist": cv2.calcHist([norm_channels["s"]], [0], mask, [bins], [0, (bins - 1)])},
        "v": {"label": "value", "graph_color": "orange",
              "hist": cv2.calcHist([norm_channels["v"]], [0], mask, [bins], [0, (bins - 1)])}
    }

    hist_data_b = [l[0] for l in histograms["b"]["hist"]]
    hist_data_g = [l[0] for l in histograms["g"]["hist"]]
    hist_data_r = [l[0] for l in histograms["r"]["hist"]]
    hist_data_l = [l[0] for l in histograms["l"]["hist"]]
    hist_data_m = [l[0] for l in histograms["m"]["hist"]]
    hist_data_y = [l[0] for l in histograms["y"]["hist"]]
    hist_data_h = [l[0] for l in histograms["h"]["hist"]]
    hist_data_s = [l[0] for l in histograms["s"]["hist"]]
    hist_data_v = [l[0] for l in histograms["v"]["hist"]]

    binval = np.arange(0, bins)
    bin_values = [l for l in binval]

    # Store Color Histogram Data
    hist_header = [
        'HEADER_HISTOGRAM',
        'bin-number',
        'bin-values',
        'blue',
        'green',
        'red',
        'lightness',
        'green-magenta',
        'blue-yellow',
        'hue',
        'saturation',
        'value'
    ]

    hist_data = [
        'HISTOGRAM_DATA',
        bins,
        bin_values,
        hist_data_b,
        hist_data_g,
        hist_data_r,
        hist_data_l,
        hist_data_m,
        hist_data_y,
        hist_data_h,
        hist_data_s,
        hist_data_v
    ]

    # if pseudo_channel is not None:
    #         analysis_images = _pseudocolored_image(norm_channels[pseudo_channel], bins, rgb_img, mask, pseudo_bkg,
    #                                                pseudo_channel, filename, analysis_images)
    analysis_image = []
    dataset = pd.DataFrame({'bins': binval, 'blue': hist_data_b,
                            'green': hist_data_g, 'red': hist_data_r,
                            'lightness': hist_data_l, 'green-magenta': hist_data_m,
                            'blue-yellow': hist_data_y, 'hue': hist_data_h,
                            'saturation': hist_data_s, 'value': hist_data_v})

    # Make the histogram figure using plotnine
    if hist_plot_type is not None:
        if hist_plot_type == 'rgb':
            df_rgb = pd.melt(dataset, id_vars=['bins'], value_vars=['blue', 'green', 'red'],
                             var_name='Color Channel', value_name='Pixels')
            hist_fig = (ggplot(df_rgb, aes(x='bins', y='Pixels', color='Color Channel'))
                        + geom_line()
                        + scale_x_continuous(breaks=list(range(0, bins, 25)))
                        + scale_color_manual(['blue', 'green', 'red'])
                        )
            analysis_image.append(hist_fig)

        elif hist_plot_type == 'lab':
            df_lab = pd.melt(dataset, id_vars=['bins'],
                             value_vars=['lightness', 'green-magenta', 'blue-yellow'],
                             var_name='Color Channel', value_name='Pixels')
            hist_fig = (ggplot(df_lab, aes(x='bins', y='Pixels', color='Color Channel'))
                        + geom_line()
                        + scale_x_continuous(breaks=list(range(0, bins, 25)))
                        + scale_color_manual(['yellow', 'magenta', 'dimgray'])
                        )
            analysis_image.append(hist_fig)

        elif hist_plot_type == 'hsv':
            df_hsv = pd.melt(dataset, id_vars=['bins'],
                             value_vars=['hue', 'saturation', 'value'],
                             var_name='Color Channel', value_name='Pixels')
            hist_fig = (ggplot(df_hsv, aes(x='bins', y='Pixels', color='Color Channel'))
                        + geom_line()
                        + scale_x_continuous(breaks=list(range(0, bins, 25)))
                        + scale_color_manual(['blueviolet', 'cyan', 'orange'])
                        )
            analysis_image.append(hist_fig)

        elif hist_plot_type == 'all':
            s = pd.Series(['blue', 'green', 'red', 'lightness', 'green-magenta',
                           'blue-yellow', 'hue', 'saturation', 'value'], dtype="category")
            color_channels = ['blue', 'yellow', 'green', 'magenta', 'blueviolet',
                              'dimgray', 'red', 'cyan', 'orange']
            df_all = pd.melt(dataset, id_vars=['bins'], value_vars=s, var_name='Color Channel',
                             value_name='Pixels')
            hist_fig = (ggplot(df_all, aes(x='bins', y='Pixels', color='Color Channel'))
                        + geom_line()
                        + scale_x_continuous(breaks=list(range(0, bins, 25)))
                        + scale_color_manual(color_channels)
                        )
            analysis_image.append(hist_fig)
    
    #flatten so that it is hashable
    h = h.flatten(order = 'C')
    
    # produces a dictionary with hue as key, and frequency as values.
    c = Counter(h)
    # remove background colour 
    del c[0]

    # sort the dictionary in order 
    ordered = dict(sorted(c.items(), key=lambda t: t[0]))


    # loop adds the hue to a list for the frequency of each hue
    temp_hue_list_hsv = []
    for i in range(len(ordered)):

        j = 0

        while j < list(ordered.values())[i]:
            temp_hue_list_hsv.append(list(ordered.keys())[i])

            j += 1


    #calculate relevant statistics 
    circular_mean = stats.circmean(temp_hue_list_hsv, 180)
    circular_std = stats.circstd(temp_hue_list_hsv, 180) # assumes samples are in the range [low to high] which they are
    min_hue = min(temp_hue_list_hsv)
    max_hue = max(temp_hue_list_hsv)

    median = statistics.median(temp_hue_list_hsv)

    stats_dict = {'mean': circular_mean, 'std' : circular_std, 'median': median} 

            #     if hist_plot_type is not None:
            #         # Create Histogram Plot
            #         for channel in hist_types[hist_plot_type]:
            #             plt.plot(histograms[channel]["hist"], color=histograms[channel]["graph_color"],
            #                      label=histograms[channel]["label"])
            #             plt.xlim([0, bins - 1])
            #             plt.legend()
            #         # Print plot
            #         fig_name = (os.path.splitext(filename)[0] + '_' + str(hist_plot_type) + '_hist.svg')
            #         plt.savefig(fig_name)
            #         analysis_images.append(['IMAGE', 'hist', fig_name])
            #         if params.debug == 'print':
            #             fig_name = os.path.join(params.debug_outdir, str(params.device) + '_' + str(hist_plot_type)
            #                        + '_hist.svg')
            #             plt.savefig(fig_name)
            #         plt.clf()

    return hist_header, hist_data, analysis_image, stats_dict`


Examples of results.

Using an image from the vis pipeline tutorial

![image](https://user-images.githubusercontent.com/35571955/52534128-555a2b00-2d35-11e9-8948-f89c80ae1ee4.png)

{'mean': 29.113802304695806, 'std': 31.363811023186937, 'median': 37.0}

Using one of my own images:

![bag1](https://user-images.githubusercontent.com/35571955/52534140-889cba00-2d35-11e9-8a12-59e6f08f1978.jpg)

After i cropped out the color card etc

{'mean': 34.283551714684044, 'std': 1.8281477894433626, 'median': 34}

Please, let me know what you think! The results make sense to me, but there may be a logic error in there somewhere, I welcome criticism.

Thanks!

**Comment by HaleySchuhl** [comment]
Hi @JLJ90, sorry for the delayed reply! 

The results make sense to me too. We have made a few small changes to `pcv.analyze_color` so keep that in mind when you submit your pull request so you don't get merge conflicts. The only other comments I have is that `max_hue` & `min_hue` don't get used after assignment, `collections.OrderedDict` doesn't seem be get used, and a dictionary doesn't match our current output structure. All other measurements are returned as a list for the header and a list for the data (and these data are stored into an `Outputs` class that gets used by the `pcv.print_results` function). I'd suggest adding mean, std, and median to the existing lists that get returned. Please don't hesitate if you have any questions. We look forward to seeing your pull request!

**Comment by JLJ90** [comment]
Hi @HaleySchuhl I have been trying to do some more testing with this, but I am getting stuck with the 'outputs'. 

I have made a test function by copying the analyze_color function and importing all the necessary packages, but whenever I run it  I get the message 

ImportError                               Traceback (most recent call last)
<ipython-input-3-b6a1e65e4e6c> in <module>()
      8 from plantcv.plantcv import fatal_error
      9 from plantcv.plantcv import params
---> 10 from plantcv.plantcv import outputs
     11 
     12 

ImportError: cannot import name 'outputs'

Furthermore, I am trying to understand where I should add the new calculated variables so that they can be returned.

would I simply add this block of code to the function?
`
if not 'color_statistics' in outputs.measurements:
        outputs.measurements['color_statistics'] = {}
    outputs.measurements['color_statistics']['mean'] = circular_mean
    outputs.measurements['color_statistics']['standard-deviation'] = circular_std
    outputs.measurements['color_statistics']['median'] = median
`
One last question, how can I view the data that is created for 'outputs' 

for example, if I run:

color_header, color_data, color_histogram = pcv.analyze_color(image,mask,256)

the function adds data to outputs.measurements. How would I view this?

Sorry for all the questions, I am just having a hard time understanding how to return the results of the calculations.

**Comment by HaleySchuhl** [comment]
Hello @JLJ90 ,

I'm not sure why you're getting an error on `from plantcv.plantcv import outputs`. I looked at your forked PlantCV repository and it's quite a few commits behind master so maybe updating your fork would do the trick? You could also try installing PlantCV in your current environment. 

> would I simply add this block of code to the function?
if not 'color_statistics' in outputs.measurements: outputs.measurements['color_statistics'] = {} outputs.measurements['color_statistics']['mean'] = circular_mean outputs.measurements['color_statistics']['standard-deviation'] = circular_std outputs.measurements['color_statistics']['median'] = median
> 
That looks correct! Somewhere in the `pcv.analyze_color` function you also need to save lists (maybe called `color_stats_header` and `color_stats_data`) that contain the information that was getting stored into the `stats_dict`. 

>the function adds data to outputs.measurements. How would I view this?
>
We use `pcv.print_results` to print out a tab-delimited text file, so you can run `pcv.print_results("your_filename.txt") and it will print everything stored in `outputs.measurements`. If you want separate text files for the data stored by each function you can run `pcv.print_results()` and then `pcv.outputs.clear()` before running the next function that stores data to `outputs`. So you'd also need to add 
```
 if 'color_histogram' in outputs.measurements:
    header = ['HEADER_COLOR_STATS']
    data = ['COLOR_STATS_DATA']
    for k, v in outputs.measurements['color_stats_data'].items():
        header.append(k)
        data.append(v)
    result.write('\t'.join(map(str, header)) + '\n')
    result.write('\t'.join(map(str, data)) + '\n')
``` 

Feel free to open a pull request and we can directly collaborate on your branch to get it ready to merge! @nfahlgren and I have been meaning to update the pipeline parallelization part of PlantCV (#220 ) to allow for more flexible outputs. We can make any necessary changes to `plantcv-pipeline.py` on your branch after you publish it.

**Comment by JLJ90** [comment]
Hello @HaleySchuhl 

I have updated my fork and created a pull request. Thanks for all the help!
