### ISSUE TITLE
multiple ROI

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#320]
### Description
based on my understanding, it is not possible to define multiple ROI for a single image. multiple ROI would be beneficial to remove signal from containers or infrastructure in the image.

### Details
My use case is segmenting well plate image so I would like to define a grid of 6 circle rois.
the cluster_contour() function only works if the thresholding step can precisely define the plant area, but with well plates reflection off the plastic dish makes this difficult. It would be more effective to define precisely positioned circles in a regular grid.
Another case I have though, are three plants that are offset from each other in a triangular "grid" so it would be great to have flexibility in defining the arrangement the ROIs.

Consider the case in the photo below. would be nice to use ROI to remove edge effects. The first image is from `roi_obj, roi_hier = pcv.roi.from_binary_image(thresh,img)` and the second is from 

`obj, objh = pcv.find_objects(img,thresh)
clusters_i, contours, hierarchies = pcv.cluster_contours(img, obj, objh, 2, 3)
`

![image](https://user-images.githubusercontent.com/7461221/52489765-f9967300-2b77-11e9-88fd-c2e2193f6181.png)

### Possible solutions
Possible solutions I can see are allowing a list of x, y pairs in `pcv.roi` or lists of rois, hierarchies in `pcv.roi_objects`. 
You could potentially develop a new function that allows the user to define a grid of roi too.
Maybe there is a better way?

Thanks!

**Comment by HaleySchuhl** [comment]
The plan is to write a function that will make a grid of circular ROIs where the user will specify starting coordinate (center top left object), radius of circular ROIs to be created, spacing, number of rows, and number of columns. We expect this will be more common. For the case where a rectangular grid isn't appropriate (like the triangle situation mentioned by @dschneiderch) we could add the option to provide a list of center coordinates. In order to avoid changing each function that could be used downstream of defining ROIs, we can provide an example of a for loop over `pcv.roi_objects` and other downstream functions.

**Comment by dschneiderch** [comment]
@HaleySchuhl Sounds great!
one thing, I've found it to be quite difficult to set the perfect series of rois.  One feature that would be nice in `roi_objects` to help this would be a "keep one object". Only the largest object within an roi would be kept. It would solve issues like this where the pic is the final `new_mask` in the code below.

![338_fill0](https://user-images.githubusercontent.com/7461221/52666963-7a30d880-2ec4-11e9-8a21-8127cc8c5b5b.png)

`pcv.fill` helps if you get it close, but only keeping the most obvious object would be the best for this case.

here is some code how I'm doing it now:

```
    # identify each cell with a separate ROI and combine into a single mask
    ix=2
    iy=1
    radius=88
    num_wells = 6
    nrows = 2
    ncols = 3
    num_pos_x = num_wells/ncols+1
    num_pos_y = num_wells/nrows-1
    obj, objh = pcv.find_objects(img,thresh)
    new_mask = img*0
    for ix in np.arange(num_pos_x):
        xcenter = int(95+(ix*207))
        print("xcenter: %d" % xcenter)
        for iy in np.arange(num_pos_y):
            ycenter = int(128+(iy*208))
            print("ycenter: %d" % ycenter)
            r,h=pcv.roi.circle(x=xcenter,y=ycenter,r=radius,img=thresh)
            roi_objects, hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_type='cutto',roi_contour=r, roi_hierarchy=h, object_contour=obj,obj_hierarchy=objh)
            new_mask = cv2.bitwise_or(new_mask,kept_mask)
```
