### ISSUE TITLE
cluster_counter_splitimg() output adjustment?

### ISSUE THREAD

**Issue by Mahi-Mai** [danforthcenter/plantcv#353]
Hello, plantCV crew!  Is it possible to set cluster_contour_splitimg() to output an array of images instead of an array of paths?  I'd like to perform some additional operations on the images before they're saved.

Have a nice day!

**Comment by HaleySchuhl** [comment]
Hello @Mahi-Mai ,

Right now `pcv.cluster_contour_splitimg` returns the array of paths, but we do have a relatively new function that I believe would work for your purposes! The [pcv.roi.multi](https://plantcv.readthedocs.io/en/latest/roi_multi/) was added for more flexibility. In the documentation page there is an example of how to write the downstream steps (like performing shape analysis on each plant) all in the same pipeline. 

I agree that it would be useful to return both an array of paths AND and array of images in the `pcv.cluster_contour_splitimg` function. In the meanwhile, please don't hesitate if you have any further questions!

**Comment by Mahi-Mai** [comment]
That definitely sounds useful.. thanks, Haley!  You guys are always so responsive, and I really appreciate that.
