### ISSUE TITLE
Hierarchical data/metadata outputs

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#365]
### Description

To improve the way we collect and organize outputs (metadata and measurements) our idea is to change from a tabular to hierarchical data structure. In tabular format we are constrained in what information we can collect because we need to pre-define what data we expect to find. In a hierarchical format we can collect both pre-defined and user-defined measurements as long as we enforce a minimum amount of information to describe the data.

#### Current methods

Our current data output structure looks like this:

```
HEADER_<TYPE>    var1    var2
<TYPE>_DATA    value1    value2
```

This data gets mapped into a relational database by creating a tables that hold various <TYPE> data with columns for each measurement (vars). So when we add a `var` we have to also inform the process that builds the database that we expect to find `var` (even if we don't we need to know it could exist so we can keep a placeholder/NA value). This makes adding new measurements or other information to the collected output data cumbersome. It also effectively prevents users from collecting custom information without going through the development team to add it (or add it themselves).

#### Proposed changes

A core piece of restructuring measurement data is to define the minimum information we need to make each measurement usable by `plantcv-pipeline.py` without the need for special handling of every class of measurements like we currently do. Ultimately we will want to co-align this with [MIAPPE](https://www.miappe.org/) but in particular we should follow the recommendations for describing observed variables laid out in (Ćwiek-Kupczyńska et al. 2016):

> * Variable ID—a local unique identifier of a variable, e.g. a short name, that is a key linking the definitions of variables with observations in Derived Data File,
> * Trait—a name of the trait mapped to an external ontology; if there is no exact mapping, an informative description of the trait,
> * Method—a name of the measurement method mapped to an external ontology; if there is no exact mapping, an informative description of the measurement procedure,
> * Scale—units of the measurement or a scale in which the observations are expressed; if possible, standard units and scales should be used and mapped to existing ontologies; in case of a non-standard scale a full explanation should be given.

Programmatically I think we also need information about the type of data (`int`, `str`, etc.) and possibly whether the data is a single value or a list of values (maybe this could be automatically determined). I think we also need a to store a label for each value, which will be useful when the data is a frequency table (e.g. hues).

@HaleySchuhl and I discussed having a `pcv.add_measurement` type function that has the information above as required inputs so that we can ensure we have the minimum information standard as much as possible.

What would the data look like in a hierarchical format? I propose we use JSON as it translates to/from Python data structures easily. In Python dictionary/JSON format I am thinking it would look something like this:

```json
{
    "image-ID": {  
        "metadata": {
        },
        "observations": {
            "pixel_area": {
                "trait": "area",
                "method": "plantcv.plantcv.analyze_objects",
                "scale": "pixels",
                "type": "int",
                "value": 1000,
                "label": "pixels"
            },
            "hull_area": {
                "trait": "convex hull area",
                "method": "plantcv.plantcv.analyze_objects",
                "scale": "pixels",
                "type": "int",
                "value": 1500,
                "label": "pixels"
            },
            "hue": {
                "trait": "hue value distribution",
                "method": "plantcv.plantcv.analyze_color",
                "scale": "counts",
                "type": "int",
                "value": [0, 0, 20, 60, 80, 30, 0, ... ],
                "label": [0, 2, 4, 6, 8, 10, ... ]
            } 
        }
    }
}
```

This is just a proposal, as we try to implement it we will need to refine it I'm sure.

#### Citations
Ćwiek-Kupczyńska H, Altmann T, Arend D, Arnaud E, Chen D, Cornut G, Fiorani F, Frohmberg W, Junker A, Klukas C, Lange M, Mazurek C, Nafissi A, Neveu P, van Oeveren J, Pommier C, Poorter H, Rocca-Serra P, Sansone S-A, Scholz U, van Schriek M, Seren Ü, Usadel B, Weise S, Kersey P, Krajewski P. 2016. Measures for interoperability of phenotypic data: minimum information requirements and formatting. Plant methods 12:44. DOI: [10.1186/s13007-016-0144-4](https://doi.org/10.1186/s13007-016-0144-4).

### Completion Criteria

- [x] Update `Outputs` class
- [x] Update how `analyze_*` functions push data to `Outputs`
- [x] Update how `pcv.print_results` outputs data
- [x] Update `plantcv-pipeline.py` to accept new output format
- [x] Remove tabular outputs from `analyze_*` functions
- [x] Update documentation

**Comment by HaleySchuhl** [comment]
Discuss next steps: 

- Add a function that takes hierarchical data output (the .json file) and translate it to a table to be used in Excel, R, etc. 
- How to handle time series data? Link observations by plant ID?

**Comment by nfahlgren** [comment]
One change I would make to our current output is in the `variables` section. The `variables` dictionary declares what metadata and observations are found in at least one entity but not what kind of data it is. This causes a problem because for each entity we have two dictionaries (`metadata` and `observations`) and we don't know which dictionary the variable is in. I think the simple fix is to change the `variables` dictionary. Current looks like this:

```json
{
    "variables": {
        "image": 1,
        "area": 1
    }
}
```

But could be like this:

```json
```json
{
    "variables": {
        "image": "metadata",
        "area": "observations"
    }
}
```

Alternatively, each `entity` could potentially be flattened into one dictionary, maybe there's no real need to separate metadata from quantitative data.
```
