### ISSUE TITLE
Morphology: Branch Id Issue

### ISSUE THREAD

**Issue by karnoldbio** [danforthcenter/plantcv#369]
### Description
Question/Bug

in testing out the new morphology package that was added recently i ran into an issue with identifying branch points from the image skeleton. it seems that after the image was skeletonized, the point of separation is not in one of the patterns plantcv recognizes as a branch point. rather than being in a recognized formation of 
[ 0  1   0]
[-1  1 -1]
[ 1 -1  1]
but the formation of the skeleton where the leaf separates is
[0  1  0]
[1  1  0]
[1  0  1]

because of the pixel in the [1][0] position it does not match the pattern and thus is seen as a continuation of the same segment.

my question in relation to this issue is that if the pattern was changed from
[ 0  1   0]    
[-1  1 -1]            
[ 1 -1  1 ]          
 to     
 [ 0  1  0]
 [ 0  1  0]
 [1 -1  1]
would this solve the issue or in your testing are there a number of plants that require that distinction? 

### Details
an example image of the issue
![image](https://user-images.githubusercontent.com/46695868/57642176-8122c200-756b-11e9-8294-f90c3f37998e.png)

![image](https://user-images.githubusercontent.com/46695868/57642321-e37bc280-756b-11e9-9a12-ca9b274cb6d7.png)

![image](https://user-images.githubusercontent.com/46695868/57642425-2473d700-756c-11e9-9a48-c76f8974d079.png)

this fix would allow us to more accurately collect data from the leaves when the segments are correctly identified

### Completion Criteria
- [ ] Discuss Usefulness and if fix is possible
- [ ] Determine Best method for applying fix
- [ ] More Correctly id branch points

**Comment by HaleySchuhl** [comment]
Hi @karnoldbio ,

Thanks for testing out the new morphology package! I definitely agree with your suggestion of incorporating more flexibility in the types of branch points that get recognized. I hadn't run into a branch point kernel like the example you posted while developing. This could easily be integrated into some of the improvements we have coming with the PlantCV v3.3 release. I believe any junction point where 3 or more lines meet should be recognized as a branch point and this shouldn't be at risk of finding false branch points in the middle of leaves after a skeleton is pruned. 

Thanks again for this suggestion! The v3.3 is coming in the next couple of days and we can certainly add updated kernels to the release.
