### ISSUE TITLE
tests fail after updating TEST_INPUT_MASK to a binary mask

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#372]
when testing to implement #371 I found tests/data/input_mask.png was not binary.  I added tests/data/input_mask_binary.png and changed `TEST_INPUT_MASK` to point to this file instead. This breaks `crop_position_mask` tests (the tests passed successfully with `input_mask.png`.

I looked into crop_position_mask but it's a bit complicated for me right now.

**Comment by nfahlgren** [comment]
This is fixed now in #373

**Comment by dschneiderch** [comment]
great!
