### ISSUE TITLE
help with test for change to pseudocolor

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#375]
In short, I modified visualize.pseudocolor to bypass the 20% buffer that is calculated around an object's bounding box when an obj is given to crop the output image. The bypass only happens if the input obj is already a rectangle. I found I wanted to pass a consistent size frame to crop the images rather than rely on the bounding box of the plant object which is changing size every time. Id like to crop the output because otherwise I end up with an image that is completely blank on one half (if I have two roi). Passing a rectangular obj lets me get a reasonably centered image.

https://github.com/danforthcenter/plantcv/blob/rect_obj_pseudocolor/plantcv/plantcv/visualize/pseudocolor.py

I think there should be a test to make sure a rectangle obj is treated right and the output is different from passing a plant obj.   However, since the function returns a matplotlib image rather than an array I'm not sure how to do that.

Here is how I'm using it. roi_c are the roi contours.

```
hgt,wdth = np.shape(mask)
if len(roi_c)==2:
    if i == 0:
        p1 = (int(0), int(0))
        p2 = (int(hgt), int(hgt))
    elif i == 1:
        p1 = (int(wdth-hgt), int(0))
        p2 = (int(wdth), int(hgt))
elif len(roi_c) == 1:
    cutwidth = (wdth-hgt)/2
    p1 = (int(cutwidth), int(0))
    p2 = (int(cutwidth+hgt), int(hgt))
else:
    pcv.fatal_error('Stop. You are using a script setup for 1 or 2 rois only.')

_,_,figframe,_ = pcv.rectangle_mask(plant_mask,p1, p2, color='white')

# print pseduocolor
imgdir = os.path.join(outdir,'pseudocolor_images',sampleid,'roi'+str(i),'colorindex')
os.makedirs(imgdir,exist_ok=True)
gi_img = pcv.visualize.pseudocolor(gi, obj = figframe[0], mask=plant_mask, cmap='viridis', min_value = .35, max_value = .55, background='black')
gi_img.savefig(os.path.join(imgdir, outfn + '_roi' + str(i) + '_greenness.png'), bbox_inches='tight')
gi_img.clf()
```

**Comment by HaleySchuhl** [comment]
Hello @dschneiderch ,

Noah and I talked about this feature, but we think it would be more useful to add a parameter that allows users to change the buffer if they provide an object for more flexibility than the hard coded buffer. This way you can provide a rectangular object and pass `padding=0` to achieve the same result. We can test this parameter by checking the shape of the pseudocolored image that gets returned, like we do currently.

**Comment by dschneiderch** [comment]
Ok, that would work for me. I did think about adding a padding argument but i was wary of overloading the function with input arguments.
Sorry I didn't realize you could check the shape of a matplotlib figure. I guess I should have seen the existing tests.
It would actually be nice if we could center the plant in a frame. my solution only sort of works by squaring the input object on which ever side the roi is on. But if someone had more than 1 row of roi it would start to look quite odd. I found however that if I provided an obj that extended past the end of the image it would just get cropped.  We would need to enlarge the image - which would only work well with black or white background. 
It occurred to me over the weekend that it might make more sense to use `cluster_contour()` annd `cluster_contour_splitimg()` in this case. I"m not super familiar with those functions so do you think that would address the centering issue?

**Comment by HaleySchuhl** [comment]
`cluster_contour_splitimg` doesn't crop the image, but it does make everything except the plant of interest white so it might be a good intermediate step to get equal frame sizes and have the plant centered. In `auto_crop` the plant will be centered if the user inputs equal values for `padding_x` and `padding_y` but the final frame won't be consistent unless the bounding box of the object provided is the same size, but we also generally expect people to input the plant contour. I could see a combination of `pcv.auto_crop` and `pcv.resize` being the easiest way to achieve centered images of equal size, but this will likely stretch images since the aspect ratio probably isn't consistent. Another route to get cropped images that are centered and equal frame size is by using the center of mass information collected by `pcv.analyze_shape` to inform the location of the rectangle mask you make.

**Comment by dschneiderch** [comment]
fyi, i merged master into rect_obj_pseudocolor.  It looked like you were working on a test - let me know if you want me to do something there. I updated docs based on where the direction the code was going.

**Comment by HaleySchuhl** [comment]
@dschneiderch Sounds good! I updated my branch from the one you have published and added the unit testing back in to cover the code as it currently stands, but the code seems quite different from what you're planning based on what you added to the `pseudocolor` docs page. Just to clarify, the plan is to have users provide a tuple of scale values for custom padding?

**Comment by dschneiderch** [comment]
No I had changed everything back to a single integer for simplicity.
