### ISSUE TITLE
Analyze Object area discrepancy

### ISSUE THREAD

**Issue by tvanbutselaar** [danforthcenter/plantcv#376]
I have analyzed a set of Arabidopsis plants with PlantCV. My primary interest is the rosette area that each plant has. While PlantCV does a great job, I found a discrepancy between the measured area in the output of the VIS pipeline as compared to measuring the pixels of a mask in a program like Photoshop or ImageJ. What can cause this? 

I have attached a mask + plant sample picture set (output from mulitplant pipeline). According to Analyze_Object, the area is 10022 pixels2, while the mask in ImageJ has an area of 9540 pixels2, resp. 
![01_DSC9543Ps6_0_p0 1](https://user-images.githubusercontent.com/50912561/58172181-22122b00-7c98-11e9-84ca-d1c7682aa0db.jpg)
![01_DSC9543Ps6_0_p0_mask 1](https://user-images.githubusercontent.com/50912561/58172208-30604700-7c98-11e9-955c-84a9cfc63ff4.jpg)

**Comment by HaleySchuhl** [comment]
Hello @tvanbutselaar ,

The `plantcv.analyze_object` function is using moments to calculate area rather than counting the pixels in the mask. Inside the function area is calculated as the first moment as follows: 
```
# Moments
#  m = cv2.moments(obj)
m = cv2.moments(mask, binaryImage=True)
# Properties
# Area
area = m['m00']
``` 

Don't hesitate to let us know if you have any other questions/concerns/suggestions!

**Comment by tvanbutselaar** [comment]
Great, thanks for the quick answer, it seems I need to refresh some geometry lessons again! (:
