### ISSUE TITLE
Package plantCV up to allow installation by `setup.py install`

### ISSUE THREAD

**Issue by jshoyer** [danforthcenter/plantcv#38]
### Description:
As Noah and I have discussed, it would be nice to allow installation of plantCV into a user/system library of packages via the standard python mechanism. This will free users from having to add the package source to their $PYTHONPATH, and enable use of the `help()` function, now that all (?) of the plantCV functions have PEP8 doc strings.
Cf. the Image Harvest [installation instructions](http://cropstressgenomics.org/data/html/installation.html).

### Context

I create this issue just as a public reminder---I think we are committed to doing this for version 2.0, and so I wanted it to be in the list for that milestone. Please tag this issue as an enhancement, if you like.

### Further suggestions
The `setuptools` package (rather than the legacy `distutils` package) is recommended for creating source distributions. I will keep reading through the documentation at [setuptools.readthedocs.io](https://setuptools.readthedocs.io/en/latest/) and [packaging.python.org](https://packaging.python.org/) as time allows.

Maybe it would be worth uploading the project to PyPI at some point, but that can wait.

As [noted](https://packaging.python.org/science/), "Scientific software tends to have more complex dependencies than most", and plantCV is no exception, primarily because it requires OpenCV to be installed. One could imagine automatic dependency handling to enable a user to install both plantCV and OpenCV in one shot, but it is not entirely obvious how to do this. So we should probably just update the docs to show that homebrew makes it relatively easy to install OpenCV on Macs, and otherwise defer worrying about this.

**Comment by nfahlgren** [comment]
@jshoyer I have setuptools working now for the dev branch. I tested it myself but it would be great if you (and others) could test it also to make sure it works for you. I updated the documentation, other than for Windows, here: http://plantcv.readthedocs.io/en/latest/installation/.

**Comment by calizarr** [comment]
If you follow most of the instructions and follow these lines of code:
```
virtualenv -p ~/usr/python2/bin/bin/python2.7 Test_PlantCV --system-site-packages
cd Test_PlantCV/
git clone https://github.com/danforthcenter/plantcv.git
cd plantcv/
git checkout dev
python setup.py install
```
the plantcv import fails with this error
```
Python 2.7.9 (default, Feb 23 2015, 15:48:39) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import plantcv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plantcv/__init__.py", line 11, in <module>
    from print_image import print_image
  File "plantcv/print_image.py", line 3, in <module>
    import cv2
ImportError: No module named cv2
>>> 
```
Seems like an OpenCV issue or path and OpenCV issue.

**Comment by nfahlgren** [comment]
@calizarr when I created a virtualenv as you did, on jupyter, it worked for me. Maybe there is something up with your OpenCV path? I used our standard system OpenCV, using the `--system-site-packages` like you did.

**Comment by nfahlgren** [comment]
Looks like the problem was that @calizarr used a local Python install that did not link with the system lib paths, so cv2 was not found in the default sys.path. I think the solution here is 1) adding documentation to the installation instructions for virtualenv and 2) adding better checking in the setup.py script to make sure cv2 is importable before installing.

**Comment by jshoyer** [comment]
`sudo python setup.py install` worked fine for me on a Macbook (os 10.10.5, 14F1909---I am still on Yosemite). Some cursory testing of a pipeline produced results that matched my expectations. Great!

(I have not actually read through your installation documentation yet)

**Comment by nfahlgren** [comment]
@jshoyer awesome, thanks!
