### ISSUE TITLE
PlantCV Parallel Pipeline: Database should be created by default

### ISSUE THREAD

**Issue by calizarr** [danforthcenter/plantcv#39]
When running PlantCV parallel pipeline script (plantcv-pipeline.py) if sqlite db already exists it prompts for an overwrite.

If on a non-interactive system, such as a queuing system it will then either hang or exit as if all went normally.

Maybe reverse it and create database by default or add an option to auto overwrite.

**Comment by maliagehan** [comment]
database is now created by default. If db exists data is appended, if -c flag is now used but a db exists, it will be overwritten.
