### ISSUE TITLE
ImportError: No module named plantcv

### ISSUE THREAD

**Issue by RavinduDharmasena** [danforthcenter/plantcv#404]
### Description

I installed the plantcv 3.4 to my conda environment and using that I tried to do the NIR workflow tutorial. But it gives me the error given below. There wasn't any problem while installing plantcv to the conda environment as well.

`Traceback (most recent call last):
  File "./research_dss/test/nir_analysis-NEW.py", line 8, in <module>
    from plantcv import plantcv as pcv
ImportError: No module named plantcv`

The command I executed is `./research_dss/test/nir_analysis-NEW.py -i
 ./research_dss/test/IMG_8764_RGB.jpg -o ./research_dss/test/abc/ -D 'print'`

The python script and related image is included here.
[NIR_Tutorial.zip](https://github.com/danforthcenter/plantcv/files/3323515/NIR_Tutorial.zip)

Conda version and Python version version in my Ubuntu 16.04.06 LTS computer is 4.6.14 and 3.7.3 respectively.

Given below is the package list in the conda environment
`
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cloudpickle               1.2.1                      py_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
dbus                      1.13.2               h714fa37_1  
decorator                 4.4.0                      py_0    conda-forge
django                    2.2.1                    py37_0  
expat                     2.2.5             hf484d3e_1002    conda-forge
ffmpeg                    4.0.2                ha0c5888_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freeglut                  3.0.0             hf484d3e_1005    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf5                      1.10.2               hc401514_3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
imageio                   2.5.0                    py37_0    conda-forge
jasper                    2.0.14               h07fcdf6_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0             hf484d3e_1000    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libopencv                 3.4.2                hb342d67_1  
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
matplotlib                2.2.2            py37hb69df0a_2  
mizani                    0.5.4                      py_0    conda-forge
ncurses                   6.1                  he6710b0_1  
nettle                    3.3                           0    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
palettable                3.1.1                      py_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he6710b0_0  
pillow                    6.0.0            py37h34e0f95_0    anaconda
pip                       19.1.1                   py37_0  
pixman                    0.34.0            h14c3975_1003    conda-forge
plantcv                   3.4.0                      py_0    bioconda
plotnine                  0.3.0                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py-opencv                 3.4.2            py37hb342d67_1  
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py37hd352d35_1    conda-forge
qt                        5.6.3                h8bf5577_3  
readline                  7.0                  h7b6447c_5  
scikit-image              0.14.2           py37hf484d3e_0    conda-forge
scipy                     1.2.1            py37h09a28d5_1    conda-forge
setuptools                41.0.1                   py37_0  
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h7b6447c_0  
sqlparse                  0.3.0                      py_0    conda-forge
statsmodels               0.9.0           py37h3010b51_1000    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
wheel                     0.33.4                   py37_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.9             h516909a_1002    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.0                h3b9ef0a_0    conda-forge
` 

Here is the pip freeze result
`catkin==0.6.16
certifi==2019.6.16
cloudpickle==1.2.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.2.2
decorator==4.4.0
Django==2.2.1
ecto==0.6.11
imageio==2.5.0
kiwisolver==1.1.0
matplotlib==2.2.2
mizani==0.5.4
networkx==2.3
numpy==1.16.4
olefile==0.46
palettable==3.1.1
pandas==0.24.2
patsy==0.5.1
Pillow==6.0.0
plantcv==3.3.0
plotnine==0.3.0
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
scikit-image==0.14.2
scipy==1.2.1
six==1.12.0
sqlparse==0.3.0
statsmodels==0.9.0
toolz==0.9.0
tornado==6.0.2
`

**Comment by AdamDimech** [comment]
Your `pip freeze` shows that you have PlantCV 3.3.0 but the package list in Conda shows that you have PlantCV 3.4.0.  For what it is worth, I have also [observed inconsistencies](https://github.com/danforthcenter/plantcv/issues/401#issuecomment-505275370) between the version that `pip freeze` shows I have and what is actually installed.

**Comment by RavinduDharmasena** [comment]
How can I solve it ?. Is it will be OK if the plantCV is reinstalled in the conda environment ?

**Comment by RavinduDharmasena** [comment]
I installed plantcv to a newly created test environment and still the problem persists in that environment too. Given below is the installation log.

conda install plantcv
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/ravindu/anaconda3/envs/testplantcv

  added / updated specs:
    - plantcv

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    descartes-1.1.0            |             py_3           6 KB  conda-forge
    expat-2.2.5                |    he1b5a44_1003         191 KB  conda-forge
    matplotlib-3.1.0           |           py37_1           6 KB  conda-forge
    matplotlib-base-3.1.0      |   py37hfd891ef_1         6.6 MB  conda-forge
    pillow-6.0.0               |   py37he7afcd5_0         616 KB  conda-forge
    plantcv-3.4.1              |             py_0          91 KB  bioconda
    plotnine-0.5.1             |             py_0         3.0 MB  conda-forge
    pytz-2019.1                |             py_0         227 KB  conda-forge
    scikit-image-0.14.3        |   py37hb3f55d8_0        23.9 MB  conda-forge
    statsmodels-0.10.0         |   py37hc1659b7_0         9.5 MB  conda-forge
    tornado-6.0.3              |   py37h516909a_0         637 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        44.7 MB

The following NEW packages will be INSTALLED:

  cairo              conda-forge/linux-64::cairo-1.14.12-h80bd089_1005
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.1-py_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_1
  cytoolz            conda-forge/linux-64::cytoolz-0.9.0.1-py37h14c3975_1001
  dask-core          conda-forge/noarch::dask-core-1.2.2-py_0
  dbus               pkgs/main/linux-64::dbus-1.13.2-h714fa37_1
  decorator          conda-forge/noarch::decorator-4.4.0-py_0
  descartes          conda-forge/noarch::descartes-1.1.0-py_3
  expat              conda-forge/linux-64::expat-2.2.5-he1b5a44_1003
  ffmpeg             conda-forge/linux-64::ffmpeg-4.0.2-ha0c5888_2
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-he4413a7_1000
  freeglut           conda-forge/linux-64::freeglut-3.0.0-hf484d3e_1005
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.56.2-had28632_1001
  gmp                conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000
  gnutls             conda-forge/linux-64::gnutls-3.5.19-h2a4e5f8_1
  graphite2          conda-forge/linux-64::graphite2-1.3.13-hf484d3e_1000
  gst-plugins-base   pkgs/main/linux-64::gst-plugins-base-1.14.0-hbbd80ab_1
  gstreamer          pkgs/main/linux-64::gstreamer-1.14.0-hb453b48_1
  harfbuzz           conda-forge/linux-64::harfbuzz-1.9.0-he243708_1001
  hdf5               conda-forge/linux-64::hdf5-1.10.2-hc401514_3
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  imageio            conda-forge/linux-64::imageio-2.5.0-py37_0
  jasper             conda-forge/linux-64::jasper-2.0.14-h07fcdf6_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  kiwisolver         conda-forge/linux-64::kiwisolver-1.1.0-py37hc9558a2_0
  libblas            conda-forge/linux-64::libblas-3.8.0-7_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-7_openblas
  libgfortran        conda-forge/linux-64::libgfortran-3.0.0-1
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libglu             conda-forge/linux-64::libglu-9.0.0-hf484d3e_1000
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1005
  liblapack          conda-forge/linux-64::liblapack-3.8.0-7_openblas
  libopencv          pkgs/main/linux-64::libopencv-3.4.2-hb342d67_1
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h57b8799_1003
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.9-h13577e0_0
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  matplotlib         conda-forge/linux-64::matplotlib-3.1.0-py37_1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.1.0-py37hfd891ef_1
  mizani             conda-forge/noarch::mizani-0.5.4-py_0
  nettle             conda-forge/linux-64::nettle-3.3-0
  networkx           conda-forge/noarch::networkx-2.3-py_0
  numpy              conda-forge/linux-64::numpy-1.16.4-py37h95a1406_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openblas           conda-forge/linux-64::openblas-0.3.5-h9ac9557_1001
  openh264           conda-forge/linux-64::openh264-1.8.0-hdbcaa40_1000
  palettable         conda-forge/noarch::palettable-3.1.1-py_0
  pandas             conda-forge/linux-64::pandas-0.24.2-py37hb3f55d8_0
  patsy              conda-forge/noarch::patsy-0.5.1-py_0
  pcre               pkgs/main/linux-64::pcre-8.43-he6710b0_0
  pillow             conda-forge/linux-64::pillow-6.0.0-py37he7afcd5_0
  pixman             conda-forge/linux-64::pixman-0.34.0-h14c3975_1003
  plantcv            bioconda/noarch::plantcv-3.4.1-py_0
  plotnine           conda-forge/noarch::plotnine-0.5.1-py_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  py-opencv          pkgs/main/linux-64::py-opencv-3.4.2-py37hb342d67_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyqt               conda-forge/linux-64::pyqt-5.6.0-py37h13b7fb3_1008
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pytz               conda-forge/noarch::pytz-2019.1-py_0
  pywavelets         conda-forge/linux-64::pywavelets-1.0.3-py37hd352d35_1
  qt                 pkgs/main/linux-64::qt-5.6.3-h8bf5577_3
  scikit-image       conda-forge/linux-64::scikit-image-0.14.3-py37hb3f55d8_0
  scipy              conda-forge/linux-64::scipy-1.2.1-py37h09a28d5_1
  sip                conda-forge/linux-64::sip-4.18.1-py37hf484d3e_1000
  six                conda-forge/linux-64::six-1.12.0-py37_1000
  statsmodels        conda-forge/linux-64::statsmodels-0.10.0-py37hc1659b7_0
  toolz              conda-forge/noarch::toolz-0.9.0-py_1
  tornado            conda-forge/linux-64::tornado-6.0.3-py37h516909a_0
  x264               conda-forge/linux-64::x264-1!152.20180806-h14c3975_0
  xorg-fixesproto    conda-forge/linux-64::xorg-fixesproto-5.0-h14c3975_1002
  xorg-inputproto    conda-forge/linux-64::xorg-inputproto-2.3.2-h14c3975_1002
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.9-h516909a_1004
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.7-h14c3975_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-5.0.3-h516909a_1004
  xorg-libxi         conda-forge/linux-64::xorg-libxi-1.7.10-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  zstd               conda-forge/linux-64::zstd-1.4.0-h3b9ef0a_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
plotnine-0.5.1       | 3.0 MB    | ################################################### | 100% 
statsmodels-0.10.0   | 9.5 MB    | ################################################### | 100% 
plantcv-3.4.1        | 91 KB     | ################################################### | 100% 
matplotlib-base-3.1. | 6.6 MB    | ################################################### | 100% 
expat-2.2.5          | 191 KB    | ################################################### | 100% 
matplotlib-3.1.0     | 6 KB      | ################################################### | 100% 
pillow-6.0.0         | 616 KB    | ################################################### | 100% 
pytz-2019.1          | 227 KB    | ################################################### | 100% 
scikit-image-0.14.3  | 23.9 MB   | ################################################### | 100% 
descartes-1.1.0      | 6 KB      | ################################################### | 100% 
tornado-6.0.3        | 637 KB    | ################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by nfahlgren** [comment]
Hi @RavinduDharmasena, like with what @AdamDimech is seeing I am thinking the older version is hanging out somewhere unexpected or side-by-side with the new version somehow. Could you run this in your conda environment (either command-line python prompt or in Jupyter)?

```bash
from plantcv import plantcv as pcv
print(pcv.__version__)
print(pcv.__file__)
```

The first print will tell us if the importer is grabbing 3.4.0 or 3.4.1. The second print will tell us the file path to where the importer is grabbing the package.

**Comment by RavinduDharmasena** [comment]
@nfahlgren This is the output I get when the above codes are executed in python terminal. Entire terminal code is given below.
(research_dss) ravindu@ravindu-Samsung-DeskTop-System:~$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from plantcv import plantcv as pcv
>>> print(pcv.__version__)
3.4.0
>>> print(pcv.__file__)
/home/ravindu/anaconda3/envs/research_dss/lib/python3.7/site-packages/plantcv/plantcv/__init__.py

**Comment by nfahlgren** [comment]
I think I see the issue. When you execute your script directly (as opposed to doing `python nir_analysis-NEW.py`) it executes using the Python defined in the first line: `#!/usr/bin/python`. Rather than specifying `/usr/bin/python` directly (this is the system Python that has it's own library path), you can change this line to be responsive to your conda environments: `#!/usr/bin/env python`.

**Comment by RavinduDharmasena** [comment]
@nfahlgren, Thank you for pointing out the mistake. Now the plantCV is working fine.
