### ISSUE TITLE
Scaling images of different camera distance + top-view photos

### ISSUE THREAD

**Issue by scsolano** [danforthcenter/plantcv#413]
### Description

 Hello all! First and foremost, thank you all for helping me throughout these last few weeks with getting some issues resolved, I am now able to build a pipeline that gets pixel volume of a plant efficiently 

However I still have a concern with my dataset rather than the pipeline. As I took photos of sunflowers, they grew throughout the experiment. In the first few weeks, I needed to position the camera close to the plants as they weren't as tall and I needed as much of the plant as possible to be seen. And as the weeks passed by, they grew tall enough such that I needed to reposition the camera to get the full plant. 

 Of course, this resulted in the issue where pixel volume of some plants was "inflated", meaning that a small plant and a large plant could have the same pixel volume (more or less) because of their perceived size in the image due to different camera positions. My new issue is establishing some sort of scale to address that issue to create a pipeline that works for all images no matter the distance of the plant from the camera

 I see in the documentation that there are scaling features, however the parameters for the scale features are about pot height which isn't really prominent in some photos where I only have a slight edge of the top of the pot, as well as photos taken from the top 
 
 Therefore, I would need to base parameters on something like pot width/diameter. So I have two issues

 1. How would I implement a scale to deal with images where plants are at different distances from the camera by using pot width/diameter?
 2. How would I implement that same pipeline to images from the top (or would I need to create an entirely separate pipeline for plant images taken from the top?)

For reference, I'll post three photos of plants - two of which are plants where I had to position the camera at different distances and one image of a plant taken from above.

 Thank you in advance!

 Pictures at different camera distances:
 
 
![109_90_4](https://user-images.githubusercontent.com/49666313/60359930-6d5ede00-99a8-11e9-86b5-c710d0abb9ac.JPG)

![105_180_3](https://user-images.githubusercontent.com/49666313/60359950-7d76bd80-99a8-11e9-986c-0b01cb77180c.JPG)

 Picture from the top view:

![105_top_3](https://user-images.githubusercontent.com/49666313/60359971-8b2c4300-99a8-11e9-920e-a867073a2e9e.JPG)

**Comment by HaleySchuhl** [comment]
Hi @scsolano ,

PlantCV has a function meant for this exact thing! The function `pcv.report_size_marker` (https://plantcv.readthedocs.io/en/latest/report_size_marker/)  can detect/input a size marker, like the red tough spots in your images, and calculate the size of one of these. This area gets stored automatically to the `Outputs` class for each image so you can scale for size data during data analysis based on how far the plant is from the camera.

**Comment by scsolano** [comment]
I see, so I would likely have to have different inputs for report_size_marker throughout the dataset then, thus I'd have to divide the dataset based on distances I suppose? Thank you!

**Comment by scsolano** [comment]
I see, so I would likely have to put different inputs on report_size_marker based on the sticker's distance to the plant (since it didn't always stay consistent as the background was moved every now and then). It is consistent across several sets of photos but not the entire dataset, so I suppose my best bet would be to divide up the dataset then? 

Thanks for the response!

**Comment by HaleySchuhl** [comment]
Feel free to reopen this issue with any addition questions, comments, or suggestions.
