### ISSUE TITLE
Cannot obtain image output from morphological functions

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#414]
I have developed a very [simple script](https://gist.github.com/AdamDimech/9efeaa41bda51e2fc2df0b07bb3d5e96) to run a morphological analysis on some of my images, which I want to eventually incorporate into my general VIS pipeline.

Unfortunately I can't output any of the images from this pipeline. Images work in [Jupyter Notebook](https://gist.github.com/AdamDimech/6350555c5e755ed46832e1e7747bdb7b) but not in the final python script. In particular I would like to obtain the "tips" image.

The [tutorial](https://plantcv.readthedocs.io/en/latest/morphology_tutorial/) shows how to use the morphological analyses but not how to extract the image data which would be valuable. I tried @HaleySchuhl's [trick](https://github.com/danforthcenter/plantcv/issues/391#issuecomment-504448763) but it didn't return an image:

`pcv.print_image(img=tip_pts_mask[0], filename=args.outdir + "/Tips-" + filename)`

I also tried this which also didn't work:

`tips = pcv.analyze_object(tip_pts_mask, leaf_obj, cropped_mask)`
`pcv.print_image(img=tips[0], filename=args.outdir + "/Tips-" + filename)`

I am guessing that `pcv.analyze_object` is incorrect but can't find any example of what I should be using.

**Comment by nfahlgren** [comment]
Hi @AdamDimech,

`tip_pts_mask` is a single binary image (Figure 9 in the tutorial) with the tip points/pixels labeled white and everything else labeled black. You can save it as you were doing but without the `[0]`:

```python
pcv.print_image(img=tip_pts_mask, filename=args.outdir + "/Tips-" + filename)
```

Are you looking to save the version with the skeleton and the tips labeled green (Figure 10 in the tutorial) though?

**Comment by AdamDimech** [comment]
Thanks @nfahlgren. Yes, I would like to save the version with the skeleton and the tip points marked. That would be very useful whilst I check and optimise my workflows. Can this be done?

**Comment by nfahlgren** [comment]
Hi @AdamDimech, it's possibly not ideal, but if you set `pcv.params.debug = "print"` prior to running `pcv.morphology.find_tips` it should save the tips image to `pcv.params.debug_outdir`. The only issue with that is that the name of the output image won't be unique from input image to input image. If the directory passed to `--outdir` is unique then that won't be a problem, otherwise you could create a unique output directory for each image using something like:

```python
# Save debug image in unique folder per input image
saved_imgs_dir = os.path.join(pcv.params.debug_outdir, filename)
# If the directory does not exist, make it
if not os.path.exists(saved_imgs_dir):
    os.mkdir(saved_imgs_dir)
# Set the debug_outdir directory to the unique output directory path
pcv.params.debug_outdir = saved_imgs_dir
```

We can definitely look at the plotting size and color ideas!

**Comment by HaleySchuhl** [comment]
Feel free to reopen with any additional comments/suggestions/questions!
