### ISSUE TITLE
parallel pipeline image format

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#424]
Is there a technical reason that plantcv-workflow.py only accepts png and jpg? I have a lot of .tif files that work fine with plantcv otherwise.

are there any benefits to .png to .jpg to .tif? I've always thought/assumed that .tif preserved the data best and .jpg had high compression. .png is nice because git will diff it :) but I assume (for no good reason) it's a lossy format. Maybe I should switch to png? is it just a different container for the same data?

**Comment by HaleySchuhl** [comment]
It should be able to handle .tif! In the documentation we give the example of .jpg but users should be able to specify any file extension in --type so long as `cv2.imread` can open it.

**Comment by nfahlgren** [comment]
Yeah, the online documentation does sort of suggest that the only options are `png` and `jpg` but it should accept any file extension in principle.

**Comment by dschneiderch** [comment]
ok, it looks like it works with .tif. 
one of my troubleshooting steps was to change to png because of the docs but i guess that wasn't actually the source of my previous errors.

**Comment by nfahlgren** [comment]
One other note from above. I don't necessarily think there is an advantage to TIF vs PNG (that I know of). But PNG is a lossless compression. I do generally avoid JPG when possible since it uses lossy compression.

**Comment by dschneiderch** [comment]
well then png it should be. seeing .png differences from multiple iterations of making a mask is super cool!
The only downside I've found to .png is that opencv will only write unsigned integers to png. Fine for sensor data, but not as convenient for Fv/Fm for example.

**Comment by nfahlgren** [comment]
Ah I see, TIF can be float? Maybe we could intentionally output float-type data as TIF then, would potentially be convenient for thermal image data.

**Comment by dschneiderch** [comment]
It can be 32bit float. https://docs.opencv.org/3.4.6/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce

When I process my PSII images, I always start with Fv/Fm and then use imwrite for Fv/Fm and Fm as output so I use them later when calculating other PSII parameters.

So, writing temp files might be another solution to act as coprocess files.

**Comment by dschneiderch** [comment]
I was going to up date the documentationfor pipeline_parallel.md for the image format. 
I was also going to update  the example for flat file directory because I don't think this will actually run because of the date.

```
AABA002948-2014-03-14 03_29_45-Pilot_031014-VIS_TV_z3500.png

1. Plant ID = AABA002948
2. Timestamp = 2014-03-14 03_29_45
3. Measurement Label = Pilot_031014
4. Camera Label = VIS_TV_z3500
```

SHould I just change it to something like this?
```
AABA002948_2014-03-14-03-29-45_Pilot-031014_VIS_TV_z3500.png
```

**Comment by HaleySchuhl** [comment]
On my branch I updated it to the following:
```
**Example Name:**

AABA002948_2014-03-14 03-29-45_Pilot-031014_VIS_TV_z3500.png

1. Plant ID = AABA002948
2. Timestamp = 2014-03-14 03-29-45
3. Measurement Label = Pilot-031014
4. Image Type = VIS
5. Camera Label = TV
6. Zoom = z3500
```

I also added the list of valid metadata to the parallelization docs page.

**Comment by HaleySchuhl** [comment]
I believe everything has been addressed in this issue. Feel free to reopen with any additional comments!
