### ISSUE TITLE
Kernels with arrays of 1's and 0's

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#427]
I am trying to use the [Closing](https://plantcv.readthedocs.io/en/stable/closing/) function, where `kernel` is listed as an optional parameter "(an) optional neighbourhood, expressed as an array of 1's and 0's."

How do I code this?

I cannot find an example code where the array of 1's and 0's is used. I have tried various combinations of curly and normal brackets, commas, no commas etc etc and all end in an error of some sort.

For example, this fails: `closed = pcv.closing(image, kernel=[0, 1, 0, 1, 1, 1, 0, 1, 0])`

I want to use the following kernel:

`0 1 0`
`1 1 1`
`0 1 0`

**Comment by nfahlgren** [comment]
Hi @AdamDimech, you just about have it right but the kernel needs to be a NumPy array:

```closed = pcv.closing(image, kernel=np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]]))```

We should definitely add an example in the docs.

**Comment by AdamDimech** [comment]
Thanks @nfahlgren.

Is there a more generic/easy way to specify these kernels (for example, 11 x 11) where all the entries are 1?

Does this mean the speed of a closing is proportional to kernel size? I ask this because I envisage large filtering with say a thousand by thousand kernel. Can an area opening be performed?

**Comment by nfahlgren** [comment]
You can use np.ones or np.zeros to fill out arrays:

```kernel = np.ones(shape=[11, 11])```

The kernel size will affect how fine or granular the transformation is. I think larger kernels will be faster because the kernel is scanned across the image, but smaller kernels will result in finer scale transformation. 

For this function the kernel size (and the shape of the pattern in it) will affect the size of holes that can be filled. If you make it really really big I'm not sure what would happen but it might fill in much more than you want.

**Comment by AdamDimech** [comment]
Hi @nfahlgren 

Since posting this question, I have found a method in [OpenCV](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html#structuring-element) that works in PlantCV to specify kernels of various shapes:

**Rectangular kernel 11×11**
`cv2.getStructuringElement(cv2.MORPH_RECT,(11,11))`

**Elliptical kernel 11×11**
`cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(11,11))`

**Cross kernel 11×11**
`cv2.getStructuringElement(cv2.MORPH_CROSS,(11,11))`

The code isn't elegant (and a neat PlantCV function for this would be great) but it does the job without having to manually code large and complex kernels.

**Comment by HaleySchuhl** [comment]
Thanks for the suggestion @AdamDimech !

We're adding a PlantCV function to create these different structuring elements and an example in the documentation for `pcv.opening` and `pcv.closing`.
