### ISSUE TITLE
update bioconda

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#432]
Not sure what your timeline is but it would be great if bioconda got updated with bug fixes, maybe 3.5.1

I just spent half a day tracking down a bug that you fixed 2 days after releasing 3.5. 3.5 was released >1 mo ago so a bug fix release would be warranted.

I'd like avoid guiding users through installing the dev version if possible....

**Comment by nfahlgren** [comment]
We're going to merge the two PRs you created today and Haley is adding one more, but we should be able to trigger the new release shortly. Bioconda is now automatically generating PRs when it detects new versions on PyPI so by tomorrow it should be updated on Bioconda.
