### ISSUE TITLE
PlantCV v2.0 license

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#44]
Thoughts on converting to an MIT license instead of GPLv2?

**Comment by jshoyer** [comment]
I do not think it really matters, but I would vote for the BSD license, based Section 3.8 [here](http://fossil-scm.org/index.html/doc/trunk/www/fossil-v-git.wiki). Perhaps that would involve too much paperwork to be worthwhile. OpenCV is released under a BSD license, for what it is worth.

**Comment by nfahlgren** [comment]
It looks like BSD and MIT are interchangable as far as what they cover: http://choosealicense.com/appendix/
