### ISSUE TITLE
Read ENVI hyperspectral images

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#441]
**Describe the solution you'd like**
We will add a new method for reading images files to support ENVI-type hyperspectral data. Our plan is to use the BIL filename as input and automatically find the associated ENVI header file (we will assume it is in the same directory and has a `.hdr` extension.

The function will need to read the ENVI header file (a text file) to extract image information such as the image dimensions (samples = width, lines = height, bands = wavelengths/channels) and the image format (data type = bit depth/numerical format, interleave = BIL, BIP, BSQ).

We also need to keep track of the wavelength labels.

Our plan is to use numpy.fromfile (https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromfile.html) to read the raw image data. Then we need to reshape the interleaved data correctly using the row, column, band ordering described here: https://gis.stackexchange.com/questions/313914/read-aviris-data-with-python

**Additional context**
The ENVI header format is documented here: https://opticks.org/docs/help/4.3.1/Help/Opticks/Content/Importers_Exporters/ENVI_Header_Format.htm

**Comment by dschneiderch** [comment]
Why not include gdal as a dependency and use its functions for reading ENVI (and hundreds of other formats)?

**Comment by nfahlgren** [comment]
GDAL is a pretty heavy dependency, you have to install the C/C++ system libraries outside of Python in order to use the Python package.

**Comment by dschneiderch** [comment]
I’ve found it to be pretty straightforward with conda but from source it can be a PIA.

**Comment by nfahlgren** [comment]
Same here. The system libraries are pretty easy to install with Linux package managers in general, but if anyone is installing through PyPI they have to either install from source or a package manager upfront.

Could be worth going down that route at some point, but at least for ENVI files, reading them in with NumPy and a simple header file parser is only ~10 lines of code. What we are not sure about yet is how many formats we are realistically going to encounter. I do think if users end up having many different file types it's going to be better to use an established library like GDAL rather than reinventing parsers for many different types.

Thoughts?

**Comment by dschneiderch** [comment]
> What we are not sure about yet is how many formats we are realistically going to encounter. 

That is the crux of the situation :-)

I suggested GDAL so you wouldn't have to worry about supporting every additional file format but maybe it's overkill for plant phenomics. it is mostly pretty basic image formats (tif/png/jpg) with the addition of ENVI (anything else ?- some hyperspectral company might implement an hdf5 format?) for hyperspectral and ply/las (others?) for point cloud data. if you start getting a lot of field phenomics users then georeferencing support will become important.

**Comment by dschneiderch** [comment]
also, xarray does not require gdal for general use (which i thought it might) in case you're planning to go that route within plantcv.

**Comment by nfahlgren** [comment]
xarray might be a cool way to store the hyperspectral data cubes. We want to be able to refer to the bands/channels by wavelength labels, as opposed to their index number, and it looks like that's exactly what xarray achieves: http://xarray.pydata.org/en/stable/data-structures.html

**Comment by dschneiderch** [comment]
Yep, seems to be becoming the defacto standard in geo and climate sciences for n-dimensional data analysis in python. Just need to make sure the metadata is good. That's where using the native ENVI driver might come in handy if the attributes are correctly encoded.

**Comment by HaleySchuhl** [comment]
Closed in #464

**Comment by mohitlomash** [comment]
Hi there. is this new version available now? I tried to open my .bil and .hdr file. i did not found anything which supports this file format in ENVI software. Can you please guide me. Thank You.

**Comment by HaleySchuhl** [comment]
Hi @mohitlomash thanks for reaching out.

We support at least one type of `.bil` dataformat, and have a test image  here (GitHub/plantcv/tests/testdata/darkReference). However, it's very likely that your image format is novel to PlantCV and would require some updating to support this format. Are you willing and able to share the image & corresponding .hdr you are trying to read in?
