### ISSUE TITLE
Update saved NumPy test data

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#447]
**Is your feature request related to a problem? Please describe.**
When we update to NumPy 1.17+ we will need to recreate the NPZ files in our test data because of changes in the way NumPy reads these data objects: https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html.

**Describe the solution you'd like**
We will need to recreate our NPZ files, presumably without using the pickle module, to build new saved data that can be read by `numpy.load` in v1.17+.

We also want to use this as an opportunity to build some notebooks for our test data so that we can more easily rebuild test datasets in the future.

**Describe alternatives you've considered**
For the short term we are blocking NumPy 1.17 in our dependency list.

**Comment by bganglia** [comment]
@nfahlgren 

It looks like in some cases, the problem is that multiple arrays of different sizes are being saved as elements in a single Numpy array, instead of separate arrays within the npz file. I think I know how to fix this.

I can try to update these files (and the code that opens them), but this will still leave building notebooks for the data.

**Comment by nfahlgren** [comment]
Sounds great!

**Comment by bganglia** [comment]
@nfahlgren 

It looks like these files affect quite a few functions in /plantcv/tests/tests.py, so I will probably break this PR up into a few parts.

I will try to tackle a couple of the functions from the last column of this table in each part.

| npz file                    | variable name used            | functions affected
|-----------------------------|-------------------------------|---------------------------------------------
| clusters_i_visualize.npz    | TEST_INPUT_VISUALIZE_CLUSTERS | test_plantcv_visualize_clustered_contours
| roi_objects_visualize.npz | TEST_INPUT_VISUALIZE_CONTOUR  | test_plantcv_visualize_clustered_contours
| multi_contours.npz        | TEST_INPUT_MULTI_CONTOUR      | test_plantcv_cluster_contours_splitting   
| roi_objects.npz           | TEST_INPUT_MULTI_OBJECT       | test_plantcv_cluster_contours,<br>test_plantcv_cluster_contours_grayscale_input,<br>test_plantcv_auto_crop,<br>test_plantcv_auto_crop_grayscale_input,<br>test_plantcv_auto_crop_bad_input
| multi_contours.npz        | TEST_INPUT_MULTI_CONTOUR      | test_plantcv_cluster_contours_splitting
| skeleton_objects.npz      | TEST_SKELETON_OBJECTS         | test_plantcv_morphology_segment_tangent_angles,<br>test_plantcv_morphology_segment_id,
| input_roi.npz             | TEST_INPUT_ROI                | test_plantcv_roi_objects,<br>test_plantcv_roi_objects_bad_input,<br>test_plantcv_roi_objects_grayscale_input,
| clusters_i.npz            | TEST_INPUT_CLUSTER_CONTOUR    | test_plantcv_cluster_conotours_splitting,
| input_contours1.npz       | TEST_INPUT_CONTOURS1          | test_plantcv_object_composition,<br>test_plantcv_object_composition_grayscale_input,<br>test_plantcv_roi_objects,<br>test_plantcv_roi_objects_bad_input
