### ISSUE TITLE
'match' multiple values of same metadata field

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#461]
**Is your feature request related to a problem? Please describe.**
It would be great if I could specify multiple values to match for the same metadata field key. This is another way to subset the images to test the workflow on more than a couple images.

**Describe the solution you'd like**
```
python %CONDA_PREFIX%/Scripts/plantcv-workflow.py --workflow vis.py ^
    --dir data/testimages/vis ^
    --type png ^
    --outdir output ^
    --json results.json ^
    --adaptor filename ^
    --delimiter - ^
    --meta plantbarcode-measurementlabel-timestamp-camera ^
    -T 4 ^
    --create ^
    --other_args="--debugdir debug-images" ^
    --match plantbarcode:A1,plantbarcode:B2,plantbarcode:C3
```

It would be particularly handy to filter the dates this way so I could run the first day and last day.

**Describe alternatives you've considered**
- an alternative image directory that has a subset of files
- run workflow multiple times with different match arguments

**Additional context**
plantcv-utils.py sample_images  could potentially be used as an intermediary if you could sample based on group. same idea as previously discussed with groups and maps.

**Comment by bganglia** [comment]
@HaleySchuhl I can work on this.
