### ISSUE TITLE
save ROIs as separate entities

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#462]
**Describe the bug**
When I run a workflow in parallel, I only get one value per image even though there are two ROI. [summary of output emasurements](https://plantcv.readthedocs.io/en/stable/output_measurements/) suggests an entity can be a region of an image.  I tried adding the roi as an observation to `outputs` but it only keeps roi 1 (of 0,1).

**To Reproduce**

relevant code:
```
    c,h = pcv.find_objects(img,mask)
    rc, rh = pcv.roi.multi(img, coord = [(1250,900),(1250,2400)], radius = 450)
    print(fn)
    for i, rc_i in enumerate(rc):
        rh_i = rh[i]
        try:
            roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=rc_i,
                                                                                roi_hierarchy=rh_i,
                                                                                object_contour=c,
                                                                                obj_hierarchy=h,
                                                                                roi_type='partial')
        except RuntimeError as err:
            print('!!!!',err,str(i))
        else:
            object, mask = pcv.object_composition(img, roi_objects, roi_obj_hierarchy)
            shape_img = pcv.analyze_object(img, object, mask)
            pcv.outputs.add_observation(
                variable='roi',
                trait='roi',
                method='roi',
                scale='int',
                datatype=int,
                value=i,
                label='#')

    # Write shape and color data to results file
    pcv.print_results(filename=args.result)
```

**Expected behavior**
I was expecting an entity for each roi in each image.  If this is possible, an example would be great! Thanks!

**Local environment (please complete the following information):**
 Windows 10, bioconda plantcv 3.6

**Comment by HaleySchuhl** [comment]
Hi @dschneiderch ,

I am totally on board! After PlantCV 3 the plan is to use classes to make it MUCH easier to have multiple entities per image, rather than working on the assumption that there is one plant per image. We want to remove as much programming as possible, so the plan is to have each `analyze_*` function handle multiple entities without writing any loops or anything. 

For now, you need to write the data out after each entity in analyzed, and clear outputs by using `outputs.clear()` before running `analyze_object` again. The dictionary structure makes it so variables need to be unique otherwise they just get replaced. Again, will be easier with some updates to how we handle multiple entities per object!

**Comment by dschneiderch** [comment]
is this what you meant? it didn't affect my output though.
```
    c,h = pcv.find_objects(img,mask)
    rc, rh = pcv.roi.multi(img, coord = [(1250,900),(1250,2400)], radius = 450)
    print(fn)
    for i, rc_i in enumerate(rc):
        rh_i = rh[i]
        try:
            roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=rc_i,
                                                                                roi_hierarchy=rh_i,
                                                                                object_contour=c,
                                                                                obj_hierarchy=h,
                                                                                roi_type='partial')
        except RuntimeError as err:
            print('!!!!',err,str(i))
        else:
            object, mask = pcv.object_composition(img, roi_objects, roi_obj_hierarchy)
            shape_img = pcv.analyze_object(img, object, mask)
            pcv.outputs.add_observation(
                variable='roi',
                trait='roi',
                method='roi',
                scale='int',
                datatype=int,
                value=i,
                label='#')

        # Write shape and data to results file
        pcv.print_results(filename=args.result)
        pcv.outputs.clear()
```

**Comment by HaleySchuhl** [comment]
To keep the output data from getting overwritten the results file needs to be unique. 

```
# Write shape and data to results file
    result_filename = args.result + str(i)
    pcv.print_results(filename=result_filename)
    pcv.outputs.clear()
```
Does this give you the desired results? @nfahlgren can correct me if I'm wrong, but recording the same observations multiple times per output file appears to overwrite the first instance of that observation due to the dictionary format.

**Comment by dschneiderch** [comment]
that does not work.  
I think plantcv-utils can't find imagefile.png.txt1, imagefile.png.txt0. also, imagefile.png.txt also exists but returns no observations.

I changed the naming so it could find the text file:
```
basename, ext = os.path.splitext(args.result)
result_filename = basename + str(i) + ext
pcv.print_results(filename=result_filename)
pcv.outputs.clear()
```

but now all the metadata is cleared for the 0,1 files, the original  .txt file has no observations, and the resultant csv looks like this:

```csv
camera,imgtype,zoom,exposure,gain,frame,lifter,timestamp,id,plantbarcode,treatment,cartag,measurementlabel,other,image,in_bounds,area,convex_hull_area,solidity,perimeter,width,height,longest_path,convex_hull_vertices,object_in_frame,ellipse_major_axis,ellipse_minor_axis,ellipse_angle,ellipse_eccentricity,roi
VIS0,none,none,none,none,none,none,20190715T161102,none,A3,none,none,GoldStandard2_RGB,none,data/raw_snapshots/vis\A3-GoldStandard2_RGB-20190715T161102-VIS0.png,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,True,144146.0,290002.0,0.4970517444707278,6472.497392177582,589,726,7878,35,True,628.0012817382812,482.2403564453125,164.3201904296875,0.6405732276224794,0
NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,True,192560.0,388279.0,0.49593204886177206,6500.435364723206,732,700,5199,38,True,688.16650390625,573.1627807617188,59.96556854248047,0.5534477930364211,1
VIS0,none,none,none,none,none,none,20190718T161027,none,A3,none,none,GoldStandard2_RGB,none,data/raw_snapshots/vis\A3-GoldStandard2_RGB-20190718T161027-VIS0.png,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,True,234950.0,376761.5,0.6236040572086055,5367.0237814188,735,745,5094,52,True,697.149169921875,595.7699584960938,121.57115173339844,0.5193192487476924,0
NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,True,357121.0,616483.0,0.579287668921933,7431.884436130524,936,925,10424,45,True,819.6633911132812,789.1626586914062,173.1463623046875,0.270255250711892,1
```

**Comment by nfahlgren** [comment]
Hi @dschneiderch,

Until we can implement the changes @HaleySchuhl mentioned, saving the data for each plant/object can be done but takes a bit of work in the user workflow script. When `plantcv-workflow.py` is run, it creates a results file for each image that gets analyzed (these are the temporary JSON files in the timestamped directory). That file is input to the user's workflow script. What we need to do is read the contents of that file into memory (it's the image metadata at this point), then delete that file. Then in your for loop, for each ROI, we create a new results file with the metadata from the original and print results for that plant to it. Then finally, clear the outputs and repeat for each ROI. When `plantcv-workflow.py` gets to the final processing results phase, it will read all these back in and combine them into the final output.

Here's a full example of this working: https://nbviewer.jupyter.org/github/nfahlgren/shared_jupyter_notebooks/blob/master/arabidopsis-multiplant.ipynb

**Comment by dschneiderch** [comment]
Makes sense. Thanks for showing the way.

Two small changes to your notebook were needed:

  1.
Filename = str(i) + “_” + args.result  causes an error because it tries to append the roi # in front of the timestamped directory:
'0_2019-10-14_16-32-50\\A3-GoldStandard2_RGB-20190718T161027-VIS0.png.txt'

2.

Checking for obj_area > 0 doesn’t work well because pcv.roi_objects() throws an error if no plant is detected.
Instead of:
  # Only proceed if a plant was detected
    if obj_area > 0:
I’ve been using
try:
            roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=rc_i,
                                                                                roi_hierarchy=rh_i,
                                                                                object_contour=c,
                                                                                obj_hierarchy=h,
                                                                                roi_type='partial')
        except RuntimeError as err:
            print('!!!!',err,str(i))
        else:
            object, mask = pcv.object_composition(img, roi_objects, roi_obj_hierarchy)
            shape_img = pcv.analyze_object(img, object, mask)
            pcv.outputs.add_observation(
                variable='roi',
                trait='roi',
                method='roi',
                scale='int',
                datatype=int,
                value=i,
                label='#')

**Comment by nfahlgren** [comment]
Oh yeah, oops. In my example I didn't have a directory path.

**Comment by dschneiderch** [comment]
oh, looks like the error message in `roi_objects()` was removed a month ago
