### ISSUE TITLE
plantcv-workflow fails silently with mismatched meta and delimiter arguments

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#477]
**Describe the bug**
If you incorrectly parse the filename or provide the wrong meta_fields the program will fail silently.

**To Reproduce**
I discovered in this test:
```
def test_plantcv_parallel_metadata_parser_images_outside_daterange():
    data_dir = os.path.join(PARALLEL_TEST_DATA, TEST_IMG_DIR2)
    meta_filters = {"imgtype": "NIR"}
    start_date = 10
    end_date = 10
    date_format = "%Y%m%d"
    meta_fields = {"imgtype": 0, "camera": 1, "frame": 2, "zoom": 3, "lifter": 4, "gain": 5, "exposure": 6,
                   "timestamp": 7}
    error_log = open(os.path.join(TEST_TMPDIR, "error.log"), 'w')
    jobcount, meta = plantcv.parallel.metadata_parser(data_dir=data_dir, meta_fields=meta_fields,
                                                      valid_meta=VALID_META, meta_filters=meta_filters,date_format=date_format,
                                                      start_date=start_date, end_date=end_date, error_log=error_log,
                                                      delimiter="_", file_type="jpg", coprocess=None)
    assert meta == {}
```
where the filename is `tests\parallel_data\images_w_date\NIR_SV_0_z1_h1_g0_e65_2014-03-14 03_29_45.jpg`
if you split it with `_`
```
filename = 'NIR_SV_0_z1_h1_g0_e65_2014-03-14 03_29_45.jpg'
filename.split('_')
['NIR', 'SV', '0', 'z1', 'h1', 'g0', 'e65', '2014-03-14 03', '29', '45.jpg']
```
you get more than 7 parts, so in `metadata_parser()` `meta` is returned as `{}` because
```
metadata = _parse_filename(filename=prefix, delimiter=delimiter, regex=regex)
# Not all images in a directory may have the same metadata structure only keep those that do
if len(metadata) == meta_count:
```

I realize it's being used to separate files we want and don't want, but maybe there is something defensive that can be done here?

**Comment by HaleySchuhl** [comment]
@dschneiderch ,

I believe this is acting as intended. When it's separating files not only do we filter by matching expected metadata but also by the number of metadata fields in targeted images. The assumption is that an image with the incorrect number of metadata fields is not targeted by a workflow.

**Comment by dschneiderch** [comment]
Yea, it's one of those feature bugs :-)

It just was very confusing to me, but mostly because I wasn't that super familiar with the filename of the test image. I think in practice the problem would be more evident to the user.

I guess a simple warning in plantcv-workflow.py if 0 images are included for analysis could help steer someone in the right direction.
