### ISSUE TITLE
Clean seeds 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#488]
Hi there,

I'm testing my workflow for seed size on a test image of my seed (rice).
I modified a bit the script and I was able to fill in just the rice seeds and not the awns, which will avoid to clean the seed before the phenotyping. 

However, when I colored the seeds (objects) differently (a step right before the for loop for analyzing each seed separately), I noticed that some pixels of one seed are colored differently (you can notice them by zooming in), and are considered as different objects. Therefore, they are analyzed separately from the analyze_objects function.
I guess this is related to the variability of colors in each seed. 

The first solution that I thought was to fill objects with an area included in a specific interval, not just smaller than a certain number. Is there a way to do it in PlantCV? 

I'm attaching the commands and the images
[rice_Test_EpsonV600.zip](https://github.com/danforthcenter/plantcv/files/3795797/rice_Test_EpsonV600.zip)
.
```
args = options()
pcv.params.debug = args.debug

#let's safe the args.directory so that we can go back anytime:
originalDir = os.getcwd()

#read in image
img, imgpath, imgname = pcv.readimage(filename=args.image)

mask, masked_img = pcv.threshold.custom_range(rgb_img=img1, lower_thresh=[0,0,155], upper_thresh=[255,255,255], channel='LAB')

fill_image = pcv.fill(mask, 200) 
id_objects, obj_hierarchy = pcv.find_objects(img, fill_image)

roi1, roi_hierarchy= pcv.roi.rectangle(img=img1, x=150, y=800, h=2250, w=2250)
roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi1, roi_hierarchy=roi_hierarchy, object_contour=id_objects, 
                                                                      obj_hierarchy=obj_hierarchy, roi_type='partial')

# Randomly colors the individual seeds
img_copy = np.copy(img)
for i in range(0, len(roi_objects)):
    rand_color = pcv.color_palette(1)
    cv2.drawContours(img_copy, roi_objects, i, rand_color[0], -1, lineType=8, hierarchy=roi_obj_hierarchy)
image_name = extractName(args.image) + "_seedColors.jpg"
pcv.print_image(img_copy, image_name)#save the picture
pcv.outputs.clear()
```
_Originally posted by @amarrano in https://github.com/danforthcenter/plantcv/issues/466#issuecomment-548566491_

**Comment by HaleySchuhl** [comment]
The fill step should be good at filling in salt noise in a binary image. There isn't a PlantCV function to just fill objects within a certain range but this is definitely doable!

fill_image = pcv.fill(mask, 200)
id_objects, obj_hierarchy = pcv.find_objects(img, fill_image)

#####
# Insert this to delete objects between 500 and 800 pixels in size.
for seed in id_objects:
    if len(seed)>500 and len(seed)<800:
        id_objects.remove(seed)
#####

roi1, roi_hierarchy= pcv.roi.rectangle(img=img1, x=150, y=800, h=2250, w=2250)
image
^
In this case I think that the way to address this is to do a flood fill. When you color each contour it ignores hierarchy so it will color child contours differently than parent contours. However, you can mostly avoid this and keep from losing this projected area if you use either dilation or flood fill

image
^
I would also suggest trying out erosion to help clean the seed images too. I saw in one image that you attached that two of the seeds were slightly touching but you could likely erode a little to separate the two seeds.

**Comment by amarrano** [comment]
Thanks @HaleySchuhl. I used the fill_holes function and it filled the entire rice kernel, without coloring differently the child contours. However, when I still have some area of the awns colored that I want to cut off. 

I followed your suggestions but I got this error:

fill_image = pcv.fill_holes(mask)   
id_objects, obj_hierarchy = pcv.find_objects(img1, fill_image)
for seed in id_objects:
    if len(seed) < 100:
        id_objects.remove(seed)


/home/amarrano/.local/lib/python2.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-475-0f59d0ec78a7> in <module>()
      1 for seed in id_objects:
      2     if len(seed) < 100:
----> 3         id_objects.remove(seed)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by HaleySchuhl** [comment]
Hi @amarrano ,

I've been able to replicate this on the image you've provided. It seems like removing objects from the list that's being iterated through is doing funky stuff. I tweaked the code and got rid of the ValueError. I also realized this alternative I suggested to `pcv.fill` is neglecting the hierarchies bit. I modified your code to the workflow below and found it works well on your image. 

```

args = options()
pcv.params.debug = args.debug

#let's safe the args.directory so that we can go back anytime:
originalDir = os.getcwd()

#read in image
img, imgpath, imgname = pcv.readimage(filename=args.image)

mask, masked_img = pcv.threshold.custom_range(rgb_img=img1, lower_thresh=[0,0,155], upper_thresh=[255,255,255], channel='LAB')

# Fill in holes and salt noise in the mask 
fill_image = pcv.fill_holes(mask)
fill_image = pcv.fill(fill_image, 100)

# Use erode and dilate to separate seeds that are close to one another
eroded_mask = pcv.erode(fill_image, ksize=8, i=1)
dil_mask = pcv.dilate(eroded_mask, ksize=5, i=1)

id_objects, obj_hierarchy = pcv.find_objects(img, dil_mask)

# Make copy of the contours 
id_objects2 = id_objects.copy()

# Sort through and remove those specified 
for i, seed in enumerate(id_objects):
    if len(seed)<100:
        id_objects2.remove(seed)
        obj_hierarchy.remove(obj_hierarchy[i])

roi1, roi_hierarchy= pcv.roi.rectangle(img=img, x=150, y=800, h=2250, w=2250)

roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, 
                                                                      roi_contour=roi1, 
                                                                      roi_hierarchy=roi_hierarchy, 
                                                                      object_contour=id_objects,
                                                                      obj_hierarchy=obj_hierarchy, 
                                                                      roi_type='partial')

img_copy = np.copy(img)
for i in range(0, len(roi_objects)):
    rand_color = pcv.color_palette(1)
    cv2.drawContours(img_copy, roi_objects, i, rand_color[0], -1, lineType=8, hierarchy=roi_obj_hierarchy)

image_name = extractName(args.image) + "_seedColors.jpg"
pcv.print_image(img_copy, image_name)#save the picture
pcv.outputs.clear()
```

**Comment by HaleySchuhl** [comment]
Feel welcome to reopen with any further discussion or questions!
