### ISSUE TITLE
Change readimage to read images as is, instead of as color

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#49]
Any reason why we should not add the -1 flag in the cv2.imread call to read images in their existing format instead of converting to color (default behavior)? Otherwise plantcv.readimage is only useful for color images.

**Comment by maliagehan** [comment]
not a problem, we would just have to fix some things, because some opencv functions won't use a single channel image. We've (I've) been working under the assumption that we're going to read the grey images in as a color to create a mask then read in the grey as a -1 flag.
