### ISSUE TITLE
importing with sys.path.append() failing

### ISSUE THREAD

**Issue by Mahi-Mai** [danforthcenter/plantcv#491]
Hello plantcv crew!  I use cloud services in my research.  Often this means, instead of using pip install or something similar, I'll clone the repo of interest and access the module using sys.path.append()

This used to work in the past for plantcv, but now I'm getting the following error:
```
ModuleNotFoundError: No module named 'plantcv.plantcv'
```
I've tried various combinations of sys.path.append() and import statements ( /rep/plantcv, /rep/plantcv/plantcv/, from plantcv import plantcv as pcv, etc), but they all result in the same error.

Any suggestions?  (Thanks!)

**Comment by Mahi-Mai** [comment]
Nevermind!  I figured it out by trying something i read in another thread.  I changed the name of one of the folders so that my import statement looked like this:
```
sys.path.append('/repos/plantcv')
import plantcv_ as pcv
```

Thanks for plantcv!

**Comment by nfahlgren** [comment]
Great, thanks @Mahi-Mai!

**Comment by Mahi-Mai** [comment]
I was wrong, haha1

**Comment by Mahi-Mai** [comment]
I'm ridiculous.  I didn't realize it had reached the point where I could just use "pip install plantcv" and then import using from plantcv import plantcv as pcv.  I added the pip install to my environment builder.

Problem solved!
