### ISSUE TITLE
Alt Parallelization Scheme

### ISSUE THREAD

**Issue by maliagehan** [danforthcenter/plantcv#5]
Alternative parallelization schema for PlantCV that will allow the selection of some metadata (angle etc).

**Comment by maliagehan** [comment]
Added image_analysis.py, still working to make this even more flexible.

**Comment by maliagehan** [comment]
NF added image_analysis.py to make this more flexible. Still working out the kinks to make this even more flexible.

**Comment by nfahlgren** [comment]
Python multiprocessing implemented, plus the removal of automatic matplotlib plotting seems to have lifted our CPU limit.
