### ISSUE TITLE
--dates workflow flag throws error about timestamp format

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#511]
I'm not sure when this happened but in PlantCV 3.7 i get the error from the date check function:
```
time data '20190709T113342' does not match format '%%Y%%m%%dT%%H%%M%%S'
  --> Please specify the correct --timestampformat argument <--
```
when trying to run: 
```
#! bash

outdir=output/vis
mkdir -p $outdir

python \
$CONDA_PREFIX/bin/plantcv-workflow.py \
--dir data/vis \
--workflow scripts/visworkflow.py \
--type png \
--json $outdir/vis.json \
--outdir $outdir \
--adaptor filename \
--delimiter "(.{2})-(.+)-(\d{8}T\d{6})-(.+)-(\d)" \
--timestampformat "%%Y%%m%%dT%%H%%M%%S" \
--meta plantbarcode,measurementlabel,timestamp,camera,id \
--cpu 8 \
--writeimg \
--create \
--match plantbarcode:A6 \
--dates 2019-07-17
```

The timestamp clearly is in the correct format.
It works fine without --dates.  It does not work if  `--dates 20190717` or `--dates 20190717T000000`

Implementing #474 might simplify things and resolve this.

relevant lines 180-194 plantcv-workflow.py

**Comment by nfahlgren** [comment]
The double %% is only used in Windows batch scripts correct? In Bash if you try using only one does it work?

**Comment by dschneiderch** [comment]
You are correct. Thanks!
