### ISSUE TITLE
Returning number of pixels per cluster and store them

### ISSUE THREAD

**Issue by marien1011** [danforthcenter/plantcv#518]
Hi all,

I've applied the existing Multi Plant Image Workflow and have used this to identify the number of plants given a certain number of rows and columns. In addition, I'd also like to monitor the plants by getting the number of pixels of each plant after clustering them. 

**Getting the Number of Pixels per Clustered Contours**
Below is the image attached for the final output after dividing the necessary details. Would it be possible to extract how much 'green' pixels are there and store the values (ex. array) to monitor that the growth of the plant is increasing? 

![git](https://user-images.githubusercontent.com/30958897/73278371-73f75180-4226-11ea-8932-7b61d9fb195f.JPG)

`a = pcv.rgb2gray_lab(rgb_img=img1, channel='a')`
`img_binary = pcv.threshold.binary(gray_img=a, threshold=120, max_value=255, object_type='dark')`
`fill_image = pcv.fill(bin_img=img_binary, size=10)`
`dilated = pcv.dilate(gray_img=fill_image, ksize=2, i=1)`
`id_objects, obj_hierarchy = pcv.find_objects(img=img1, mask=dilated)`
`roi_contour, roi_hierarchy = pcv.roi.rectangle(img=img1, x=150, y=90, h=250, w=1000)`
`roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img1, `roi_contour=roi_contour, `
              `                                                    roi_hierarchy=roi_hierarchy,`
                  `                                                     object_contour=id_objects,`
                    `                                                   obj_hierarchy=obj_hierarchy, `
                       `                                        roi_type='partial') `

`clusters_i, contours, hierarchies = pcv.cluster_contours(img=img1, roi_objects=roi_objects, `
  `                                                           roi_obj_hierarchy=roi_obj_hierarchy, `
   `                                                          nrow=3, ncol=7,`
   `                                                          show_grid=True)`

Apologies for being stuck. Any help would highly be appreciated. Thank you!

**Comment by HaleySchuhl** [comment]
Hi @marien1011 ,

That's certainly doable! There is an existing function `pcv.analyze_object()` that is specifically designed for measuring shape characteristics like the plant area. However, this stores out a lot of data (https://plantcv.readthedocs.io/en/latest/analyze_shape/) so storing the number of pixels per plant might be better if that is the only characteristic of interest!

There are two ways to record information about multiple plants per image and my preference is to use the newer `pcv.roi.multi()` function. 

```
...
dilated = pcv.dilate(gray_img=fill_image, ksize=2, i=1)
id_objects, obj_hierarchy = pcv.find_objects(img=img1, mask=dilated)
roi_contour, roi_hierarchy = pcv.roi.rectangle(img=img1, x=150, y=90, h=250, w=1000)
roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img1,
    roi_contour=roi_contour, roi_hierarchy=roi_hierarchy, object_contour=id_objects,
    obj_hierarchy=obj_hierarchy, roi_type='partial')

# Parameters might need adjusting, draw ROIs around each plant 
roi1, roi_hier1  = pcv.roi.multi(img=img1, coord=(150,90), radius=50,
    spacing=(20, 20), nrows=1, ncols=5)

# Initialize list of plant areas 
plant_area_list = [] 

# Loop through and filter each plant, record the size
for i in range(0, len(roi1)):
    roi = roi1[i]
    hierarchy = roi_hier1[i]
    # Find objects
    filtered_contours, filtered_hierarchy, filtered_mask, filtered_area = pcv.roi_objects(
        img=img, roi_type="partial", roi_contour=roi, roi_hierarchy=hierarchy, object_contour=roi_objects, 
        obj_hierarchy=roi_obj_hierarchy)
    plant_area_list.append(filtered_area)
    
# Label area by plant ID, leftmost plant has id=0
plant_area_labels = [i for i in range(0, len(plant_area_list))]

# Create a new measurement
pcv.outputs.add_observation(variable='plant_area', trait='plant area ',
                            method='plantcv.plantcv.roi_objects', scale='pixels', datatype=list,
                            value=plant_area_list, label=plant_area_labels)
pcv.print_results(filename="plant_area_results.txt")
```

**Comment by marien1011** [comment]
Thank you so much for explaining the code step by step.

Would also like to ask why the multiple ROIs aren't displaying in a circular shape. Does it have a maximum scale?

`# Parameters might need adjusting, draw ROIs around each plant 
roi1, roi_hier1  = pcv.roi.multi(img=img1, coord=(150,300), radius=50,
    spacing=(20, 20), nrows=2, ncols=5)`

![git](https://user-images.githubusercontent.com/30958897/73414212-127bd380-4349-11ea-8d06-f869429c8ddf.PNG)

**Comment by HaleySchuhl** [comment]
@marien1011 

It looks like your spacing is too small and is causing all your ROIs to overlap.  It is strange that the debugging image seems to be only displaying the convex hull of the overlapped circles? Anyhow, adjusting the spacing parameter ought to resolve this and will instead display the circular ROI's as usual (more detail [here](https://plantcv.readthedocs.io/en/latest/roi_multi/))

**Comment by marien1011** [comment]
Thank you so much @HaleySchuhl for the wonderful help! :)
