### ISSUE TITLE
PlantCV on Raspberry Pi 4 with BerryConda - advise please.

### ISSUE THREAD

**Issue by laburnumsystems** [danforthcenter/plantcv#521]
Trying to install plantcv on Raspberry Pi 4, on the latest Raspian build. 

https://plantcv.readthedocs.io/en/latest/installation/

I do note that this configuration is not in the list of tested environments, but wanted to reach out for advice/guidance, given the various routes I have been trying with this and rabbit holes I have been down. 

After encountering issues with miniconda3, and seeing advice on this, I switched to BerryConda

https://github.com/jjhelmus/berryconda

Specifically this

Berryconda3-2.0.0-Linux-armv7l.sh

I am able to activate plantcv [source activate plantcv]

Open CV is installed

(plantcv) pi@pi4:~ $ conda install opencv
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/pi/berryconda3/envs/plantcv:
#
opencv                    3.3.0            py36hb02bd27_0

Python 

(plantcv) pi@pi4:~ $ python3 --version
Python 3.6.6

I am having issues with cv2. The python module is struggling

pi@pi4:~/berryconda3/envs/plantcv/lib/python3.6/site-packages $ sudo python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Have tried updating my python path and even forcing python path in the py module - no luck.

Any advice most welcome. Shall I try to install PlantCV manually? Is Plant CV ready on Python3? (I am also having the issue on python 2).

(plantcv) pi@pi4:~ $ sudo python test.py
/home/pi
/usr/lib/python2.7
/usr/lib/python2.7/plat-arm-linux-gnueabihf
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/Adafruit_DHT-1.4.0-py2.7-linux-armv7l.egg
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/gtk-2.0
/home/pi/berryconda3/envs/plantcv
/home/pi/berryconda3/envs/plantcv/lib/python3.6/site-packages
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import cv2
ImportError: No module named cv2
(plantcv) pi@pi4:~ $ sudo python3 test.py
/home/pi
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/dist-packages
/usr/local/lib/python3.7/dist-packages/Adafruit_DHT-1.1.1-py3.7-linux-armv7l.egg
/usr/lib/python3/dist-packages
/home/pi/berryconda3/envs/plantcv
/home/pi/berryconda3/envs/plantcv/lib/python3.6/site-packages
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

---------------------------------------------------- 

(plantcv) pi@pi4:/ $ sudo find . -name cv2*.*
./home/pi/berryconda3/envs/plantcv/lib/python3.6/site-packages/cv2.cpython-36m-arm-linux-gnueabihf.so
./home/pi/berryconda3/pkgs/opencv-3.3.0-py36hb02bd27_0/lib/python3.6/site-packages/cv2.cpython-36m-arm-linux-gnueabihf.so

**Comment by HaleySchuhl** [comment]
Hi @laburnumsystems ,

Thank you for opening an issue! We have dropped support for Python2 this year but have PlantCV support for Python 3. Testing coverage is in both 3.6 and 3.7. 

It appears that maybe the wrong version of OpenCV is installed in your plantcv environment that you've created. When I look at the modules listed after running `pip freeze` in any of my environments I created to use PlantCV in will list `opencv-python==3.4.5.20` since we install it via the [PyPI package opencv-python](https://pypi.org/project/opencv-python/). 

Please let us know if installing opencv-python via PyPI resolves these installation issues!

**Comment by laburnumsystems** [comment]
Hi @HaleySchuhl, many thanks for your response and the reference. Unfortunately, I am still not quite there...
As directed by the reference, for Raspberry Pi, I used https://www.piwheels.org/ and actually installed the opencv, as follows. 

sudo apt install libtiff5 libpango-1.0-0 libavcodec58 libgdk-pixbuf2.0-0 libjasper1 libqt4-test libpangocairo-1.0-0 libswscale5 libilmbase23 libatk1.0-0 libgtk-3-0 libqtcore4 libcairo2 libwebp6 libavutil56 libcairo-gobject2 libopenexr23 libqtgui4 libavformat58

sudo pip3 install opencv-python==3.4.6.27 

[the latest version does not work on RPI as I and others have found [per https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/issues/67]
and 3.4.5.20 was showing as unavailable].

For 3.4.6.27, basic testing of importing cv2 and getting the version works. 

So, onward to installing plantcv! :)

I tried doing this running pip3, not pip, given we are discussing Python3.

pip3 install plantcv

This actually gets pretty far along, then finally fails. Please see attached. 

Appreciate your help, I have spent over 3 days on this so far trying various routes. 
[last try on 5 Feb.txt](https://github.com/danforthcenter/plantcv/files/4159984/last.try.on.5.Feb.txt)

**Comment by nfahlgren** [comment]
It looks like it's failing when installing `scipy` because it's not finding a Fortran compiler. If that's the case then running `sudo apt install gfortran` should add the compiler.

**Comment by laburnumsystems** [comment]
Success! plantcv installed and running on my pi4 now. 

@nfahlgren, @HaleySchuhl many thanks for your help. 

Here is a brief summary: 

1. installed pre-requisites and opencv

sudo apt install libtiff5 libpango-1.0-0 libavcodec58 libgdk-pixbuf2.0-0 libjasper1 libqt4-test libpangocairo-1.0-0 libswscale5 libilmbase23 libatk1.0-0 libgtk-3-0 libqtcore4 libcairo2 libwebp6 libavutil56 libcairo-gobject2 libopenexr23 libqtgui4 libavformat58

sudo pip3 install opencv-python==3.4.6.27

references:
https://www.piwheels.org/
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/issues/67

"Hey, this is because the latest version of openCV doesn't work with RPi. Instead of pip3 install opencv-python try pip3 install opencv-python==3.4.6.27
You will need to uninstall the latest version first. pip3 uninstall opencv-python"

2. installed fortran compiler. 

sudo apt install gfortran

references:
https://github.com/danforthcenter/plantcv/issues/521

3. Installed further dependencies. 

references:
https://stackoverflow.com/questions/53347759/importerror-libcblas-so-3-cannot-open-shared-object-file-no-such-file-or-dire

4. installed pybind11 due to compilation error. 

compilation terminated.
scipy/fft/_pocketfft/pypocketfft.cxx:15:10: fatal error: pybind11/pybind11.h: No such file or directory
#include <pybind11/pybind11.h>
                ^~~~~~~~~~~~~~~~~~~~~

5. Install plantcv. 

pip3 install plantcv


6. For testing, used the VIS example py. 

https://plantcv.readthedocs.io/en/stable/vis_tutorial/

python3 first.py -i original_image.jpg -r result_file.txt

Made some slight tweaks. 

a. Received this error in two places on running the example

TypeError: apply_mask() got an unexpected keyword argument 'rgb_img'

so removed the named argument, just used a passed (non-named argument for the image file). 

b. Received a further error

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

so passed in the results file name on the command line above, otherwise it errored.
