### ISSUE TITLE
Matplotlib deprecation errors

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#524]
**Start a discussion about anything you would like**
Functions that are using matplotlib to plot histograms often give verbose depreciation errors. While these don't inherently harm anything they are annoying and can potentially raise the concern that something went wrong while using the function even though it is working fine. I found a way to suppress these warning messages. 

```
import warnings
import matplotlib.cbook
warnings.filterwarnings("ignore",category=matplotlib.cbook.mplDeprecation)
```

Maybe this gets wrapped in a `try` block. Objections?

**Comment by dschneiderch** [comment]
yeah, super annoying. isn't the issue plotnine though?
I filter the plotnine warnings in my scripts.

**Comment by nfahlgren** [comment]
I think this will be fixed by switching the plotting backend in v4.x.
