### ISSUE TITLE
length 0 objects in segment functions

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#531]
I was adapting the morphology tutorial for my own images and ran into  a "divide by zero error" that I tracked back to `color_palette`. It turned out I was giving `segment_id` an object with length 0 so it couldn't define a color. I was using this naively but I think it would be worth checking that object has a length >0 in each of the `segment` functions and giving a helpful error message. There might be a need for error catching in `color_palette` as well.

**Comment by HaleySchuhl** [comment]
@dschneiderch I did a little bit of testing and I think our updates to the way `color_palette` is working resolves this issue. Do you think it would still be a good idea to print a warning statement in any `segment_` functions if they are passed an empty list of objects anyways?

**Comment by dschneiderch** [comment]
i couldn't reproduce this with pcv 3.7 (released dec 2019) or 3.10.1 so i'm not sure what to think.  i maybe have programmed around it and now I don't remember well enough. 
that said, an empty list is usually unexpected so a warning could be nice for a unsuspecting user.
