### ISSUE TITLE
Thresholding helper function 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#537]
**Is your feature request related to a problem? Please describe.**
We are interested in some type of function that will help users determine which is the best thresholding method rather than needing to manually try each option one by one. 

**Describe the solution you'd like**
A single function that will help users pick a thresholding method 

**Describe alternatives you've considered**
Is there a scikit image function that already does this? Show each thresholding function currently available in PlantCV. Might style it after the `pcv.visualize.colorspaces` function, or might be able to have the function automatically pick the "best" method.

**Comment by dschneiderch** [comment]
here is the thresholding helper function from skimage
https://scikit-image.org/docs/stable/api/skimage.filters.html?highlight=filters#skimage.filters.try_all_threshold

it would work like `colorspaces`. I don't think it's realistic to be able to choose a different method automatically for each image, but I do think that most imaging scenarios naturally lend themselves to one or the other method. The `filters.threshold_*` functions output the binary threshold value.  I've found the yen and isodata methods to be pretty robust with my datasets.
