### ISSUE TITLE
pruned segments still in output file

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#539]
**Describe the bug**
I'm a little confused by my workflow that uses the morphology subpackage. My results continue ot include segments less than 10 even though I've run 
```
        # Prune the skeleton
        pruned, seg_img, edge_objects = pcv.morphology.prune(skel_img=skeleton,
                                                             size=10,
                                                             mask=obj_mask)
```
here is an example from the output file:
```{json}
            "observations": {
                "segment_path_length": {
                    "trait": "segment path length",
                    "method": "plantcv.plantcv.morphology.segment_path_length",
                    "scale": "pixels",
                    "datatype": "<class 'list'>",
                    "value": [
                        0.7071067690849304,
                        6.914213538169861,
                        57.370057225227356,
                        62.40559107065201,
                        134.1923879981041
                    ],
                    "label": [
                        0,
                        1,
                        2,
                        3,
                        4
                    ]
                },
```

**Expected behavior**
I expect segments less than length 10 to be discarded.
I"m still a little confused what all these steps do exactly so could you tell me if you notice anything not right in my steps? 

```{python}

#!/usr/bin/python
import sys, traceback
import cv2
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv
import os
import json

### Parse command-line arguments
def options():
    parser = argparse.ArgumentParser(
        description="Imaging processing with opencv")
    parser.add_argument("-i",
                        "--image",
                        help="Input image file.",
                        required=True)
    parser.add_argument("-o",
                        "--outdir",
                        help="Output directory for image files.",
                        required=False)
    parser.add_argument("-r", "--result", help="result file.", required=False)
    parser.add_argument("-w",
                        "--writeimg",
                        help="write out images.",
                        default=False,
                        action="store_true")
    parser.add_argument(
        "-D",
        "--debug",
        help=
        "can be set to 'print' or None (or 'plot' if in jupyter) prints intermediate images.",
        default=None)
    args = parser.parse_args()
    return args


def createMask(img):
    b_img = pcv.rgb2gray_lab(img, 'b')
    thresh = pcv.threshold.binary(b_img, 135, 255, 'light')
    fill = pcv.fill(thresh, 100)
    seedmask = pcv.dilate(fill, 3, 3)
    roots = pcv.apply_mask(img, pcv.invert(seedmask), 'black')
    l_img = pcv.rgb2gray_lab(roots, 'l')
    thresh_l = pcv.threshold.binary(l_img, 85, 255, 'light')
    mask = pcv.fill(thresh_l, 275)
    mask = pcv.dilate(mask, 3, 2)
    mask = pcv.gaussian_blur(mask, (9,9))
    return (mask)

### Main workflow
def main():
    # Get options
    args = options()

    pcv.params.debug = args.debug  #set debug mode
    pcv.params.outdir = args.outdir  #set output directory
    pcv.params.line_thickness = 4
    pcv.params.text_size = 2
    pcv.params.text_thickness = 4
    pcv.params.dpi = 150
    
    # The result file should exist if plantcv-workflow.py was run
    if os.path.exists(args.result):
        # Open the result file
        results = open(args.result, "r")
        # The result file would have image metadata in it from plantcv-workflow.py, read it into memory
        metadata = json.load(results)
        # Close the file
        results.close()
        #
        plantbarcode = metadata['metadata']['plantbarcode']['value']
        timestamp = metadata['metadata']['timestamp']['value']
        
    img, pn, fn = pcv.readbayer(args.image)
    mask = createMask(img)
    masked_img = pcv.apply_mask(img, mask, 'black')

    # Find roots in image
    rootr, rooth = pcv.find_objects(img, mask)

    # Filter objects in image based on ROI filter
    dishr, dishh = pcv.roi.circle(mask, 1750, 1300, 400)
    obj, obj_h, obj_mask, _ = pcv.roi_objects(img, dishr, dishh, rootr, rooth)

    pcv.print_image(
        obj_mask, filename=os.path.join(args.outdir, timestamp+'_mask.png')
    )  #   (os.path.join(pn,os.path.splitext(fn)[0]+'_masked.png'))

    if len(np.unique(obj_mask)) > 1:

        # Create skeleton of roots
        skeleton = pcv.morphology.skeletonize(mask=obj_mask)

        # Prune the skeleton
        pruned, seg_img, edge_objects = pcv.morphology.prune(skel_img=skeleton,
                                                             size=10,
                                                             mask=obj_mask)

        if len(edge_objects) > 0:
            # Identify branch points
            branch_pts_mask = pcv.morphology.find_branch_pts(skel_img=pruned,
                                                             mask=obj_mask)

            # Identify tip points
            tip_pts_mask = pcv.morphology.find_tips(skel_img=pruned,
                                                    mask=obj_mask)

            # Identify segments
            segmented_img, labeled_img = pcv.morphology.segment_id(
                skel_img=pruned, objects=edge_objects, mask=obj_mask)

            # Measure path lengths of segments
            labeled_img2 = pcv.morphology.segment_path_length(
                segmented_img=segmented_img, objects=edge_objects)

            if args.writeimg:
                pcv.print_image(labeled_img2,
                                filename=os.path.join(args.outdir,
                                                    timestamp+'_length.png'))

            # Measure angle of roots
            labeled_img4 = pcv.morphology.segment_angle(
                segmented_img=segmented_img, objects=edge_objects)

            if args.writeimg:
                pcv.print_image(labeled_img4,
                                filename=os.path.join(args.outdir,
                                                    timestamp+'_angle.png'))

    pcv.print_results(args.result)


if __name__ == '__main__':
    main()
```

**Local environment (please complete the following information):**
WIndows10, PlantCV via Bioconda v3.7

**Comment by dschneiderch** [comment]
here is the example image for that result.
[Pats Wheat Root Growth_002-0001_A1_2019-06-11_07-19-08.461_0.zip](https://github.com/danforthcenter/plantcv/files/4314758/Pats.Wheat.Root.Growth_002-0001_A1_2019-06-11_07-19-08.461_0.zip)

**Comment by dschneiderch** [comment]
just going to add that i get the same results on my linux server.

**Comment by nfahlgren** [comment]
Hi @dschneiderch, I ran through your workflow with your example data and can confirm the behavior you see. I think there are two different aspects to this issue:

1. prune trims segments by `size` pixels from tips. The final segment length can be less than `size` pixels long. I.e. it's not a length threshold for keeping/discarding paths.
2. In the example image there is a small segment in the center of the 4-way branching point. It has a length of 0 and I think it's not discarded because it is a branch-to-branch segment, so pruning has not effect on it.

I have a recollection that @HaleySchuhl is/was working on a function to filter segments by path length, is that right Haley?

**Comment by HaleySchuhl** [comment]
After v3.4.1 the pruning function was updating to work more discriminately while removing pieces of skeleton. The description that @nfahlgren described since this release now describes the internal function `pcv.morphology._iterative_prune`:

> prune trims segments by size pixels from tips. The final segment length can be less than size pixels long. I.e. it's not a length threshold for keeping/discarding paths.

Instead, the `pcv.morphology.prune` function is removing any segment that is `size` pixels long or smaller without changing any of the secondary segments that are long enough. However, the second point that Noah made is the reason why you can still see segments that have a path length smaller than your `size` even after pruning if they are primary segments. We don't want to remove those since the skeleton won't be a fully connected graph anymore then. 

However, I think it would be a good idea to think about a way to clean up morphology data that gets collected since skeletons are so volatile to imperfections in masks or other weirdness. #549

**Comment by nfahlgren** [comment]
Ah, thanks for the clarification!

**Comment by dschneiderch** [comment]
Thanks for the insight.  Is there a way to merge segments  based on hierarchy?  so in this case if there is a ~0 length segment connecting 2 larger segments we'd just absorb the smallest one

**Comment by HaleySchuhl** [comment]
@dschneiderch sorry for the very late response! There isn't a function right now that combines segments based on hierarchy, but I think the recently added `pcv.morphology.analyze_stem` [function](https://plantcv.readthedocs.io/en/latest/analyze_stem/) allows for analysis of stem objects as an entire stem entity. Are there any other use cases where you could imagine the need to combine segments?

**Comment by dschneiderch** [comment]
this was a 1-off analysis and I haven't really used the morph package much since so I don't have any other cases in mind than the original germination analysis.
a 0-length segment is very weird though!

**Comment by HaleySchuhl** [comment]
Agreed! I'm going to close this issue for now but feel free to reopen with related discussion/questions.
