### ISSUE TITLE
Can't import plantcv correctly :No module named 'fatal_error'.

### ISSUE THREAD

**Issue by friendsAI** [danforthcenter/plantcv#562]
After I installed plantcv, I tried to use like this "from plantcv import plantcv as pcv", but the message says : from fatal_error import fatal_error    
ModuleNotFoundError: No module named 'fatal_error'. " 
I also tried " import plantcv as pcv",  when I use like this: 
device, threshold_gaussian = pcv.adaptive_threshold(img, 255, 'gaussian','dark', device, debug="print")
It says: AttributeError: module 'plantcv' has no attribute 'adaptive_threshold' .
How to solve this problem? My OS is Mac.

**Comment by maliagehan** [comment]
Hi friendsAI, sorry you are having trouble. Can you provide a little more information on what installation instructions you were following (did you do the conda installation? pypi?)?When you are doing the import you are working in a Jupyter notebook?

**Comment by friendsAI** [comment]
The following is the installation:
(1)Clone the PlantCV repository:  git clone git://github.com/danforthcenter/plantcv.git. (here if use https://   instead,  it will report error)
(2)Run the setup script:   cd plantcv
bash scripts/setup.sh
I use command-line window when I tried to import plantcv

**Comment by maliagehan** [comment]
Got it, so you followed the script based installation, @nfahlgren can chime in but I might recommend using the Conda installation instead (https://plantcv.readthedocs.io/en/stable/installation/#conda-based-installation-procedure). It will require installing miniconda https://docs.conda.io/en/latest/miniconda.html

**Comment by friendsAI** [comment]
But I can't see environment.yml in the plantcv folder, instead ,there is a venv folder. The version of plantcv is 2.

**Comment by maliagehan** [comment]
Thanks friendsAi, Is there a reason why you are installing an older version of PlantCV? we're currently in version 3.

**Comment by friendsAI** [comment]
when I install plantcv, I  thought the latest version is 2 , so  I use  this command:   git clone --branch v2.0 git://github.com/danforthcenter/plantcv.git
Well,   I'll try  reinstall by the instructions in the webpage  you just mentioned.

**Comment by friendsAI** [comment]
I reinstalled plantcv according to the page(https://plantcv.readthedocs.io/en/stable/installation/#conda-based-installation-procedure) ,and now I can import it correctly. Thank you very much! @ maliagehan
