### ISSUE TITLE
add "Breaking Changes" to release notes

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#564]
would it be possible to include breaking changes to the release notes? it can be a little frustrating to track down an issue just to find an internal code change 5 months ago :-) 

I guess it's been a couple versions now but I don't see it in the release notes:
https://github.com/danforthcenter/plantcv/commit/7f066f120f41038935bc41017405a258f2b6f195#diff-2f8f75e21900a7fd10e8469827e8290a
This one is particularly frustrating because I'm fairly sure it used to result in 0, then got changed to a fatal_error, and now is back to 0. So I've been chasing my tail. Personally I think resulting in 0 is the best way to handle this.

In the next release pcv.threshold_custom_range(...,'RGB') should be listed.

**Comment by nfahlgren** [comment]
When we change the input/output structure we document it starting here: https://plantcv.readthedocs.io/en/stable/updating/#plantcvacute

**Comment by dschneiderch** [comment]
but it's not there..... https://plantcv.readthedocs.io/en/stable/updating/#plantcvroi_objects
a summary would be more useful in my opinion than having to scroll through every fuction in pcv

**Comment by nfahlgren** [comment]
What is there is accurate though. I think the fatal error was introduced but we decided it was not good so it was removed. Our goal is to summarize each release but sometimes we miss some things. We could start including a section on breaking changes specifically though.

**Comment by dschneiderch** [comment]
sorry not trying to sound grumpy about it. just frustrated what feels like chasing my tail.

**Comment by nfahlgren** [comment]
No worries, understandable :)

**Comment by nfahlgren** [comment]
Hi @dschneiderch, starting with release v3.9.0 we are adding a section about breaking changes to the release notes (thanks @HaleySchuhl!).
