### ISSUE TITLE
Set default wavelength units for ENVI files

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#565]
**Is your feature request related to a problem? Please describe.**
@Mamatemenrs gave us some sample hyperspectral data to test with because it was not working with `pcv.readimage`. I found two issues.

First, the file names were:

```
REFLECTANCE_2019-06-09_010.dat
REFLECTANCE_2019-06-09_010.hdr
```

But we expect:

```
REFLECTANCE_2019-06-09_010.dat
REFLECTANCE_2019-06-09_010.dat.hdr
```

Second, the `hdr` file was missing the `wavelength units` key-value pair.

**Describe the solution you'd like**
For the missing `wavelength units` key in the `hdr` file, I think we can check if the key exists in the parsed header file and if it doesn't set `wavelength units` to `nm` by default. If I rename the files as we expect and add this key-value pair to the `hdr` file PlantCV reads the image in correctly.

For the file extensions, I think what we have and what @Mamatemenrs has seem like they could both be common. Maybe we should check for the existence of `filename + ".hdr"`, and if it doesn't exist, check for `filename[:-4] + ".hdr"`?

**Comment by Mamatemenrs** [comment]
wavelength units key does exist in the hdr file for BSQ format data, yet the value is unknown. nm is the right wavelength unit for both formats of data.
