### ISSUE TITLE
Potential dependency conflicts between plantcv and numpy

### ISSUE THREAD

**Issue by NeolithEra** [danforthcenter/plantcv#575]
Hi, as shown in the following full dependency graph of **_plantcv_**, **_plantcv_** requires **_numpy >=1.11,<1.17,<1.17_**, **_plantcv_** requires **_matplotlib >=1.5_** (**_matplotlib3.2.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_matplotlib 3.2.1_** transitively introduces **_numpy >=1.11,<1.17_**.

Obviously, there are multiple version constraints set for **_numpy_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_numpy 1.16.6_** (i.e., the newest version satisfying constraint **_>=1.11,<1.17_**) is the actually installed version.

Although the first found package version **_numpy 1.16.6_** just satisfies the later dependency constraint （**_numpy >=1.11,<1.17_**), such installed version is very close to the upper bound of the version constraint of numpy specified by **_matplotlib 3.2.1_**. 

Once **_matplotlib_** upgrades，its newest version will be installed, as **_plantcv_** does not specify the upper bound of version constraint for **_matplotlib_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_matplotlib_** version introduces a higher version of **_numpy_**, violating its another version constraint **_>=1.11,<1.17_**.

According to the release history of matplotlib, it habitually upgrates Numpy in its recent releases. For instance, matplotlib #15645 upgrated Numpy’s constraint from **_>=1.11 to >=1.12_**, and matplotlib #15698 upgrated Numpy’s constraint from **_>=1.12 to >=1.15_**. 

As such, it is a warm warning of a potential dependency conflict issue for plantcv.

### Dependency tree
```
plantcv  - 3.7
| +- matplotlib(install version:3.2.1 version range:>=1.5)
| | +- cycler(install version:0.10.0 version range:>=0.10)
| | | +- six(install version:1.14.0 version range:*)
| | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | +- numpy(install version:1.16.6 version range:>=1.11)
| | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| +- numpy(install version:1.16.6 version range:>=1.11,<1.17)
| +- opencv-python(install version:3.4.9.33 version range:>=3.4,<4)
| +- pandas(install version:1.0.3 version range:*)
| +- plotnine(install version:0.5.1 version range:<=0.5.1)
| +- python-dateutil(install version:2.8.1 version range:*)
| +- scikit-image(install version:0.14.2 version range:==0.14.2)
| +- scipy(install version:1.2.3 version range:<1.3)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.11_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_matplotlib_**.
3.	Change your direct dependency **_matplotlib_** to be **_>=1.5,<=3.2.1_**.
@nfahlgren  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by nfahlgren** [comment]
Hi @NeolithEra,

Thanks for reaching out with the suggestions above! It looks like the dependency tree above is for PlantCV v3.7. In the latest release, v3.8 we implemented your suggestion 1 by loosening the version range of NumPy.

Best,
Noah

**Comment by HaleySchuhl** [comment]
Feel free to reopen with further comments/questions!
