### ISSUE TITLE
Quantifying discoloration

### ISSUE THREAD

**Issue by rjuncu** [danforthcenter/plantcv#577]
Hi, I was wondering if anyone had any good analysis approaches to this problem. I have leaf pictures with areas that are discolored to varying degrees. I want to quantify how discolored these areas are. I have seen similar projects find the average hue value of the leaf, find the percent of the leaf that is discolored, and find healthy/unhealthy pixel ratios. I feel like these methods aren't super effective for what I want to do. Most of the methods are influenced by the size of the discolored area, when I only care about how severely it is discolored. If anyone is willing to give their two cents I'd really appreciate it!

**Comment by nfahlgren** [comment]
Hi @rjuncu, one idea that comes to mind is measuring the distance between hue values. I'm thinking something like measuring the average hue of leaves that are not discolored (or some type of control). Then for each pixel on a leaf being analyzed, measure the hue value and calculate the absolute distance between the observed hue and the reference hue value. Normal green pixels would be similar to the reference mean hue, discolored pixels would be further away. Would something like that work?

**Comment by rjuncu** [comment]
@nfahlgren Thanks a lot!!

**Comment by HaleySchuhl** [comment]
Feel free to reopen with any further related questions/comments!
