### ISSUE TITLE
Docker Image ImportError: libGL.so.1: No such file or directory

### ISSUE THREAD

**Issue by jamesthesken** [danforthcenter/plantcv#579]
**Describe the bug**
Pulling the Docker image as outlined in the documentation results in missing shared libraries. 

```
$ docker run danforthcenter/plantcv python -c 'from plantcv import plantcv as pcv; print(pcv.__version__)'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/plantcv-3.8.0+135.g2e9c0c40-py3.7.egg/plantcv/plantcv/__init__.py", line 137, in <module>
    from plantcv.plantcv.print_image import print_image
  File "/opt/conda/lib/python3.7/site-packages/plantcv-3.8.0+135.g2e9c0c40-py3.7.egg/plantcv/plantcv/print_image.py", line 3, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

```

**To Reproduce**
1. `docker pull danforthcenter/plantcv`
2. `docker run danforthcenter/plantcv python -c 'from plantcv import plantcv as pcv; print(pcv.__version__)'`
3. See error above

**Expected behavior**
According to the documentation, nothing should appear on the console as the package is imported correctly.

**Local environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Environment: Docker version 19.03.8
 - PlantCV Version 3.8.0

**Additional context**
Thank you for any help!

**Comment by nfahlgren** [comment]
Hi @jamesthesken, thanks for reporting this! I was able to reproduce the issue and tested a solution locally. I created the pull request #580 to fix this bug. Once we merge it a new version of the container should be automatically built on Docker Hub.

**Comment by nfahlgren** [comment]
I tested pulling the updated container and it's working for me, let me know if it's working on your end as well. Thanks!

**Comment by jamesthesken** [comment]
Excellent support, it's working! Thank you!
