### ISSUE TITLE
Unexpected results from VIS example

### ISSUE THREAD

**Issue by SeanStephensenAIRM** [danforthcenter/plantcv#585]
I am trying to run the [VIS Workflow](https://plantcv.readthedocs.io/en/latest/vis_tutorial/) example on one of my own images using PyCharm and not getting the same results as when I run the Jupyter example on the provided test image. I have copied and pasted the full code from the bottom of the linked page, and modified the 3 or 4 misnamed kwargs which cause instant failure (are these known? should I file a separate issue?). my CL call is:

`python pcv_test.py -i "C:\Users\seans\Documents\145343.tif" -D 'print' -w -o "C:\Users\seans\Documents\"`

The program runs with no errors, but does not output anything or display anything at any point. I have tried adding in a few print statements in `pcv_test.py` (the copied code) to verify that it is reaching points, and it seems to be successfully reading in the image and generating a mask. When I manually output the mask from this script (another imwrite call), it successfully writes out a mask, however not the one that I want.

For the following input image, I get the following mask (from the `kept_mask` variable in the example code), which is clearly background noise instead of the plant:

![pcv1](https://user-images.githubusercontent.com/60408933/84914124-e0150d80-b080-11ea-907b-9459b5378b82.PNG)

![pcv2](https://user-images.githubusercontent.com/60408933/84914141-e4412b00-b080-11ea-9cd9-38c3e001ddf2.PNG)

I expect that a better setup photo with better lighting on the plant and a cleaner background will help. To test this idea, I tried faking a clean background on the same photo with MS paint, and then again with cropping the background out:

![pcv3](https://user-images.githubusercontent.com/60408933/84914301-13579c80-b081-11ea-8271-392641d57f96.PNG)

![pcv4](https://user-images.githubusercontent.com/60408933/84914313-16528d00-b081-11ea-8454-7e4ef4f849b0.PNG)

Both of these methods give me the following error:
```
Warning: Invalid contour.
Traceback (most recent call last):
  File "pcv_test.py", line 119, in <module>
    main()
  File "pcv_test.py", line 104, in main
    shape_imgs = pcv.analyze_object(img=img, obj=obj, mask=mask)
  File "C:\Users\seans\Documents\image_classification\venv\lib\site-packages\plantcv\plantcv\analyze_object.py", line 30, in analyze_object
    if len(obj) < 5:
TypeError: object of type 'NoneType' has no len()
```

Any advice on any way of solving any off the issues here? to recap:
-the program as provided gives me no output. Are my CL flags incorrect?
-Why do manually cropped or cleaned images encounter the contour error?
-How can I improve my experimental setup to not need to manually crop/clean?
-Bonus: Should I provide more info on the mislabelled kwargs in the stock script?

To be thorough, and since the script isn't too long, here's the code that I copied/pasted/fixed kwargs/added a mask imwrite:

```
# !/usr/bin/python
import sys, traceback
import cv2
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv


### Parse command-line arguments
def options():
    parser = argparse.ArgumentParser(description="Imaging processing with opencv")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-r", "--result", help="result file.", required=False)
    parser.add_argument("-w", "--writeimg", help="write out images.", default=False, action="store_true")
    parser.add_argument("-D", "--debug",
                        help="can be set to 'print' or None (or 'plot' if in jupyter) prints intermediate images.",
                        default=None)
    args = parser.parse_args()
    return args

#### Start of the Main/Customizable portion of the workflow.

### Main workflow
def main():
    # Get options
    args = options()

    pcv.params.debug = args.debug  # set debug mode
    pcv.params.debug_outdir = args.outdir  # set output directory

    # Read image
    img, path, filename = pcv.readimage(filename=args.image)

    # Convert RGB to HSV and extract the saturation channel
    s = pcv.rgb2gray_hsv(rgb_img=img, channel='s')

    # Threshold the saturation image
    s_thresh = pcv.threshold.binary(gray_img=s, threshold=85, max_value=255, object_type='light')

    # Median Blur
    s_mblur = pcv.median_blur(gray_img=s_thresh, ksize=5)
    s_cnt = pcv.median_blur(gray_img=s_thresh, ksize=5)

    # Convert RGB to LAB and extract the Blue channel
    b = pcv.rgb2gray_lab(rgb_img=img, channel='b')

    # Threshold the blue image
    b_thresh = pcv.threshold.binary(gray_img=b, threshold=160, max_value=255, object_type='light')
    b_cnt = pcv.threshold.binary(gray_img=b, threshold=160, max_value=255, object_type='light')

    # Fill small objects
    # b_fill = pcv.fill(b_thresh, 10)

    # Join the thresholded saturation and blue-yellow images
    bs = pcv.logical_or(bin_img1=s_mblur, bin_img2=b_cnt)

    # Apply Mask (for VIS images, mask_color=white)
    masked = pcv.apply_mask(img=img, mask=bs, mask_color='white')

    # Convert RGB to LAB and extract the Green-Magenta and Blue-Yellow channels
    masked_a = pcv.rgb2gray_lab(rgb_img=masked, channel='a')
    masked_b = pcv.rgb2gray_lab(rgb_img=masked, channel='b')

    # Threshold the green-magenta and blue images
    maskeda_thresh = pcv.threshold.binary(gray_img=masked_a, threshold=115, max_value=255, object_type='dark')
    maskeda_thresh1 = pcv.threshold.binary(gray_img=masked_a, threshold=135, max_value=255, object_type='light')
    maskedb_thresh = pcv.threshold.binary(gray_img=masked_b, threshold=128, max_value=255, object_type='light')

    # Join the thresholded saturation and blue-yellow images (OR)
    ab1 = pcv.logical_or(bin_img1=maskeda_thresh, bin_img2=maskedb_thresh)
    ab = pcv.logical_or(bin_img1=maskeda_thresh1, bin_img2=ab1)

    # Fill small objects
    ab_fill = pcv.fill(bin_img=ab, size=200)

    # Apply mask (for VIS images, mask_color=white)
    masked2 = pcv.apply_mask(img=masked, mask=ab_fill, mask_color='white')

    # Identify objects
    id_objects, obj_hierarchy = pcv.find_objects(img=masked2, mask=ab_fill)

    # Define ROI
    roi1, roi_hierarchy= pcv.roi.rectangle(img=masked2, x=100, y=100, h=200, w=200)

    # Decide which objects to keep
    roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi1,
                                                               roi_hierarchy=roi_hierarchy,
                                                               object_contour=id_objects,
                                                               obj_hierarchy=obj_hierarchy,
                                                               roi_type='partial')
    cv2.imwrite("C:\Users\seans\Documents\mask.png", kept_mask)
    # Object combine kept objects
    obj, mask = pcv.object_composition(img=img, contours=roi_objects, hierarchy=hierarchy3)

    ############### Analysis ################

    outfile=False
    if args.writeimg == True:
        outfile = args.outdir + "/" + filename

    # Find shape properties, output shape image (optional)
    shape_imgs = pcv.analyze_object(img=img, obj=obj, mask=mask)

    # Shape properties relative to user boundary line (optional)
    boundary_img1 = pcv.analyze_bound_horizontal(img=img, obj=obj, mask=mask, line_position=1680)

    # Determine color properties: Histograms, Color Slices, output color analyzed histogram (optional)
    color_histogram = pcv.analyze_color(rgb_img=img, mask=kept_mask, hist_plot_type='all')

    # Pseudocolor the grayscale image
    pseudocolored_img = pcv.visualize.pseudocolor(gray_img=s, mask=kept_mask, cmap='jet')

    # Write shape and color data to results file
    # pcv.print_results(filename=args.result)

if __name__ == '__main__':
    main()
```

**Comment by nfahlgren** [comment]
Hi @SeanStephensenAIRM, thanks for reaching out!

We had not noticed the incorrect keyword arguments, let's definitely get those fixed. I'm noting the following need to be fixed:

Line 47: b = pcv.rgb2gray_lab(**rgb_img**=img, channel='b')

Line 60: masked = pcv.apply_mask(**img**=img, mask=bs, mask_color='white')

Line 79: masked2 = pcv.apply_mask(**img**=masked, mask=ab_fill, mask_color='white')

**Comment by SeanStephensenAIRM** [comment]
Thank you for the prompt reply, @nfahlgren . Those are the only 3 mislabelled kwargs that I encountered - the script runs after that. Please me know if you have any ideas about the remaining issues once it runs.

**Comment by nfahlgren** [comment]
One issue for sure is that the settings in the example pipeline don't work as-is for your image. But another issue is the lack of output you observe. When I run the pipeline on your picture with debug set to print (`-D print`) I do get all the debug images in the folder I specify with the `-o` option. I want to confirm that in `C:\Users\seans\Documents\` you do not see images labeled with prefixes in the range 1-73?

Rather than tweaking the example workflow parameters, I put together a quick workflow for your example image. It's definitely not perfect, misses the plant stem because it's hard to distinguish between it and the soil.

[example_workflow.pdf](https://github.com/danforthcenter/plantcv/files/4794017/example_workflow.pdf)

**Comment by SeanStephensenAIRM** [comment]
Thanks again for the attention, @nfahlgren . It appears that my error was coming from using `-D 'print'` in CLI instead of `-D print`. That's probably just my inexperience with CLI shining through, assuming that I needed to indicate a string input. Your ROI specification seems handy, and alleviates the problems I was having with manual cropping etc. Thanks for the help.

**Comment by nfahlgren** [comment]
print or 'print' should work in theory, but maybe Windows does not like the quoted version. I do not test on Windows often, though we are building in automatic testing across Linux, Windows, and macOS for each release going forward.
