### ISSUE TITLE
image is not binary

### ISSUE THREAD

**Issue by danammeansbear** [danforthcenter/plantcv#591]
S C:\Users\adam\.spyder-py3> python multiplantworkflow.py -i C:\Users\adam\.spyder-py3\multiplant.jpg -o C:\Users\adam\.spyder-py3\images -n names.txt -D 'print'
>>
Traceback (most recent call last):
  File "multiplantworkflow.py", line 198, in <module>
    main()
  File "multiplantworkflow.py", line 110, in main
    fill_image = pcv.fill(bin_img=img_binary, size=100)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plantcv\plantcv\fill.py", line 31, in fill
    fatal_error("Image is not binary")
  File "C:\ProgramData\Anaconda3\lib\site-packages\plantcv\plantcv\fatal_error.py", line 14, in fatal_error
    raise RuntimeError(error)
RuntimeError: Image is not binary

**Expected behavior**

**Local environment (please complete the following information):**
 - OS: [e.g. Linux, macOS, Windows]
 - Environment [e.g. conda, virtualenv, pip, docker, etc.]
 - PlantCV Version [e.g. 3.6.0]

**Additional context**

**Comment by HaleySchuhl** [comment]
hi @danammeansbear ,

The error message indicates that the image saved in the `img_binary` variable is probably either grayscale or RGB. Many PlantCV functions can output binary images, such as the functions inside the threshold sub-package. Could you attach the entire workflow that you're using? This will help see why the image type is disagreeing.

**Comment by danammeansbear** [comment]
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 24 22:23:22 2020

@author: adam
"""
#!/usr/bin/python

import sys, traceback
import cv2
import os
import re
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv

### Parse command-line arguments
def options():
    parser = argparse.ArgumentParser(description="Imaging processing with opencv")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=True)
    parser.add_argument("-n", "--names", help="path to txt file with names of genotypes to split images into", required =False)
    parser.add_argument("-D", "--debug", help="Turn on debug, prints intermediate images.", action=None)
    args = parser.parse_args()
    return args

### Main workflow
def main():
    # Get options
    args = options()

    # Read image
    img, path, filename = pcv.readimage(args.image)

    pcv.params.debug=args.debug #set debug mode

    # STEP 1: Check if this is a night image, for some of these dataset's images were captured
    # at night, even if nothing is visible. To make sure that images are not taken at
    # night we check that the image isn't mostly dark (0=black, 255=white).
    # if it is a night image it throws a fatal error and stops the workflow.

    if np.average(img) < 50:
        pcv.fatal_error("Night Image")
    else:
        pass

    # STEP 2: Normalize the white color so you can later
    # compare color between images.
    # Inputs:
    #   img = image object, RGB colorspace
    #   roi = region for white reference, if none uses the whole image,
    #         otherwise (x position, y position, box width, box height)

    # white balance image based on white toughspot

    img1 = pcv.white_balance(img=img,roi=(400,800,200,200))

    # STEP 3: Rotate the image
    # Inputs:
    #   img = image object, RGB color space
    #   rotation_deg = Rotation angle in degrees, can be negative, positive values 
    #                  will move counter-clockwise 
    #   crop = If True then image will be cropped to original image dimensions, if False
    #          the image size will be adjusted to accommodate new image dimensions 


    rotate_img = pcv.rotate(img=img1,rotation_deg=-1, crop=False)

    # STEP 4: Shift image. This step is important for clustering later on.
    # For this image it also allows you to push the green raspberry pi camera
    # out of the image. This step might not be necessary for all images.
    # The resulting image is the same size as the original.
    # Inputs:
    #   img    = image object
    #   number = integer, number of pixels to move image
    #   side   = direction to move from "top", "bottom", "right","left"

    shift1 = pcv.shift_img(img=img1, number=300, side='top')
    img1 = shift1

    # STEP 5: Convert image from RGB colorspace to LAB colorspace
    # Keep only the green-magenta channel (grayscale)
    # Inputs:
    #    img     = image object, RGB colorspace
    #    channel = color subchannel ('l' = lightness, 'a' = green-magenta , 'b' = blue-yellow)

    #a = pcv.rgb2gray_lab(img=img1, channel='a')
    a = pcv.rgb2gray_lab(rgb_img=img1, channel='a')

    # STEP 6: Set a binary threshold on the saturation channel image
    # Inputs:
    #    img         = img object, grayscale
    #    threshold   = threshold value (0-255)
    #    max_value   = value to apply above threshold (usually 255 = white)
    #    object_type = light or dark
    #       - If object is light then standard thresholding is done
    #       - If object is dark then inverse thresholding is done

    img_binary = pcv.threshold.binary(gray_img=a, threshold=120, max_value=255, object_type='dark')
    #img_binary = pcv.threshold.binary(gray_img=a, threshold=120, max_value=225, object_type='dark')                                                   ^
    #                                                   |
    #                                     adjust this value

    # STEP 7: Fill in small objects (speckles)
    # Inputs:
    #    bin_img  = image object, binary. img will be returned after filling
    #    size = minimum object area size in pixels (integer)

    fill_image = pcv.fill(bin_img=img_binary, size=100)
    #                                          ^
    #                                          |
    #                           adjust this value

    # STEP 8: Dilate so that you don't lose leaves (just in case)
    # Inputs:
    #    img    = input image
    #    ksize  = kernel size
    #    i      = iterations, i.e. number of consecutive filtering passes

    dilated = pcv.dilate(img=fill_image, ksize=1, i=1)

    # STEP 9: Find objects (contours: black-white boundaries)
    # Inputs:
    #    img  = image that the objects will be overlayed
    #    mask = what is used for object detection

    id_objects, obj_hierarchy = pcv.find_objects(img=img1, mask=dilated)

    # STEP 10: Define region of interest (ROI)
    # Inputs:
    #    img       = img to overlay roi
    #    x_adj     = adjust center along x axis
    #    y_adj     = adjust center along y axis
    #    h_adj     = adjust height
    #    w_adj     = adjust width
    # roi_contour, roi_hierarchy = pcv.roi.rectangle(img1, 10, 500, -10, -100)
    #                                                      ^                ^
    #                                                      |________________|
    #                                            adjust these four values

    roi_contour, roi_hierarchy = pcv.roi.rectangle(img=img1, x=6, y=90, h=200, w=390)

    # STEP 11: Keep objects that overlap with the ROI
    # Inputs:
    #    img            = img to display kept objects
    #    roi_contour    = contour of roi, output from any ROI function
    #    roi_hierarchy  = contour of roi, output from any ROI function
    #    object_contour = contours of objects, output from "Identifying Objects" function
    #    obj_hierarchy  = hierarchy of objects, output from "Identifying Objects" function
    #    roi_type       = 'partial' (default, for partially inside), 'cutto', or 'largest' (keep only largest contour)

    roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img1, roi_contour=roi_contour, 
                                                                          roi_hierarchy=roi_hierarchy,
                                                                          object_contour=id_objects,
                                                                          obj_hierarchy=obj_hierarchy, 
                                                                          roi_type='partial')

    # STEP 12: This function take a image with multiple contours and
    # clusters them based on user input of rows and columns

    # Inputs:
    #    img               = An RGB image
    #    roi_objects       = object contours in an image that are needed to be clustered.
    #    roi_obj_hierarchy = object hierarchy
    #    nrow              = number of rows to cluster (this should be the approximate  number of desired rows in the entire image even if there isn't a literal row of plants)
    #    ncol              = number of columns to cluster (this should be the approximate number of desired columns in the entire image even if there isn't a literal row of plants)
    #    show_grid         = if True then a grid gets displayed in debug mode (default show_grid=False)

    clusters_i, contours, hierarchies = pcv.cluster_contours(img=img1, roi_objects=roi_objects, 
                                                             roi_obj_hierarchy=roi_obj_hierarchy, 
                                                             nrow=4, ncol=6)

    # STEP 13: This function takes clustered contours and splits them into multiple images,
    # also does a check to make sure that the number of inputted filenames matches the number
    # of clustered contours. If no filenames are given then the objects are just numbered
    # Inputs:
    #    img                     = ideally a masked RGB image.
    #    grouped_contour_indexes = output of cluster_contours, indexes of clusters of contours
    #    contours                = contours to cluster, output of cluster_contours
    #    hierarchy               = object hierarchy
    #    outdir                  = directory for output images
    #    file                    = the name of the input image to use as a base name , output of filename from read_image function
    #    filenames               = input txt file with list of filenames in order from top to bottom left to right (likely list of genotypes)

    # Set global debug behavior to None (default), "print" (to file), or "plot" (Jupyter Notebooks or X11)
    pcv.params.debug = "print"

    out = args.outdir
    names = args.names

    output_path, imgs, masks = pcv.cluster_contour_splitimg(img=img1, grouped_contour_indexes=clusters_i, 
                                                            contours=contours, hierarchy=hierarchies, 
                                                            outdir=out, file=filename, filenames=names)

# Call program
if __name__ == '__main__':
    main()

**Comment by danammeansbear** [comment]
it is the sample multiplant workflow from the documentation. Im going through and creating video tutorials on the software and noticed the documentation needs updated and I was able to figure it out for the first vis workflow.

**Comment by nfahlgren** [comment]
I think this line:

```python

img_binary = pcv.threshold.binary(gray_img=a, threshold=120, max_value=255, object_type='dark')
```

is returning an all black or all white image. The fill function triggers the error because it’s looking for an image with two unique values (0, 255 typically). The threshold value needs to be adjusted lower/higher.

**Comment by HaleySchuhl** [comment]
I need to test the static multi-plant workflow but I can confirm that the interactive tutorials are functioning as intended.

**Comment by danammeansbear** [comment]
>>
Traceback (most recent call last):
  File "multiplantworkflow.py", line 198, in <module>
    main()
  File "multiplantworkflow.py", line 110, in main
    fill_image = pcv.fill(bin_img=img_binary, size=100)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plantcv\plantcv\fill.py", line 31, in fill
    fatal_error("Image is not binary")
  File "C:\ProgramData\Anaconda3\lib\site-packages\plantcv\plantcv\fatal_error.py", line 14, in fatal_error
    raise RuntimeError(error)
RuntimeError: Image is not binary
PS C:\Users\adam\.spyder-py3>


is the exact error i am receiving, hopefully this helps it.

**Comment by danammeansbear** [comment]
so is my image just the problem?

**Comment by HaleySchuhl** [comment]
@danammeansbear most likely! As @nfahlgren mentioned, you probably need to adjust the `threshold` parameter in the `pcv.threshold.binary` right above the `pcv.fill` step. 

Are you running the workflow in Jupyter? We suggest developing/editing workflows in Jupyter for easier debugging.

**Comment by danammeansbear** [comment]
Thank you, Currently I am using spyder IDE not jupyter.

**Comment by nfahlgren** [comment]
We found in #585 that on Windows `-D 'print'` with quotes caused it to not output debug images. If you instead use `-D print` without quotes it should save all the intermediate images so you can visualize how the settings for each step are working for your image.

**Comment by danammeansbear** [comment]
![multiplant](https://user-images.githubusercontent.com/30583193/85759643-2270c700-b6df-11ea-8c32-723c9598a305.jpg)

Currently using this image from the documentation
Still confused on why an image from documentation you provide wont work. I changed the threshold down in increments of 20 but no change. I also found out that print or 'print' only works with jupyter not command line where I usually run my code.

**Comment by nfahlgren** [comment]
The images embedded in the documentation are for web-viewing only as examples. They are not original size for reduced size, loading speed, etc. Some steps in the workflows (ROIs for example) have settings that depend on the original image dimensions.

The interactive documentation (launch binder button) contains both the workflow and example data that works as-is with the workflow.

**Comment by danammeansbear** [comment]
the code for VIS Example needs to be updated because I had to run through these[](https://github.com/danforthcenter/plantcv/issues/585) to get the example to run so maybe its something similar ?

**Comment by danammeansbear** [comment]
thank you again I am very naive still!

**Comment by nfahlgren** [comment]
In the VIS tutorial you might have run into some of the issues in #585? If so, we updated the workflow in the default branch of PlantCV yesterday, but they won't show up in the "stable" version of the documentation until we make a new versioned release. The "latest" documentation can be accessed at this link though: https://plantcv.readthedocs.io/en/latest/

And no worries at all, this is great feedback. We really appreciate it!

**Comment by danammeansbear** [comment]
You honestly have made an amazing product, Im surprised you aren't more popular !

**Comment by nfahlgren** [comment]
Thanks @danammeansbear! Feel free to reach out if you run into other issues

**Comment by danammeansbear** [comment]
PS C:\Users\adam\.spyder-py3> python multiplantworkflow.py -i C:\Users\adam\.spyder-py3\mt.jpg -o C:\Users\adam\.spyder-py3\images -n names.txt -D print
>>
Traceback (most recent call last):
  File "multiplantworkflow.py", line 198, in <module>
    main()
  File "multiplantworkflow.py", line 121, in main
    dilated = pcv.dilate(img=fill_image, ksize=1, i=1)
TypeError: dilate() got an unexpected keyword argument 'img'

**Comment by nfahlgren** [comment]
You are correct, `pcv.dilate` should have an input called `gray_img` instead of only `img`.
