### ISSUE TITLE
Creating video using time lapse images

### ISSUE THREAD

**Issue by Sanazjd** [danforthcenter/plantcv#602]
I was working on making a video from time lapse images last week and I thought it might be a useful feature to add to plantCV. Do you think it is something plantCV community will be interested? If so I can go ahead and contribute it following the instructions on https://plantcv.readthedocs.io/en/latest/CONTRIBUTING/.

**Comment by maliagehan** [comment]
HI @Sanazjd great to hear from you. @DannieSheng has recently added something similar in the timeseries subpackage (https://github.com/danforthcenter/plantcv/tree/add_time_series_sub_package) that's currently on its own branch sounds like there could be overlap.

**Comment by Sanazjd** [comment]
Hi @maliagehan,
Awesome, I'll check timeseries subpackage, I'm doing a lot of timeseries these days and it will be a great help.

**Comment by DannieSheng** [comment]
Hi @Sanazjd and @maliagehan 
The function to create time lapse video was added as a function in the "visualize" subpackage.
The link provided by Malia works, you will have then to go into plantcv/plantcv/visualize, and you will see the function "time_lapse_video.py"
This change has yet to be merged to the master.

**Comment by Sanazjd** [comment]
@DannieSheng this looks great and works flawless. One suggestion is to add a feature to skip n images or take every nth image from the directory. I had more than 2000 images and I chose every 10th image to create the video.

**Comment by DannieSheng** [comment]
@Sanazjd 
It's great to hear that it works for you! 
To get a subset of your images, you have an option to use the 2nd parameter "list_img" by providing a list of image names.

**Comment by Sanazjd** [comment]
> @Sanazjd
> It's great to hear that it works for you!
> To get a subset of your images, you have an option to use the 2nd parameter "list_img" by providing a list of image names.

I see, totally make sense.
