### ISSUE TITLE
Support PSII data from CropReporter

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#606]
We wish to add the functionality to support CropReporter PSII data. Short term goals include the ability to read in raw image data files into a PlantCV workflow, with long term goals of extended analysis capabilities into a fluorescence subpackage. 

**Proposed method**
Dump in raw data, reshape, and possibly filter captured arrays to keep those needed. 
Minimal method for reading the data: 
```
from plantcv import plantcv as pcv
import numpy as np
dat = "image.DAT"
ImageCols = 1296
ImageRows = 966
y = ImageRows
x = ImageCols
raw_data = np.fromfile(dat, np.uint16, -1)
array_data = raw_data.reshape(y, int(len(raw_data)/(y*x)), x).transpose((0, 2, 1))
```

**Describe alternatives you've considered**

**Additional context**
* Crop reporter outputs a DAT file and an INI file
* INI file is sort of like the ENVI (hyperspectral) metadata file, and includes image dimensions 
* In array_data each item in the z-axis/channel dimension is a separate image
* The INI file should help us figure out what each image in the set is

**Comment by dschneiderch** [comment]
#426 for reference
this reinforces the idea that we need to build some preprocessing functions that package multiframe snapshots like a collect of .png into a single file, potentially with a metadata file.
