### ISSUE TITLE
Update documentation to revise conda installation procedure

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#608]
**Is your feature request related to a problem? Please describe.**
Starting with PlantCV v3.9.0, the `plantcv` conda package is available through the `conda-forge` channel. We need to update several things to reflect this.

**Describe the solution you'd like**
- [ ] Update documentation
  - [ ] Docs home page `index.md`
  - [ ] Docs installation page `installation.md`
  - [ ] Docs updating page `updating.md`
- [ ] Update README conda button/badge
- [ ] VICE Dockerfile `vice/Dockerfile`

Closed by #629

**Comment by dschneiderch** [comment]
Are you giving up on bioconda?
________________________________

**Comment by nfahlgren** [comment]
Just for the PlantCV package. OpenCV was the tricky bit and since it's hosted in conda-forge there is sort of an easier path there for building on top of it. I think plantcv <=3.8.0 will still be available through bioconda, 3.9.0+ from conda-forge.
