### ISSUE TITLE
I found the broken link of the sample code about "analyze_stem".

### ISSUE THREAD

**Issue by electop** [danforthcenter/plantcv#613]
**Describe the bug**
This's the broken link about "analyze_stem".
https://github.com/danforthcenter/plantcv/blob/master/plantcv/plantcv/analyze_stem.py

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1.  Go to "https://github.com/danforthcenter/plantcv/blob/master/docs/analyze_stem.md"
2.  Click to the link of "Source Code: Here".
3.  See error

**Expected behavior**
It should see the sample code of "analyze_stem.py".

**Local environment (please complete the following information):**
 - OS: All
 - Environment: Web
 - PlantCV Version: All

**Additional context**
None

**Comment by HaleySchuhl** [comment]
@electop thanks for bringing this to our attention! I can update this doc page and fix the broken link within the pull request I'll be finishing up today!
