### ISSUE TITLE
Pseudocolor function plotting issues

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#620]
**Describe the bug**
@dschneiderch noted that on his Windows system the `pcv.visualize.pseudocolor` function was plotting even when `pcv.params.debug = None`. He proposed the updating the debug logic block to the following:

```python
if params.debug is not None:
    if params.debug == 'print':
        plt.savefig(os.path.join(params.debug_outdir, str(params.device) + '_pseudocolored.png'), dpi=params.dpi)
        plt.close()
    elif params.debug == 'plot':
        plot_image(pseudo_img1)
        # Use non-blocking mode in case the function is run more than once
        plt.show(block=False)
```

Essentially this removes an extra piece of logic that did `plt.show()` even when debug was set to `None`.

I think there are some other issues to work out though, so I'm opening this as a new issue instead of applying the fix within another PR.

**To Reproduce**

**Issue 1**
We automatically set the `matplotlib` backend under conditions where we do not detect a display.:

```python
# If there is no display or a matplotlib backend already defined, use the non-GUI backend
if "DISPLAY" not in os.environ and "MPLBACKEND" not in os.environ:
    matplotlib.use("Agg")
```

On Linux and macOS, if `DISPLAY` is not a defined environment variable, or we are not in Jupyter (MPLBACKEND), then we set the backend to Agg so that plots can be created without trying to plot to a window/screen device. One part of @dschneiderch issue I think is that on Windows we are not accounting for display devices.

**Issue 2**
Related to the above issue, `pcv.visualize.pseudocolor`, with the current code, displays the image even when debug is `None`. In Jupyter for example:

```python
%matplotlib inline
from plantcv import plantcv as pcv
pcv.params.debug = None
img, imgpath, imgname = pcv.readimage(filename="image.png")
gray_img = pcv.rgb2gray_hsv(rgb_img=img, channel="v")
ps_img = pcv.visualize.pseudocolor(gray_img=gray_img)
# Plots the pseudocolor image here
ps_img.savefig("test.png")
# Saves the image correctly to a file
```

**Issue 3**
If the current code is modified to remove the extra `plt.show()` and the code is run multiple times in an environment with the `Agg` backend multiple scale bars are plotted, probably because the figure does not get closed before plotting again. 

**Expected behavior**
I'm not 100% sure what the overall solution is, we will need to try running some test code in Jupyter, on the command line, and with/without plotting interfaces to make sure we can get the behavior set to be consistent.

**Local environment (please complete the following information):**
 - OS: macOS, Windows
 - Environment: conda, Jupyter, command-line
 - PlantCV Version: 3.9.0+68.g409b26b

**Comment by dschneiderch** [comment]
@nfahlgren I thin you probably know this but just to be explicit on Windows DISPLAY is in os.environ as:
`'DISPLAY': 'localhost:0.0'`

**Comment by nfahlgren** [comment]
I did not actually!

**Comment by dschneiderch** [comment]
just an untested idea but maybe this would work
```
if params.debug is not None:
    if params.debug == 'print':
        plt.savefig(os.path.join(params.debug_outdir, str(params.device) + '_pseudocolored.png'), dpi=params.dpi)
        plt.close()
    elif params.debug == 'plot':
        plot_image(pseudo_img1)
        # Use non-blocking mode in case the function is run more than once
        plt.show(block=False)
else:
        plt.close()
```

**Comment by dschneiderch** [comment]
actually i'm surprised that ` "DISPLAY" not in os.environ` this works on unix. I thought DISPLAY was always localhost on  unix systems

**Comment by nfahlgren** [comment]
At least on our system we don't install the desktop environment, only the sever packages, so DISPLAY is undefined by default.

**Comment by dschneiderch** [comment]
"our system" meaning a server?

this also explains why I was having issues on my server because `  'DISPLAY': '10.110.17.28:10.0',` when I use ssh -Y

**Comment by nfahlgren** [comment]
So I think Jupyter is an easy case, when you are in Jupyter you want a backend that supports plotting, even if you don't use it.

One possible solution is to use the Agg backend whenever we are not in Jupyter (or another notebook - which I would need to look into more).  Essentially to modify Lines 4-5 of the main `__init__.py` file to:

```python
if "MPLBACKEND" not in os.environ:
    matplotlib.use("Agg")
```

The downside is if you have a DISPLAY and you want plots to show up, perhaps if you are working in Spyder or something, then that would disable it.

**Comment by dschneiderch** [comment]
did you ever try just closing the figure if debug=None?

**Comment by nfahlgren** [comment]
Not yet. But I'm thinking closing it means that the returned figure cannot be saved or displayed anymore?

**Comment by dschneiderch** [comment]
if thats the case then when it gets closed with debug=print is also a bug

**Comment by dschneiderch** [comment]
also, in spyder `'MPLBACKEND': 'module://ipykernel.pylab.backend_inline',`  BUT - my figure is not inline and in a separate window instead so I'm not sure what that means.  in my prefs I have it set for "automatic" selection of display and the help suggests that will thus us a separate figure.

**Comment by dschneiderch** [comment]
I think its been overcomplicated. I removed the stuff in __init__.py and changed the debug code and everything works as expected with ipython terminal and running as a workflow with latest master. here are 3 different iterations of the figure, the first 2 from consecutive pseudocolor() and the 3rd I added a scalebar to the output from pseudocolor() using matplotlib functions

![test-a](https://user-images.githubusercontent.com/7461221/93514937-a69caa00-f8dc-11ea-891e-1c5bdb48a2c8.png)
![test-a2](https://user-images.githubusercontent.com/7461221/93514939-a7354080-f8dc-11ea-9b57-8866fcade7c2.png)
![test-a3](https://user-images.githubusercontent.com/7461221/93514931-a56b7d00-f8dc-11ea-982c-93374b79af7b.png)


New code:

```
    # Print or plot if debug is turned on
    if params.debug is not None:
        if params.debug == 'print':
            plt.savefig(os.path.join(params.debug_outdir, str(
                params.device) + '_pseudocolored.png'), dpi=params.dpi)
            plt.close()
        elif params.debug == 'plot':
            plot_image(pseudo_img1)
            # Use non-blocking mode in case the function is run more than once
            plt.show(block=False)
    else:
        plt.close()
```

then ran this in an ipython terminal (for the scalebar you can install cppcpyutils with pip and import as cppc)
```
from plantcv import plantcv as pcv
img,_,_=pcv.readimage('tests/data/VIS_SV_0_z300_h1_g0_e85_v500_93054.png')
gray_img = pcv.rgb2gray_hsv(rgb_img=img, channel="v")
pcv.params.debug=None
ps_img = pcv.visualize.pseudocolor(gray_img=gray_img, colorbar=True, axes=False)
ps_img.savefig('test-b.png')
ps_img = pcv.visualize.pseudocolor(gray_img=gray_img, colorbar=True, axes=False)
ps_img.savefig('test-b1.png')
ps_img2=cppc.viz.add_scalebar(ps_img, 0.2, 10, '1 cm') # you can install cppcpyutils with pip then import as cppc
ps_img2.savefig('test-b2.png')
```

**Comment by nfahlgren** [comment]
I think the code in `__init__.py` should stay. I agree it's actually not related to this issue because plotting should just not happen if debug = None. But I think we do need to set the backend to Agg when no plotting device is available.

**Comment by dschneiderch** [comment]
I agree, but then I raise the question how do you decide if no plotting device is available?  DISPLAY does not seem to translate and it seems like matplotlib (or someonen else?) is already doing the work of figuring it out

**Comment by dschneiderch** [comment]
for example, when I ssh to my server without -Y I have no DISPLAY and matplotlib automatically sets it to 'agg' so the plantcv code is redundant.  i'm not sure how to test that on Windows but i guess there is basically always a display on windows(? - thats why it's called Windows! - I'll show myself out)
