### ISSUE TITLE
A question about themral data analysis

### ISSUE THREAD

**Issue by Ove7comer** [danforthcenter/plantcv#627]
**Start a discussion about anything you would like**
Discussions can be used to ask questions, discuss new ideas, or anything else.
Hi,

Wanna to know how can the analysis_thermal_values function get the temperature?
Just wanna to know how it works.
My original data is PNG file, which cannot meet the requirement of parameters in analysis_thermal_values function.

Thank you!

**Comment by HaleySchuhl** [comment]
Hi @Ove7comer ,

I would suggest taking a look at the example thermal analysis workflow in our [tutorials](https://plantcv.readthedocs.io/en/latest/thermal_tutorial/). If you have a CSV from a FLIR or other thermal camera, you should be able to read the image in with `pcv.readimage` and from there the `pcv.analyze_thermal_values` function will extract the thermal values of each pixel and calculates a histogram plot of pixel intensity.

I'm not familiar with PNG formatted thermal data, but we are always looking to extend our functionality to more datatypes/cameras. Could you attach the original image here for further testing?

**Comment by dschneiderch** [comment]
relevant? https://github.com/nationaldronesau/FlirImageExtractor

**Comment by HaleySchuhl** [comment]
I'm going to close this issue for now, but feel free to open with any other further questions or comments!
