### ISSUE TITLE
VIS_TUTORIAL_JSON converted CSV file is empty

### ISSUE THREAD

**Issue by Nivedita-mahato2** [danforthcenter/plantcv#633]
**Describe the bug**
When running the VIS tutorial, In the last step where I have saved my file as text, I was not able to convert the file to CSV. After trying different solutions provided to others on GitHub by your team, the code worked but produced empty CSV files. I tried everything and nothing seems to work. Kindly suggest

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Starting with image, the image you can see the empty CSV files created on the right side,
![image](https://user-images.githubusercontent.com/57456847/96050547-b672c400-0e71-11eb-9674-313c829501cd.png)

2. Run function(s) 'import plantcv.parallel
import plantcv.utils
plantcv.parallel.process_results(job_dir=args.tmp_dir, json_file="results.json")
plantcv.utils.json2csv(json_file="results.json", csv_file="results")'

3. See error
 Find the screenshot

**Expected behavior**
 - CSV FILE  which contains the data of the analysis I performed on the image.

**Local environment (please complete the following information):**
 - OS: [ Windows]
 - Environment [ pip, google colab]
 - PlantCV Version [e.g. 3.6.0]

**Additional context**

My python file:
[plantcv_shape_analysis.zip](https://github.com/danforthcenter/plantcv/files/5381100/plantcv_shape_analysis.zip)

**Comment by nfahlgren** [comment]
Hi @Nivedita-mahato2!

I think the only change needed is that this line:

`Result= pcv.print_results(filename= 'vis_nir_tutorial_results.txt')`

should be:

`pcv.print_results(filename= args.result)`

**Comment by HaleySchuhl** [comment]
I'm going to close this issue for now, but feel free to open with any other further questions or comments!
