### ISSUE TITLE
Help with plantcv workflow parallelization

### ISSUE THREAD

**Issue by VictorNeaco** [danforthcenter/plantcv#638]
Hello!
I was following along with the latest Friday Workshop session on image analysis workflows in Plant CV and I couldn't get the config file creation to work in my Jupyter Notebook, using the same lines from the tutorial. (I am using the Plant CV kernel)

from plant cv import plantcv as pcv

import plantcv.parallel
config = plantcv.parallel.WorkflowConfig()
config.save_config(config_file = "config.json")

When I try to run this cell, I get the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-8-d7cb58fa1c88> in <module>
      1 import plantcv.parallel
----> 2 config = plantcv.parallel.WorkflowConfig()
      3 config.save_config("config.json")

AttributeError: module 'plantcv.parallel' has no attribute 'WorkflowConfig'

If I could get some help with this, it would be greatly appreciated!

**Comment by nfahlgren** [comment]
Hi @VictorNeaco!

Could you let me know what the output of this code is in your Jupyter notebook?

```python
from plantcv import plantcv as pcv
print(pcv.__version__)
print(pcv.__file__)
```

**Comment by VictorNeaco** [comment]
Hi Noah, 
I get this when I run that code.
3.8.0
/storage/data/conda/envs/plantcv/lib/python3.7/site-packages/plantcv/plantcv/__init__.py

Do I need to update anything?
Thanks for the speedy response!

**Comment by nfahlgren** [comment]
Perfect, thanks! The `WorkflowConfig` feature was introduced in v3.10.0 (v3.10.1 is the latest release). What might have happened is we moved PlantCV from bioconda to conda-forge after 3.8. You can update using `conda update plantcv` and that should ask to install 3.10.1, but if not you could try `conda update -c conda-forge plantcv` and I think that should do it for sure.

**Comment by VictorNeaco** [comment]
Thanks, I think that worked!
