### ISSUE TITLE
Add jupyter to Python pipeline function

### ISSUE THREAD

**Issue by maliagehan** [danforthcenter/plantcv#64]

**Comment by nfahlgren** [comment]
Thinking about this a bit more, maybe we don't need this script? You can export a Jupyter Python notebook as a Python script already (on the command line: `jupyter nbconvert --to python notebook.ipynb`). After downloading the script, the code would need to be refactored to make it compatible with our parallelization framework (or even just to make it a flexible script). Our hypothetical script could try to do the refactoring (add the argparse option function, add Jupyter code to the main function, etc.), but I suspect not all refactoring can be done automatically.

So the question is, is it worth doing the big refactoring with a script, and then the user can finish up the fine work, or is it easier to just add a how-to in our Jupyter documentation, with the necessary example code that needs to be pasted in? I am thinking the latter is more robust and that the script does not save the user very much time, but I am open to the script if we think it can save time.

**Comment by jshoyer** [comment]
For what it is worth, I find the idea here (or at least the title of the issue) confusing. The idea was to go in a single step from .ipynb json to a .py 'pipeline' script that could be used directly with plantcv-pipeline.py? That seems error-prone.
