### ISSUE TITLE
Problems running workflow parallelization

### ISSUE THREAD

**Issue by VictorNeaco** [danforthcenter/plantcv#640]
Hello!
I've made a config .json file for my plantcv workflow parallelization. I launched CMD.exe Prompt through my Anaconda Navigator in the PlantCV environment and entered the following line.

plantcv-workflow.py --config raspberrypi_image_workflow_config.json

Instead of processing the images from the folder I specified,  plantcv-workflow.py was opened in Notepad and nothing else seemed to happen. 

I would appreciate any input to get this fixed!
Thanks!

**Comment by dschneiderch** [comment]
On windows you'll need to type
python  %CONDA_PREFIX%/Scripts/plantcv-workflow.py --config raspberrypi_image_workflow_config.json

________________________________

**Comment by VictorNeaco** [comment]
It worked. Thanks so much!
