### ISSUE TITLE
Possible feature: automatically process MIAPPE/ISA-TAB metadata

### ISSUE THREAD

**Issue by jshoyer** [danforthcenter/plantcv#65]
### Description

Perhaps the lead developers have considered the metadata formats that other groups are promoting (below). Personally I find the amount of XML boilerplate required onerous, so I have not wrapped my head around the formats.
Processing ISA-TAB tables with python should not be too hard, and so may be worth discussing. This functionality might improve compatibility and/or convenience.
Lacking that, the 2016-06 [PDF table for MIAPPE](http://cropnet.pl/phenotypes/wp-content/uploads/2016/04/MIAPPE.pdf) may have ideas worth considering.

### Context

See 'ISA-Tab for phenotyping' [page](http://cropnet.pl/phenotypes/?page_id=37).
[Krajewski et al. 2016](http://doi.org/10.1093/jxb/erv271) described the format.
[Arend et al. 2016](http://doi.org/10.1038/sdata.2016.55) provide a dataset (*A. thaliana* C24 phenotyped with a new IPK Lemnatec system) documented with these standards. Their data might provide a nice test case for enhancing rosette plant analysis tools.

**Comment by nfahlgren** [comment]
Definitely an ongoing discussion, see [here](https://github.com/terraref/reference-data/issues/18). Our collaborators in the [Plant Imaging Consortium](http://plantimaging.cast.uark.edu/) are using MIAPPE for the HTP system at Arkansas State.

We also just learned about [PODD](http://www.plantphenomics.org.au/projects/podd/).

**Comment by nfahlgren** [comment]
I should also say that we should bring Mindy and other people that have deployed systems into the discussion, because a lot of these standards focus on the experimental metadata that would need to be provided by experimenters.

**Comment by jshoyer** [comment]
I am closing this for now---feel free to reopen whenever.
The next thing to do would be to experiment with the `isa-api` python package: https://isatools.readthedocs.io
If that package proves easy to use/reason about, then we can talk further about importing that package or otherwise "baking" the functionality into plantcv.

**Comment by jshoyer** [comment]
Linking here, for the record, to the recent published description of MIAPPE by [Ćwiek-Kupczyńska et al.](http://doi.org/10.1186/s13007-016-0144-4) (2016).

I am still not eager to use XML.

**Comment by jshoyer** [comment]
I am not sure why I thought that that ISA-Tab used XML by default---it is actually tab-delimited text (TSV), my favorite!
The second main way to serialize the ISA Abstract Model is ISA-JSON.
http://isa-specs.readthedocs.io/en/latest/isamodel.html

Trying out the the `isatools` (now version 0.5) would still be the next step for doing anything programmatic about this.

**Comment by nfahlgren** [comment]
Ah, nice. I knew they had the TSV format but didn't know they had ISA-JSON. TSV is definitely nice for easy parsing, but not as flexible when you have hierarchical data. The Python json package is really great for reading/writing JSON. Better than any XML parser I have ever tried anyhow :)

**Comment by jshoyer** [comment]
Related efforts to understand the terminology: https://github.com/PlantPhenoHack2017/HackTopics/issues/3

See also notes on proposed effort to standardize metadata (pre)collection: https://github.com/PlantPhenoHack2017/HackTopics/issues/4
