### ISSUE TITLE
Set of Thermal Images

### ISSUE THREAD

**Issue by anshikasharma26** [danforthcenter/plantcv#650]
We are working on the early detection of crop diseases primarily focussing on lettuce using the PlantCV. Can you provide us with some set of thermal images of any crop or Lettuce?

**Comment by HaleySchuhl** [comment]
Hi @anshikasharma26 ,

I'm not sure that we have any public thermal data, and as far as I know the researchers that are taking thermal images are doing so in Setaria. I can check back with other members of the PlantCV team and see if we have any thermal data that we could share, but there is at least one thermal image available to download from our interactive documentation. The thermal tutorial will also let you click through the workflow we wrote. https://plantcv.readthedocs.io/en/latest/thermal_tutorial/

**Comment by HaleySchuhl** [comment]
Hi @anshikasharma26 ,

After checking, it looks like TERRA-REF has publicly available FLIR thermal data here: https://doi.org/10.5061/dryad.4b8gtht99 

Hope this is useful! I'm going to close this issue for now, but feel free to reopen with other questions or comments.
