### ISSUE TITLE
analyze_nir_intensity

### ISSUE THREAD

**Issue by EdwinP503** [danforthcenter/plantcv#679]
Hello, 

So I have been working with a NIR image and I want to pull out a histogram after applying a threshold and a mask on a grayscale image, but I keep getting an error and I am sure I could be writing a wrong input. After multiple tries I want to know what is causing this error and fix it right away, let me know guys.

error                                     Traceback (most recent call last)
<ipython-input-20-0092705703e1> in <module>
----> 1 nir_hist = pcv.analyze_nir_intensity(gray_img=img, mask=mask_1, bins=256, histplot=True)
      2 nir_frequencies = pcv.outputs.observations['nir_frequencies']['value']

~/opt/anaconda3/lib/python3.8/site-packages/plantcv/plantcv/analyze_nir_intensity.py in analyze_nir_intensity(gray_img, mask, bins, histplot)
     52 
     53     # Calculate histogram
---> 54     hist_nir = [float(i[0]) for i in cv2.calcHist([gray_img], [0], mask, [bins], [0, maxval])]
     55     # Create list of bin labels
     56     bin_width = maxval / float(bins)

error: OpenCV(3.4.11) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-44rz6009/opencv/modules/imgproc/src/histogram.cpp:993: error: (-215:Assertion failed) mask.empty() || mask.type() == CV_8UC1 in function 'calcHist'

Best,
Edwin

**Comment by HaleySchuhl** [comment]
Hi there @EdwinP503 thanks for reaching out!

Based on the error message I think it looks like it's complaining about something with the mask input at that `analyze_nir_intensity` step. Since you're likely making the mask from the NIR image, you might need to change the format of your binary image slightly before proceeding to use it to mask your data. Do you use a PlantCV function to create your `mask1`?

**Comment by EdwinP503** [comment]
Yes, I am using PlantCV. So, I started by applying a binary threshold and follow with a `fill_objects` and `image_subtract` functions to remove some big objects, then I applied `mask1`. How can I edit the format? What functions could I do?

**Comment by HaleySchuhl** [comment]
Can you check the format of the mask by doing `mask1.dtype` and confirm that it's uint8 datatype?

**Comment by EdwinP503** [comment]
Oh it says unit16

**Comment by HaleySchuhl** [comment]
Ok cool! So that should be a relatively easy update to get your data and histogram out.

`mask1 = mask1.astype(np.uint8)` 

And then try to run the `pcv.analyze_nir_intensity` function again using the converted mask.

**Comment by EdwinP503** [comment]
it says the name `np` is not defined

**Comment by HaleySchuhl** [comment]
If you include `import numpy as np` in your imports, then I think this error should resolve.

**Comment by EdwinP503** [comment]
Thank you for the help it worked!
