### ISSUE TITLE
Need help in an error

### ISSUE THREAD

**Issue by fareed1234** [danforthcenter/plantcv#683]
I get this error and I really don't know what is causing it so I really appreciate any help in this regard:

![Screenshot 2021-02-07 173431](https://user-images.githubusercontent.com/78707980/107162731-d66f4b80-696a-11eb-8125-819a12cf9d39.png)

thank you

**Comment by nfahlgren** [comment]
Hi @fareed1234,

From what I can tell, it looks like `img1` is not a 3-channel (RGB) image as expected for that function and the underlying OpenCV method. In your `testPlant` workflow can you add the following code prior to running `pcv.rgb2gray_lab` so we can see what the dimensions of `img1` are?

```python
print(img1.shape)
```

**Comment by fareed1234** [comment]
It says: (1544, 2064)

**Comment by nfahlgren** [comment]
Hi @fareed1234,

Shape outputs the dimensions of the image in height, width, depth. Since this image has no depth that means it is a single height x width matrix, making it a grayscale image. An RGB image would have a depth of 3. The PlantCV rgb2gray functions require an RGB input image, so that's what is ultimately causing the error. We should put a better error check on this function however to output a more useful error message.

**Comment by fareed1234** [comment]
Thank you so much for your help. Currently I have some images as an output and I'm wondering how to make the software create the shapefile. There is this output image that reasonably identified the leaves without its shadows and is there the option to create a shapefile from the tracing of this image? Thanks again for your help. 
![6_fill10](https://user-images.githubusercontent.com/78707980/107432703-f713de80-6aed-11eb-8803-c9c1a9395520.png)

**Comment by nfahlgren** [comment]
In order for downstream steps to work, more filtering steps will be needed on this mask image to remove the small objects in the background, the edge around the tray, etc. Some filters that could be useful are [removing small objects](https://plantcv.readthedocs.io/en/stable/fill/), [median blur](https://plantcv.readthedocs.io/en/stable/median_blur/), and [erosion](https://plantcv.readthedocs.io/en/stable/erode/) and [dilation](https://plantcv.readthedocs.io/en/stable/dilate/).

We do not utilize shapefiles in PlantCV, but we have several mechanisms that can be used to identify and isolate regions for individual plants. One place to start is to look at the [multi-plant tutorial](https://plantcv.readthedocs.io/en/stable/multi-plant_tutorial/). In particular, if you click on the "launch binder" button on the tutorial page you can access an interactive environment that walks through several options for identifying individual plants.

The tutorial primarily uses the [cluster_contours](https://plantcv.readthedocs.io/en/stable/cluster_contours/) method that splits the objects into an evenly spaced grid. Some other options are to use a [multi-region of interest](https://plantcv.readthedocs.io/en/stable/roi_multi/) that creates evenly spaced circular ROIs or custom placed ROIs, or to use [spatial clustering](https://plantcv.readthedocs.io/en/stable/spatial_clustering/) to cluster pixels into groups of plants without a regular layout.

**Comment by fareed1234** [comment]
Thanks a lot for your help.

**Comment by fareed1234** [comment]
Are you aware of any Packages in R software that is used for Plant tracing?

**Comment by nfahlgren** [comment]
I am not aware of any R packages for image labeling if you mean drawing an outline around each plant. There are quite a few tools for labeling that are stand-alone applications that I could suggest.

But if you mean you are looking for something similar to PlantCV but in R, I would highly recommend FIELDimageR: https://github.com/OpenDroneMap/FIELDimageR

**Comment by fareed1234** [comment]
Your help is greatly appreciated. Thank you.
