### ISSUE TITLE
New Feature: RGB to CMYK

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#733]
PlantCV has both a [rbg2hsv](https://plantcv.readthedocs.io/en/stable/rgb2hsv/) and [rgb2lab](https://plantcv.readthedocs.io/en/stable/rgb2lab/) but no conversion to [CMYK](https://en.wikipedia.org/wiki/CMYK_color_model).

For a recent project, I found the Yellow channel in CMYK especially useful for separating my crops from background (including the support cages) from images taken on a LemnaTec Scanalyser 3D phenomics platform.

Guessing that this may be useful to others, I have had a go at adding a new PlantCV function in my own cloned repository. 

I have created my first [pull request](https://github.com/danforthcenter/plantcv/pull/732) to PlantCV which I hope is to everyone's satisfaction.

I have tested this as thoroughly as I am able but would welcome contributions from others.

**Comment by nfahlgren** [comment]
Thanks @AdamDimech, that's awesome!

**Comment by AdamDimech** [comment]
Since posting this yesterday, I have made some adjustments to the code and it now runs much more efficiently. Additionally, there was a problem with the rendering of the individual channels using matplotlib in Jupyter Notebook [eg: `plt.imshow(m, cmap="gray")]. I have made adjustments so that the selection of a channel to threshold - say Yellow - will be reflected correctly in the output of Jupyter Notebook and PlantCV when run in production which wasn't happening properly before.
