### ISSUE TITLE
'Outputs' object has no attribute 'save_results'

### ISSUE THREAD

**Issue by l30ni3** [danforthcenter/plantcv#773]
**Describe the bug**
I am running the plantcv library in a flask API. When sending an image to the /upload endpoint everything seems to work correctly (e.g. I am getting the colors values after running my workflow via pcv.outputs.observations['default']['hue_circular_std']['value']), until it reaches pcv.outputs.save_results(filename='results.json'), then I am getting the error:

line 88, in upload
pcv.outputs.save_results(filename='results.json')
AttributeError: 'Outputs' object has no attribute 'save_results'

As I read in the docs the output class is created on import from platcv automatically, do I miss something else?

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):

1. Starting with uploading an image from react native to flask backend. In the /upload endpoint it is saved to a directory in my project: file.save(os.path.join(UPLOAD_FOLDER, filename)). I am taking the same path as source for the plantcv workflow.

2. This is my /upload endpoint:

@bp.route('/images/upload', methods=['POST'])
def upload():
    file = request.files['photo']
    if file.filename == '':
        flash('No image selected for uploading')
        return redirect(request.url)
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        print('upload_image filename: ' + filename)

        # Read image
        img, path, filename = pcv.readimage(
            os.path.join(UPLOAD_FOLDER, filename))

        mask, masked_img = pcv.threshold.custom_range(
            img=img, lower_thresh=[25, 0, 0], upper_thresh=[75, 255, 255], channel='HSV')

        binary_img = pcv.median_blur(gray_img=mask, ksize=10)

        mask2 = pcv.fill(bin_img=binary_img, size=200)

        # Identify objects
        id_objects, obj_hierarchy = pcv.find_objects(img, mask2)

        # Get size of image
        h, w, c = img.shape

        # Define ROI
        roi1, roi_hierarchy = pcv.roi.rectangle(
            img=img, x=0, y=h/8*3, h=h/4, w=w)

        # Decide which objects to keep
        roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi1,
                                                                       roi_hierarchy=roi_hierarchy,
                                                                       object_contour=id_objects,
                                                                       obj_hierarchy=obj_hierarchy,
                                                                       roi_type='partial')

        # Object combine kept objects
        obj, mask2 = pcv.object_composition(
            img=img, contours=roi_objects, hierarchy=hierarchy3)

        # Determine color properties: Histograms, Color Slices, output color analyzed histogram (optional)
        color_histogram = pcv.analyze_color(
            rgb_img=img, mask=mask2, hist_plot_type=None, label="default")

        # Access data stored out from analyze_color
        print(pcv.outputs.observations['default']
              ['hue_circular_mean']['value'])

        # Access data stored out from analyze_color
        print(pcv.outputs.observations['default']
              ['hue_circular_std']['value'])

        # Access data stored out from analyze_color
        print(pcv.outputs.observations['default']
              ['hue_median']['value'])

        # Write shape data to results file
        pcv.outputs.save_results(filename='results.json')
    else:
        flash('Allowed image types are - png, jpg, jpeg, gif')

    return ({}, 204)

3. See error

upload_image filename: 3445B7F8-F395-4C9B-9B8E-39AEA0AB8CCE.jpg
68.94420930303228
8.17164690891775
68.0
127.0.0.1 - - [16/May/2021 19:01:49] "POST /api/images/upload HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/leoniekoch/Desktop/BA/05_Code/ntester/api/app/views/files.py", line 88, in upload
    pcv.outputs.save_results(filename='results.json')
AttributeError: 'Outputs' object has no attribute 'save_results'

**Expected behavior**
I'd like to have the outputs saved to a file called 'results.json'.

**Local environment (please complete the following information):**
 - OS: macOS
 - Environment: pip
 - PlantCV Version: plantcv==3.12.0

**Additional context**
pip freeze output:
click==8.0.0
cloudpickle==1.6.0
cycler==0.10.0
dask==2021.5.0
dask-jobqueue==0.7.2
decorator==4.4.2
descartes==1.1.0
distributed==2021.5.0
fsspec==2021.5.0
HeapDict==1.0.1
imageio==2.9.0
joblib==1.0.1
kiwisolver==1.3.1
locket==0.2.1
matplotlib==3.4.2
mizani==0.7.3
msgpack==1.0.2
networkx==2.5.1
numpy==1.20.3
opencv-python==3.4.14.51
palettable==3.3.0
pandas==1.2.4
partd==1.2.0
patsy==0.5.1
Pillow==8.2.0
plantcv==3.12.0
plotnine==0.8.0
psutil==5.8.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
PyWavelets==1.1.1
PyYAML==5.4.1
scikit-image==0.18.1
scikit-learn==0.24.2
scipy==1.6.3
six==1.16.0
sortedcontainers==2.3.0
statsmodels==0.12.2
tblib==1.7.0
threadpoolctl==2.1.0
tifffile==2021.4.8
toolz==0.11.1
tornado==6.1
zict==2.0.0

**Comment by nfahlgren** [comment]
Hi @l30ni3,

Thank you for the detailed report! `pcv.outputs.save_results` was only added recently in PlantCV v3.12 but it looks like you have the correct version installed in your environment. What I am thinking might be going on is that there are two different Python installations? When you run `pip freeze` the environment looks correct, but I noticed that `flask` is not included in the environment. Above it looks like flask is installed in `/usr/local/lib/python3.9/site-packages/flask`, so what I'm thinking is that in the `python3.9` library there is an older version of PlantCV.

One way to check for this is to add this to the Flask app:

```python
print(pcv.__version__)
```

**Comment by l30ni3** [comment]
Hi @nfahlgren,
thanks a lot, your are absolutely right! print (pcv.__version__) turns out to be 3.11.0.
As I am a beginner to python, the concept of virtual environments is quite new to me I must have mixed something up here. I will try to figure that out, thanks a lot!!

**Comment by l30ni3** [comment]
Hi @nfahlgren,
thanks a lot, your are absolutely right! print (pcv.__version__) turns out to be 3.11.0.
As I am a beginner to python, the concept of virtual environments is quite new to me I must have mixed something up here. I will try to figure that out, thanks a lot!!

**Comment by nfahlgren** [comment]
Thanks @l30ni3, let us know if there are any other issues!
