### ISSUE TITLE
Not able to read hyperspectral raw data

### ISSUE THREAD

**Issue by alishabs** [danforthcenter/plantcv#779]
```
from plantcv import plantcv as pcv
raw_spectral_filename= 'ENVI_20201106_185130.raw'
white_reference_filename='ENVI_20201106_161614.raw'
dark_reference_filename='ENVI_20201106_142239.raw'
raw = pcv.readimage(filename=raw_spectral_filename, mode = 'envi')
white_reference = pcv.readimage(filename=white_reference_filename, mode = 'envi')
dark_reference = pcv.readimage(filename=dark_reference_filename, mode = 'envi')
```
I have a .hdr file with the same name as .raw file and in the same folder.
I am getting this error: IndexError: index 734 is out of bounds for axis 2 with size 7

**Comment by alishabs** [comment]
this is the information i have:
 	# Rows:            800
 	# Samples:        1280
 	# Bands:             7

Bands = [734.0, 759.0, 774.0, 804.0, 823.0, 848.0, 868.0]

**Comment by nfahlgren** [comment]
Hi @alishabs, can you post the full contents of the `hdr` file associated with your raw ENVI file?
