### ISSUE TITLE
Not able to read hyperspectral raw images

### ISSUE THREAD

**Issue by shahbazhussain21** [danforthcenter/plantcv#780]
I tried using the following code to read .raw file. My .hdr file is in the same folder with the same name as .raw file.

`from plantcv import plantcv as pcv

raw_spectral_filename='20201106_161614_white/ENVI_20201106_161614.raw'

raw = pcv.readimage(filename=raw_spectral_filename, mode = 'envi')`

I am getting this error: 
IndexError: index 734 is out of bounds for axis 2 with size 7

This is the information I have:
Rows:            800
Samples:        1280
Bands:             7
Band wavelengths:  [734.0, 759.0, 774.0, 804.0, 823.0, 848.0, 868.0]

Attached is the .hdr file: [https://drive.google.com/file/d/1FlyqNFBj41_DUnmvulatTB7QxtjlNrvY/view?usp=sharing](url)

**Comment by shahbazhussain21** [comment]
`path = '20201106_161614_white/ENVI_20201106_161614.raw'`
pcv.hyperspectral.read_data(path)

getting the same error:
IndexError: index 734 is out of bounds for axis 2 with size 7

**Comment by nfahlgren** [comment]
Hi @shahbazhussain21, thanks for sending the `hdr` file! At least one issue is that your raw data are arranged in Band Sequential (BSQ) format and our current reader only supports Band Interleaved by Line (BIL) format. I introduced a pull request #781 to add support for BSQ data. Once it's merged PlantCV should be able to support your data.

**Comment by nfahlgren** [comment]
Hi @shahbazhussain21, this has been merged now and is available if PlantCV is installed from source. It will be included in PlantCV v3.13 once it's released
