### ISSUE TITLE
Skeletonize Function

### ISSUE THREAD

**Issue by RGROVE1232** [danforthcenter/plantcv#808]
When extracting segmented leaf angles from an image I am faced with gaps in the skeleton where the leaf is which then reads misrepresented angles.

_**Is there a way to adjust the thickness of the skeleton instead of having it one pixel wide?**_

I at first thought my issue was rooted when I convert the image to a binary and then blur but this was not the case.

**Comment by HaleySchuhl** [comment]
Hi @RGROVE1232 thanks for opening an issue!

The thickness of a skeleton must be just one pixel wide in order for those algorithms to work properly, so any adjustments to increase the robustness of the plants' structure should take place before skeletonization. I usually suggest using functions to clean up and refine the binary mask with steps such as `pcv.fill_holes` and `pcv.dilate`. If the binary mask has disconnected structure then the skeleton will reflect this as well. I've also had higher success when creating a binary mask that is a combination of two or more colorspaces so additionally reduce any missing portions of object in the binary mask.

**Comment by RGROVE1232** [comment]
Thank you @HaleySchuhl - works great!

**Comment by HaleySchuhl** [comment]
Great to hear it! I'm going to close this issue for now, but feel welcome to reopen with any further comments/questions :D
