### ISSUE TITLE
Integrating PlantCV VIS tutorial and plantcv-workflow.py pipeline

### ISSUE THREAD

**Issue by oetodd** [danforthcenter/plantcv#821]
I am using the base VIS tutorial from plantCV and trying to use this workflow in the plantcv-workflow.py script. I am new to python and new to image processing, but I have looked for a solution to this error/problem as much as possible before posting. After validating my JSON file, I am running:

$ plantcv-workflow.py --config configlocal.json 

Which is calling my vis-tutorial with this code chunk still in the beginning of it:

                class options:
                    def __init__(self):
                        self.image = "./pics/Fo-308-3_2021-09-11_Pilot_3DAT.jpg"
                        self.debug = "print"
                        self.writeimg= False
                        self.result = "09-13Vis_results.json"
                        self.outdir = "." # Store the output to the current directory
                        
                
                args = options()
                
                
                pcv.params.debug = args.debug
              
My single image from testing is still in the self.image option, as well as all of the other information. 

Running $ plantcv-workflow.py --config configlocal.json results in this error:

RuntimeError: Failed to open ./pics/Fo-308-3_2021-09-11_Pilot_3DAT.jpg

I am wondering what I should change to address this error, I am working over a flat directory of 3 images as a test set.

**Comment by nfahlgren** [comment]
Hi @oetodd, assuming you have converted the tutorial notebook to a Python script, there are some other steps that are needed to convert it to a workflow that will work with `plantcv-workflow.py`: https://plantcv.readthedocs.io/en/stable/jupyter/#converting-jupyter-notebooks-to-plantcv-workflow-scripts

Mainly, the module `argparse` needs to be imported, the class `options` needs to be replaced with the function `options` from that documentation page, and the rest of the workflow needs to be wrapped in the function `main`.

Let us know if you get stuck anywhere though. Thanks!

**Comment by oetodd** [comment]
Thank you! I was able to do all of that, and my script worked well. I've attached my modified VIS workflow so others may see what worked.
[vis_tutorial-sugarbeet.py.zip](https://github.com/danforthcenter/plantcv/files/7165278/vis_tutorial-sugarbeet.py.zip)

**Comment by nfahlgren** [comment]
Awesome, thanks!
