### ISSUE TITLE
Naive Bayes Multiclass error making PDFs on training data

### ISSUE THREAD

**Issue by oetodd** [danforthcenter/plantcv#825]
I am running my pixel_samples.txt to get output PDFs with:
> plantcv-train.py naive_bayes_multiclass --file pixel_samples.txt --outfile naive_bayes_pdfs.txt

The error from the last line of the Traceback that I am receiving is:

> File "/Users/oliviatodd/.local/share/virtualenvs/PlantCV_docs--Hz9H6rW/lib/python3.7/site-packages/plantcv/learn/naive_bayes.py", line 137, in naive_bayes_multiclass
    
> hsv_img = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2HSV)

> cv2.error: OpenCV(3.4.15) /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-m9iba8ac/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**To Reproduce**
[pixel_samples.txt](https://github.com/danforthcenter/plantcv/files/7172678/pixel_samples.txt)

**Local environment:**
 - OS: MacOS
 - Environment: virtualenv

All troubleshooting with this error seems to be related to input image naming issues.

**Comment by oetodd** [comment]
It doesn't seem to have solved the issue, but here is the new .txt file with the spaces removed

[pixel_samples.txt](https://github.com/danforthcenter/plantcv/files/7172767/pixel_samples.txt)

**Comment by nfahlgren** [comment]
Oh, I also just noticed there are empty columns to the right of the four class columns.

**Comment by oetodd** [comment]
I tried taking those columns out and saving a new .txt, I think what was happening was I was correcting the header spacing on the .txt (attached - unchanged).
I tried running it again without changing anything, and it seems to have worked!
[pixel_samples.txt](https://github.com/danforthcenter/plantcv/files/7172826/pixel_samples.txt)

**Comment by nfahlgren** [comment]
Great!
