### ISSUE TITLE
Multi-plant workflow parallelization runs but outputs a json file with image metadata but no results

### ISSUE THREAD

**Issue by afaghm** [danforthcenter/plantcv#841]
## But when I try to parallelize this same workflow on just 2 images, although I get no errors, the output json file turns up empty.

    config.input_dir = "/Users/afagh/Desktop/parallel_multi_plant_workflow/multiplant_input_Images/"
    config.img_outdir = "/Users/afagh/Desktop/parallel_multi_plant_workflow/multiplant_output_Images/"
    config.json = "afagh_parallel_output.json"
    config.writeimg = False
    config.cleanup = False
    config.append = False
    config.tmp_dir = "/Users/afagh/plantcv/my_parallel_temp_dir/" #did not solve the issue
    config.filename_metadata = ["plantbarcode", "timestamp","measurementlabel","imgtype","camera","zoom"]
    config.timestampformat = "%Y-%m-%d %H-%M-%S"
    config.workflow = "afagh_workflow.py"

## I run the paralleliaztion workflow in a shell script:

    import subprocess
    subprocess.call(['/Users/afagh/plantcv/afagh_parallelization_shellscript.sh'])

## The shell script is simply:

    #!/bin/sh
    python3 plantcv-workflow.py --config afagh_config.json

## and I get the printed results:

    /Applications/anaconda3/envs/plantcv/lib/python3.7/site-packages/dask_jobqueue/core.py:20: FutureWarning: tmpfile is deprecated and will be removed in a future release. Please use dask.utils.tmpfile instead.
    Starting run 2021-11-30_19-13-15
    
    Reading image metadata...
    Reading image metadata took 0.0021181106567382812 seconds.
    Building job list... 
    Job list will include 2 images
    Building job list took 0.0009169578552246094 seconds.
    Processing images... 
    /Applications/anaconda3/envs/plantcv/lib/python3.7/site-packages/dask_jobqueue/core.py:20: FutureWarning: tmpfile is deprecated and will be removed in a future release. Please use dask.utils.tmpfile instead.
    [                                        ] | 0% Completed |  3.7sThis function has been updated to include object hierarchy so object holes can be included
    This function has been updated to include object hierarchy so object holes can be included
    Processing images took 9.360568046569824 seconds.
    Processing results... 
    Processing results took 0.008126974105834961 seconds.
    0

## But the output json file is just metadata:

      {"variables": {"camera": {"category": "metadata", "datatype": "<class 'str'>"}, "imgtype": {"category": "metadata", "datatype": "<class 'str'>"}, "zoom": {"category": "metadata", "datatype": "<class 'str'>"}, "exposure": {"category": "metadata", "datatype": "<class 'str'>"}, "gain": {"category": "metadata", "datatype": "<class 'str'>"}, "frame": {"category": "metadata", "datatype": "<class 'str'>"}, "lifter": {"category": "metadata", "datatype": "<class 'str'>"}, "timestamp": {"category": "metadata", "datatype": "<class 'str'>"}, "id": {"category": "metadata", "datatype": "<class 'str'>"}, "plantbarcode": {"category": "metadata", "datatype": "<class 'str'>"}, "treatment": {"category": "metadata", "datatype": "<class 'str'>"}, "cartag": {"category": "metadata", "datatype": "<class 'str'>"}, "measurementlabel": {"category": "metadata", "datatype": "<class 'str'>"}, "other": {"category": "metadata", "datatype": "<class 'str'>"}, "image": {"category": "metadata", "datatype": "<class 'str'>"}}, "entities": [{"metadata": {"camera": {"label": "camera identifier", "datatype": "<class 'str'>", "value": "TV"}, "imgtype": {"label": "image type", "datatype": "<class 'str'>", "value": "VIS"}, "zoom": {"label": "camera zoom setting", "datatype": "<class 'str'>", "value": "z3500"}, "exposure": {"label": "camera exposure setting", "datatype": "<class 'str'>", "value": "none"}, "gain": {"label": "camera gain setting", "datatype": "<class 'str'>", "value": "none"}, "frame": {"label": "image series frame identifier", "datatype": "<class 'str'>", "value": "none"}, "lifter": {"label": "imaging platform height setting", "datatype": "<class 'str'>", "value": "none"}, "timestamp": {"label": "datetime of image", "datatype": "<class 'datetime.datetime'>", "value": "2014-03-14 03-29-46"}, "id": {"label": "image identifier", "datatype": "<class 'str'>", "value": "none"}, "plantbarcode": {"label": "plant barcode identifier", "datatype": "<class 'str'>", "value": "AABA002948"}, "treatment": {"label": "treatment identifier", "datatype": "<class 'str'>", "value": "none"}, "cartag": {"label": "plant carrier identifier", "datatype": "<class 'str'>", "value": "none"}, "measurementlabel": {"label": "experiment identifier", "datatype": "<class 'str'>", "value": "Pilot-031014"}, "other": {"label": "other identifier", "datatype": "<class 'str'>", "value": "none"}, "image": {"label": "image file", "datatype": "<class 'str'>", "value": "/Users/afagh/Desktop/parallel_multi_plant_workflow/multiplant_input_Images/AABA002948_2014-03-14 03-29-46_Pilot-031014_VIS_TV_z3500.png"}}, "observations": {}}, {"metadata": {"camera": {"label": "camera identifier", "datatype": "<class 'str'>", "value": "TV"}, "imgtype": {"label": "image type", "datatype": "<class 'str'>", "value": "VIS"}, "zoom": {"label": "camera zoom setting", "datatype": "<class 'str'>", "value": "z3500"}, "exposure": {"label": "camera exposure setting", "datatype": "<class 'str'>", "value": "none"}, "gain": {"label": "camera gain setting", "datatype": "<class 'str'>", "value": "none"}, "frame": {"label": "image series frame identifier", "datatype": "<class 'str'>", "value": "none"}, "lifter": {"label": "imaging platform height setting", "datatype": "<class 'str'>", "value": "none"}, "timestamp": {"label": "datetime of image", "datatype": "<class 'datetime.datetime'>", "value": "2014-03-14 03-29-45"}, "id": {"label": "image identifier", "datatype": "<class 'str'>", "value": "none"}, "plantbarcode": {"label": "plant barcode identifier", "datatype": "<class 'str'>", "value": "AABA002948"}, "treatment": {"label": "treatment identifier", "datatype": "<class 'str'>", "value": "none"}, "cartag": {"label": "plant carrier identifier", "datatype": "<class 'str'>", "value": "none"}, "measurementlabel": {"label": "experiment identifier", "datatype": "<class 'str'>", "value": "Pilot-031014"}, "other": {"label": "other identifier", "datatype": "<class 'str'>", "value": "none"}, "image": {"label": "image file", "datatype": "<class 'str'>", "value": "/Users/afagh/Desktop/parallel_multi_plant_workflow/multiplant_input_Images/AABA002948_2014-03-14 03-29-45_Pilot-031014_VIS_TV_z3500.png"}}, "observations": {}}]}

## I have looked at the .txt file created in tmp folder for each image and the same problem exists, metadata with no results:

{"metadata": {"camera": {"label": "camera identifier", "datatype": "<class 'str'>", "value": "TV"}, "imgtype": {"label": "image type", "datatype": "<class 'str'>", "value": "VIS"}, "zoom": {"label": "camera zoom setting", "datatype": "<class 'str'>", "value": "z3500"}, "exposure": {"label": "camera exposure setting", "datatype": "<class 'str'>", "value": "none"}, "gain": {"label": "camera gain setting", "datatype": "<class 'str'>", "value": "none"}, "frame": {"label": "image series frame identifier", "datatype": "<class 'str'>", "value": "none"}, "lifter": {"label": "imaging platform height setting", "datatype": "<class 'str'>", "value": "none"}, "timestamp": {"label": "datetime of image", "datatype": "<class 'datetime.datetime'>", "value": "2014-03-14 03-29-45"}, "id": {"label": "image identifier", "datatype": "<class 'str'>", "value": "none"}, "plantbarcode": {"label": "plant barcode identifier", "datatype": "<class 'str'>", "value": "AABA002948"}, "treatment": {"label": "treatment identifier", "datatype": "<class 'str'>", "value": "none"}, "cartag": {"label": "plant carrier identifier", "datatype": "<class 'str'>", "value": "none"}, "measurementlabel": {"label": "experiment identifier", "datatype": "<class 'str'>", "value": "Pilot-031014"}, "other": {"label": "other identifier", "datatype": "<class 'str'>", "value": "none"}, "image": {"label": "image file", "datatype": "<class 'str'>", "value": "/Users/afagh/Desktop/parallel_multi_plant_workflow/multiplant_input_Images/AABA002948_2014-03-14 03-29-45_Pilot-031014_VIS_TV_z3500.png"}}, "observations": {}}

## Expected behavior
I expected the workflow to run through all the images and save the observations (from analyze objects) for each detected plant in the json file, just as I see in my single image workflow.

## Local environment:

OS: Mac
Environment : Jupyter Notebooks
PlantCV Version: 3.13.0

Any help on how to fix this is greatly appreciated!

**Comment by nfahlgren** [comment]
Hi @afaghm, thanks for the detailed report! Because the `.txt` files in the `tmp` folder are empty (metadata only), that explains why the final output JSON file is also empty. But it does not explain why the `.txt` files do not have observations. 

Could you upload your workflow script `afagh_workflow.py`? One thing I suspect is that in the workflow the results might be saved to a file other than `args.result`, which would explain why you see the correct results when you run it on a single image but not on multiple in parallel.

**Comment by afaghm** [comment]
- Hello and thanks for your quick response. I have attache my workflow. I have not changed much other than adjusting the thresholds. I have changed the options to reflect my desired input and output directories, but I assume the parallel workflow replaces those with the ones from the config file. 


[afagh_workflow.txt](https://github.com/danforthcenter/plantcv/files/7637391/afagh_workflow.txt)

- One other thing that I am suspicious of is that the temp .txt files come out as file_name.png.txt which might be the cause for the "parallel.process_results" not being able to write to them. But I have made sure that the in put png images do not have .png in their name and I have tried to track where these txt files are created in the "job_builder.py" to see if a .png is being added, but it is not. Code snippet of job_builder.py that I am looking at:

 # Create an output file to store the image processing results and populate with metadata
        outfile = open(os.path.join(config.tmp_dir, img + ".txt"), 'w')
        # Store metadata in JSON
        img_meta["metadata"]["image"] = {
                "label": "image file",
                "datatype": "<class 'str'>",
                "value": meta[img]['path']
}
I really appreciate your help.

**Comment by nfahlgren** [comment]
Hi @afaghm, the temp file names are okay, we just append `.txt` to the end of the input image filenames (rather than removing the image extension) but they are treated as text files.

I think the only thing that needs to be updated in your workflow is the code block at the top for the class `options`. We use the class in Jupyter to mimic the function of the same name that is needed in a workflow script to handle command-line input arguments. The arguments are created by `plantcv-workflow.py` and are supplied to your workflow script. I am attaching an updated version of your script but the key change is to replace the `class options` code with:

```python
import argparse

def options():
    parser = argparse.ArgumentParser(description="Imaging processing with PlantCV.")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-r","--result", help="Result file.", required= True )
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-w","--writeimg", help="Write out images.", default=False, action="store_true")
    parser.add_argument("-D", "--debug", help="Turn on debug, prints intermediate images.")
    args = parser.parse_args()
    return args
```

[afagh_workflow_v2.py.zip](https://github.com/danforthcenter/plantcv/files/7643000/afagh_workflow_v2.py.zip)

**Comment by afaghm** [comment]
Aha, Thank you so much Noah, I am rather new to python and did not catch that. I appreciate you taking the time to rectify my misunderstanding.
