### ISSUE TITLE
Error in finding contour (find object) for Hyperspectral Image

### ISSUE THREAD

**Issue by billygrahamram** [danforthcenter/plantcv#842]
**Description**
In the `pcv.find_objects` function. I am constantly getting the same error, even after trying with multiple images. There is a big chance that the error is from my side. But I've tried multiple options in my capability. I would like to ask if anyone can solve this for me.

**To Reproduce**
- Installed PlantCV using Anaconda
- Python 3.7.12
- Conda 4.10.3

The function I am using: 
`id_objects, obj_hierarchy = pcv.find_objects(img=index_array_gdvi.array_data, mask=gdvi_thresh)`

Error:
```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
C:\Users\PCADMI~1\AppData\Local\Temp/ipykernel_19112/1019017205.py in <module>
      4    #   img  - RGB or grayscale image data for plotting
      5    #   mask - Binary mask used for detecting contours
----> 6 id_objects, obj_hierarchy = pcv.find_objects(img=index_array_gdvi.array_data, mask=gdvi_thresh)

f:\billy_graham_ram\plantcv\plantcv\plantcv\find_objects.py in find_objects(img, mask)
     32     if len(np.shape(ori_img)) == 2:
     33         ori_img = cv2.cvtColor(ori_img, cv2.COLOR_GRAY2BGR)
---> 34     objects, hierarchy = cv2.findContours(mask1, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)[-2:]
     35     # Cast tuple objects as a list
     36     objects = list(objects)

**error: OpenCV(3.4.16) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'**
```

**Local environment:**
OS: Windows 10 Pro
Environment: conda
PlantCV Version: 3.13.2
Link to data: [click here](https://drive.google.com/drive/folders/1-brWzUHABWeeJWaP3mS0UVnmA0iKf8SF?usp=sharing)

**Comment by nfahlgren** [comment]
Hi @billygrahamram, for `pcv.find_objects` the `img` input is for plotting purposes and needs to be regular image type. Our `Spectral_data` class includes a `pseudo_rgb` attribute for exactly this purpose. For what you are doing only a small change is needed:

```python
id_objects, obj_hierarchy = pcv.find_objects(img=index_array_gdvi.pseudo_rgb, mask=gdvi_thresh)
```

Hope that helps!

**Comment by billygrahamram** [comment]
I did try this before. I am getting the same error.

**Comment by nfahlgren** [comment]
What's the output if you run this:

```python
gdvi_thresh.dtype
```

**Comment by billygrahamram** [comment]
dtype('uint16')

**Comment by nfahlgren** [comment]
The underlying OpenCV function doesn't support 16-bit images I think. There are a couple workarounds.

I might suggest converting the GDVI image to 8-bit prior to thresholding to make thresholding easier and ensure that the mask is 8-bit (setting a threshold between 0-2^8 is a bit easier to handle than between 0-2^16).

```python
from skimage import img_as_ubyte

# Convert the index array to an 8-bit image
gdvi = img_as_ubyte(index_array_gdvi.array_data)
# Plot a histogram to visualize where a good threshold value might be
hist = pcv.visualize.histogram(gdvi)
# Threshold the 8-bit index image (or use another threshold method)
gdvi_thresh = pcv.threshold.binary(gray_img=gdvi, threshold=100, max_value=255)
# FInd contours (index_array_gdvi.pseudo_rgb would still work as the image but gdvi would also)
id_objects, obj_hierarchy = pcv.find_objects(img=gdvi, mask=gdvi_thresh)
```

Alternatively, you might just be able to convert the mask directly (assuming it remains a binary image):

```python
from skimage import img_as_ubyte

gdvi_thresh = img_as_ubyte(gdvi_thresh)
id_objects, obj_hierarchy = pcv.find_objects(img=index_array_gdvi.pseudo_rgb, mask=gdvi_thresh)
```

**Comment by billygrahamram** [comment]
@nfahlgren Thank you for your time! It did work. One more request: are there any upcoming workshops on HSI analysis using PlantCV? Thanks.

**Comment by nfahlgren** [comment]
Great! We don't have anything specifically planned at the moment but that is a great idea. We will be doing a workshop at the upcoming NAPPN annual meeting (https://www.plantphenotyping.org/) but I'm not sure what the topic(s) will be yet. We have enjoyed doing virtual workshops through Phenome Force (https://phenome-force.github.io/PhenomeForce/) and I could imagine doing more of those or something similar in the new year.
