### ISSUE TITLE
Memory loss during calibration of Hyperspectral Image

### ISSUE THREAD

**Issue by billygrahamram** [danforthcenter/plantcv#843]
I've been trying to calibrate raw hyperspectral (HSI) images with the white and dark reference images using the function `pcv.hyperspectral.calibrate` and it always runs out of memory. At this moment I've tried it on four different machines with different configurations. I get the following error on some of the most powerful machines and the ones that are not that powerful just shut's off.

![WhatsApp Image 2021-12-06 at 00 02 15](https://user-images.githubusercontent.com/60169819/144899501-f890d2d5-20ba-4a6d-9cd0-f99782319293.jpeg)

I understand that this is due to the size of the HSI data and I should probably do some preprocessing in order to get a small size data before calibrating it.

How should I do it?

**Computer Specifications**
CPU: Intel i7 and i9
Memory: 64GB
Graphics: Nvidia GTX 1080 Ti

**Comment by HaleySchuhl** [comment]
Thanks for reaching out @billygrahamram ,

Researchers that we work with have also found memory to be a bottleneck when it comes to processing hyperspectral data within jupyter. Do you also have calibrated data, or just the raw image cube with white and dark ref? @nfahlgren are there are backend settings or other suggestions that might alleviate these errors?

**Comment by billygrahamram** [comment]
I don't have calibrated data. I only have a raw image cube with dark and white reference images. I tried to run Jupyter on my GPU using `TensorFlow-GPU` but couldn't make it work for myself. I will try that again today and see if that improves the processing and update this thread.

**Comment by nfahlgren** [comment]
Hi @billygrahamram, initially I was thinking this was just a memory issue but I noticed the error mentions only allocating 175 MiB, which isn't very much. I'm not 100% sure but I think the issue is related to data type somewhere. The error mentions `float32` and we cast the input raw data as 16-bit float, so there appears to be a mismatch somewhere. Could you share your `.hdr` file so we can see what kind of data type/format your images are in? We might need to update the calibration logic to be more flexible.

**Comment by billygrahamram** [comment]
I tried running calibration on another computer too (a good one) and it mentioned allocating 'only' 80GB of memory. This error has been consistent with all the computers I have. We use Prediktera Evince on the same machine and there the calibration works with just a click. So, I don't think that this is a memory issue. 
To the best of my understanding of HSI data and after seeing the source code for calibration in PlantCV. I think the calculation of calibration is very tedious to be applied directly to the raw 3D array. I think I need to do a dimensionality reduction before calibration.

Link to .hdr file:[ click here ](https://drive.google.com/file/d/1jbWAOTheh-ZpJU6VENzPGnQVYASEs_vX/view?usp=sharing)

**Comment by nfahlgren** [comment]
Thanks @billygrahamram, your data is the same format as ours. Looking at our code more closely I see some updates we should make @HaleySchuhl.

The code block causing @billygrahamram an issue appears to be redundant and does not affect the output. This part creates an array called `num` that is not used downstream:

```python
    # Calibrate using reflectance = (raw data - dark reference) / (white reference - dark reference)
    output_num = []
    for i in range(0, raw_data.lines):
        ans = raw_data.array_data[i,].astype(np.float16) - dark_reference.array_data
        output_num.append(ans)
    num = np.stack(output_num, axis=2)
```

The calibration that is output then follows:

```python
    output_calibrated = []
    for i in range(0, raw_data.lines):
        ans1 = raw_data.array_data[i,] / den
        output_calibrated.append(ans1)
```

So deleting that first code block might fix the issue and will definitely end up using less memory and increase speed.

**Comment by billygrahamram** [comment]
@nfahlgren  I tried after deleting that block of code and the same error persists.

**Comment by nfahlgren** [comment]
After editing the code, did you reinstall PlantCV and restart your Jupyter kernel? The error trace in the screenshot you originally posted would not be possible if the code was deleted.

**Comment by billygrahamram** [comment]
@nfahlgren Hi, this is the error.

![Capture](https://user-images.githubusercontent.com/60169819/145250693-026aa11e-e0de-44ef-b571-6f386210d0d5.PNG)

**Comment by nfahlgren** [comment]
So far, with our data (1704x1600 x 978 bands), I cannot replicate this error with the unmodified current version of PlantCV v3.13.2. Can you confirm that `white_reference.array_data.dtype`, `dark_reference.array_data.dtype` and `spectral_array.array_data.dtype` call match?

**Comment by billygrahamram** [comment]
@nfahlgren  The data type is same in all the three data. Would you mind taking a look at my data and see if there is something wrong with it? link to data: [clickhere](https://drive.google.com/drive/folders/1MPfmu-4Ga9Hzu86UcJdqQI_b8IWsX_nR?usp=sharing) (still uploading)
![Capture1](https://user-images.githubusercontent.com/60169819/145268694-55e19f38-807c-40b7-b1dd-0e6a51cc1d30.PNG)

**Comment by nfahlgren** [comment]
Hi @billygrahamram, we figured it out! @JorgeGtz realized that, unlike the dark and white references we work with, yours have 100 lines each and we were only anticipating 1. We also realized that there was a bug in the calibration method where we were not outputting the data as described. PR #845 will fix these issues and describes the changes in more detail. Thanks for providing the sample data and working through the issue with us!

**Comment by billygrahamram** [comment]
@nfahlgren This is great news! Thank you.

**Comment by nfahlgren** [comment]
Thanks @billygrahamram, we will create a bugfix release so that it's available on PyPI and conda-forge but sounded like you are using the source code version, so it should be available now. Let us know if there's new issues you run into with it.
