### ISSUE TITLE
plantcv.analyze_color directly on a RGB image

### ISSUE THREAD

**Issue by EdwinP503** [danforthcenter/plantcv#849]
Hi,

I was wondering if it is possible to use the analyze_color function directly on a RGB image without having to create a mask.

Thanks,
Edwin Polanco

**Comment by nfahlgren** [comment]
Hi @EdwinP503, you can by creating a full-image mask:

```python
import numpy as np
from plantcv import plantcv as pcv

h, w = img.shape[:2]
hist = pcv.analyze_color(rgb_img=img, mask=np.ones([h, w], dtype=np.uint8))

```

**Comment by EdwinP503** [comment]
Thanks a lot @nfahlgren! Is there also a way to separate the Red, Green and Blue colorspaces from a RGB image? Similar to HSV and LAB colorspaces.

**Comment by nfahlgren** [comment]
Not currently as a PlantCV function (but good idea) but it can be done by splicing the image:

```python
blue = img[:, :, 0]
green = img[:, :, 1]
red = img[:, :, 2]
```

Alternatively with OpenCV:

```python
import cv2
blue, green, red = cv2.split(img)
```

**Comment by EdwinP503** [comment]
Thanks again for your help!
