### ISSUE TITLE
Analyze object TypeError

### ISSUE THREAD

**Issue by EdwinP503** [danforthcenter/plantcv#875]
Hi,

When running the workflow parallelization using a script that contains the function for analyze shape I get the following TypeError:

`  File "/Users/_sinnerman_/Pearl_Millet/Sticker.py", line 57, in <module>
    main()
  File "/Users/_sinnerman_/Pearl_Millet/Sticker.py", line 53, in main
    analyze_object = pcv.analyze_object(img=img, obj=id_objects, mask=binary_threshold1)
File "/Users/_sinnerman_/opt/anaconda3/lib/python3.8/site-packages/plantcv/plantcv/analyze_object.py", line 52, in analyze_object
    hull = cv2.convexHull(obj)
TypeError: Expected Ptr<cv::UMat> for argument 'points'`

The continuosly appear as the process continues to run. My script uses a colorspace function > a binary threshold > find_objects > and analyze shape. 
Also, when I use the function `analyze_object = pcv.analyze_object(img=img, obj=id_objects, mask=binary_threshold1, label="default")`, it throws this error that disappears when I remove the argument 'label':
`TypeError                                 Traceback (most recent call last)
<ipython-input-10-ec99fadd7a37> in <module>
----> 1 analyze_object = pcv.analyze_object(img=img, obj=id_objects, mask=binary_threshold1, label="default")

TypeError: analyze_object() got an unexpected keyword argument 'label'`

My question is if I need to specify the data I need to collect from the shape analysis? and if I need to add the function `pcv.print_results(filename=args.result)` as the last function in the script.

Thanks,
Edwin P

**Comment by HaleySchuhl** [comment]
Hi @EdwinP503 ,

To me it sounds like your PlantCV environment might be outdated. We added the `label` parameter to all analysis functions to support mutli-plant analysis in 3.11. In the case of analyzing one object per image, leaving the label set to "default" should be fine.

**Comment by EdwinP503** [comment]
Hi @HaleySchuhl,

I upgraded PlantCV and the issue with the `label` parameter is solved. The TypeError is still showing when I try to run the script on images.
`  File "/Users/_sinnerman_/Pearl_Millet/Sticker.py", line 57, in <module>
    main()
  File "/Users/_sinnerman_/Pearl_Millet/Sticker.py", line 53, in main
    analyze_object = pcv.analyze_object(img=img, obj=id_objects, mask=binary_threshold1)
  File "/Users/_sinnerman_/opt/anaconda3/lib/python3.8/site-packages/plantcv/plantcv/analyze_object.py", line 53, in analyze_object
    hull = cv2.convexHull(obj)
TypeError: Expected Ptr<cv::UMat> for argument 'points'`

**Comment by nfahlgren** [comment]
Hi @EdwinP503, are you running `pcv.object_composition` before the analyze functions?

**Comment by EdwinP503** [comment]
Hi @nfahlgren, I am not.

**Comment by nfahlgren** [comment]
Ah okay, it's required before running analyze_object

**Comment by EdwinP503** [comment]
Issue is solved! Thank you guys!
