### ISSUE TITLE
JSON to csv

### ISSUE THREAD

**Issue by stiphyMT** [danforthcenter/plantcv#881]
**Describe the bug**
Usually I run a workflow with conditionals flow for different angle or camera images. This creates NA values for certain variables that do not exist is a certain angle/camera image combination. For conversion of the multiple-value variable data to csv, in the resulting file the cases with the NA have one less column, the _sample_ variable/column is missing.

I found this on PlantCV v3.13 but looking at the github history it has existed since v3.11

I believe that in the file 
**/plantcv/tree/master/plantcv/utils/converters.py**, line **76**
`csv.write(",".join(map(str, meta_row + [var, "NA", "NA"])) + "\n")`
should be
`csv.write(",".join(map(str, meta_row + [sample, var, "NA", "NA"])) + "\n")`

thus aligning the columns with the non exception case on line **73**
`row = [sample, var, obs[var]["value"][i], obs[var]["label"][i]]`

Stephan

**Comment by stiphyMT** [comment]
PS I haven't used GitHub much interacting with others until just now. How do you change the Labels? I want 'bug' and not 'help wanted'.

**Comment by HaleySchuhl** [comment]
Hi @stiphyMT ,

Thank you for opening an issue and bringing this to our attention. I added the `bug` tag to this issue; in GitHub the labels are located along the right hand side of an issue once it's been posted. 

Would you be interested in being added as a contributor of PlantCV so you'd be able to open Pull Requests to update and/or add code? Totally optional!

**Comment by stiphyMT** [comment]
Ciao Haley,
If you are patient with me I can give it a try. While I use git, when it comes to github I am never sure what I am doing is what I want. Should I make a pull request for this issue? (something small that I can start with).
Stephan
