### ISSUE TITLE
Contributing guide is outdated on testing

### ISSUE THREAD

**Issue by jdavidpeery** [danforthcenter/plantcv#917]
https://plantcv.readthedocs.io/en/stable/CONTRIBUTING/#testing-and-documenting-your-code
I believe most of this section is outdated, for example, `tests/tests.py` is now empty and the test data isn't stored in `tests/*data/`. 

Also, are we still using pytest? I was running it locally and it did work

**Comment by nfahlgren** [comment]
We do still use pytest but the command is somewhat different. It's what you added to the PR review guide, found in this section: https://plantcv.readthedocs.io/en/latest/pr_review_process/#step-4-review-the-tests

There's some flexibility depending on what one is trying to do but for simplicity I would recommend running all tests like this: `py.test --cov=plantcv` or specific test(s) like this `py.test --cov=plantcv -k test_name_or_keywords`.

Note you have to have both `pytest` and `pytest-cov` packages installed (the latter if you want to include coverage analysis).
