### ISSUE TITLE
sorted object data collection

### ISSUE THREAD

**Issue by EdwinP503** [danforthcenter/plantcv#920]
Hi guys,

The collection of images I am working with are for measuring the height of trees that are next to each other and the results are labeled from the smallest to largest object. Is it possible to specify the order in which the results are saved? or assign labels differently based on their location, for example they are numbered starting from 1 and left to right.

`tree_objs, obj_hierarchy = pcv.find_objects(img=rotated_img, mask=fill_img)`
`copy_img = np.copy(img)`
  
`for i in range(0, len(tree_objs)):`
`if obj_hierarchy[0][i][3] == -1:`
`tree, tree_mask = pcv.object_composition(img=rotated_img, contours=[tree_obj[i]], hierarchy=np.array([[obj_hierarchy[0][i]]]))`
`if tree is not None:`
`shape_img = pcv.analyze_object(img=tree_img, obj=tree, mask=tree_mask, label=filename + '_' + f"tree{i}")`

Thanks in advance!

**Comment by HaleySchuhl** [comment]
Hi @EdwinP503 thanks for opening an issue. This ordering/multiple objects per image issue is something we've been working on addressing! For now, `pcv.roi.multi` will allow you to separate the objects in order based on their position (first is top left, then read left to right, top to bottom) in which case the `for` loop will loop over each ROI you define, and then using `find_objects` and further analysis steps within the loop. 

The [multi plant tutorial](https://plantcv.readthedocs.io/en/latest/tutorials/arabidopsis_multi_plant_tutorial/) should be very similar to your workflow, but please don't hesitate if you have any further questions or issues come up!

**Comment by EdwinP503** [comment]
Thank you @HaleySchuhl! 
Looking at the multi plant tutorial I could apply a single row of of ROIs to capture the trees, but what if one ROI detects more than one object? Would you recommend to add another for loop for iterate through the objects if that is the case?

**Comment by HaleySchuhl** [comment]
Are the objects overlapping at all in your images? Usually I'll try to tweak the multi ROI parameters until I'm getting just one entity per ROI, but feel free to get as fancy as needed! The main thing is having unique `label` inputs for each different object of interest when it comes to the `analyze_object` step.

**Comment by EdwinP503** [comment]
The objects do not overlap but the distance in between them is not consistent and the same tree is analyzed twice, but I managed to avoid duplicates on the outputs. 

There is a warning whenever I `import plantcv.parallel`. Since plantcv-workflow.py uses it, will I be updating it for a future version of PlantCV?

`/opt/anaconda3/lib/python3.8/site-packages/dask_jobqueue/core.py:20: FutureWarning: tmpfile is deprecated and will be removed in a future release. Please use dask.utils.tmpfile instead.`

**Comment by nfahlgren** [comment]
Hi @EdwinP503 that warning is generated from Dask Jobqueue. I looked a little bit ago and I think they have updated their code but that version hasn't trickled down to conda yet, if I recall correctly.

@jdavidpeery just finished up a new automatic ROI feature in the PlantCV v4 branch (4.x) that might work a bit better for you use case than multi ROI? https://plantcv.readthedocs.io/en/4.x/roi_auto_grid/

**Comment by EdwinP503** [comment]
Thanks @nfahlgren and @jdavidpeery, the automatic ROI will be really helpful!

I'll look into the warning some more. Also, I noticed that after running the workflow there is a `asyncio.exceptions.CancelledError`, would I need to add something to finish running the workflow after the last image? or is there I may be missing.

**Comment by nfahlgren** [comment]
I think we see those kind of errors too, something about the worker shutdown that's inelegant. I don't think it causes any analysis issues (not that I have observed anyhow). I need to look back into Dask stuff one of these days anyhow because I think we could improve how we use autoscaling

**Comment by EdwinP503** [comment]
In my case it do not result on any change on the date, so will ignore while I look more into it. 

Thanks a lot!
