### ISSUE TITLE
Image Rotation

### ISSUE THREAD

**Issue by scallen81** [danforthcenter/plantcv#97]
It seems that when one tries to rotate an image, let's say 90 degrees from horizontal to vertical, the image rotates but the frame remains the same. Consequently, if your image is rectangular, when rotated from horizontal to vertical the top and bottom of the image gets cut off. It would be great if both the image and the fame are rotated together.

**Comment by bhive01** [comment]
This probably would help: http://www.pyimagesearch.com/2017/01/02/rotate-images-correctly-with-opencv-and-python/

Seems like it is a known issue.

**Comment by maliagehan** [comment]
yep we had kept image dimensions intentionally, but hadn't thought about when people want to adjust the mat. We'll add the option in soon. Thanks all!

**Comment by maliagehan** [comment]
This option has finally been added, see commit 0d943b20897f9d75c9979000720bf0526346adc6 and new rotate function.
