### ISSUE TITLE
color card matrix pre-loaded

### ISSUE THREAD

**Issue by kmurphy61** [danforthcenter/plantcv#973]
**Is your feature request related to a problem? Please describe.**
To color correct images using a standard color card, I have to hard-code the image I want to adjust color to, or hard code to my color card matrix values file. 

**Describe the solution you'd like**
Can we please have color card matrices of different orientations pre-loaded so that when we use the color-correction tool, we all correct to the same matrix file? This would help us be consistent across institutions and reduce hard-coding to our own images or matrix files. 

Thanks!

**Comment by JorgeGtz** [comment]
Hi @kmurphy61,

I think we recently added the functionality you are suggesting to the future 4.0 branch.
Can you take a look at the documentation in #931 and see if that's what you are thinking?

Thank you

**Comment by kmurphy61** [comment]
That is exactly it, thank you!
