### ISSUE TITLE
Installation dependencies in docs aren't up to date

### ISSUE THREAD

**Issue by Chup123** [danforthcenter/plantcv#976]
**Describe the bug**
The installation dependencies in the docs aren't up-to-date

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Go to the following [page](https://plantcv.readthedocs.io/en/stable/installation/)
2. Look at the dependencies

**Expected behavior**
The same list as in [requirements.txt](https://github.com/danforthcenter/plantcv/blob/main/requirements.txt) should be there
Now it is not. Opencv version 4 can be used, but not the latest version off numpy

**Additional context**
Will use plantCV with some functions from opencv. Had to use the latest version

**Comment by HaleySchuhl** [comment]
Thanks @Chup123 for bringing this to our attention! I can create a PR against the main branch that updates this section of the docs and then we can update the other active branches.
