### ISSUE TITLE
Boundary Line Tool

### ISSUE THREAD

**Issue by scallen81** [danforthcenter/plantcv#98]
Typically the boundary line tool is utilized to distinguish structures (of a vertical image) above the top of a pot using a horizontal line. Alternatively, for horizontal images, for example a whole excavated plant, it would be nice to be able to distinguish between above and below ground structures be demarcating the left from the right with a vertical line.

**Comment by nfahlgren** [comment]
Pull request #217 creates this functionality. Need documentation to complete and close issue.
