### ISSUE TITLE
pcv.analyze_object giving more objects than expected 

### ISSUE THREAD

**Issue by JSCG95** [danforthcenter/plantcv#981]
Hello!

I have been trying to generate a results table based on a multiplant workflow that will consider only plants that are above a specific threshold:

if area > 400:
        # Combine contours together for each plant
        # Inputs:
        #   img       = input image
        #   contours  = contours that will be consolidated into a single object
        #   hierarchy = the relationship between contours
        plant_obj, plant_mask = pcv.object_composition(img=color, 
                                                       contours=plant_contours, 
                                                       hierarchy=plant_hierarchy)   
        plt.imshow(plant_mask, cmap = 'gray')
        plt.show()
    

        # Analyze the shape of each plant
        # Inputs:
        #   img   = input image
        #   obj   = composed object contours
        #   mask  = binary mask that contours were derived from
        #   label = a label for the group of measurements (default = "default")
        img_copy = pcv.analyze_object(img=img_copy, obj=plant_obj, 
                                      mask=plant_mask, label=f"plant{plant_id}")

I'm printing each iteration inside of 24 plants loop and I can see that in fact the pcv.object_composition function is just giving mask for the plants which are over 400 pixels. However,  pcv.analyze_object keeps giving my 24 plants total as results table.
Do you know what I could do to have as a result just the plants thar are over 400 pixels specified in the step beofre I generate my output?

**Comment by HaleySchuhl** [comment]
Hi @JSCG95 ,

Would something like this work for your goal outcomes? https://plantcv.readthedocs.io/en/latest/fill/ The `pcv.fill` function removes objects smaller than a certain size from a binary image. This would remove those small plants from your mask and would need to be positioned in your workflow before you do `pcv.find_objects` to identify plants from the binary mask.

**Comment by JSCG95** [comment]
I'm using the function pcv.fill and in fact is working pretty good a few steps before in my workflow.

   path = filename
    # tray_number = 1
    # pcv.params.debug = "print"
    # Let's develop the code for a single image first
    # PCV is reading this img as BGR instead of RGB
    img, path, img_filename = pcv.readimage(filename=path, mode="native")
    plt.imshow(img)
    
    # We use cv2 function to restore RGB format of our image. 
    color = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(color)
    
    # (X and Y are starting X,Y coordinate respectively)
    # h = y_axis total lenght , w = x_axis total lenght
    #crop = pcv.crop(img=color_rgb, x=140, y=180, h=2000, w=3700)
    #plt.imshow(crop)
    
    
        # Make sure you are analizing an RGB for this to work. 
        #   rbg_img      = original image
        #   original_img = whether to include the original RGB images in the display: True (default) or False
    colorspace_img = pcv.visualize.colorspaces(rgb_img=color,original_img=False)
    plt.imshow(colorspace_img)
    
    #   channel = desired colorspace ('l', 'a', or 'b')
    lab_a = pcv.rgb2gray_lab(rgb_img=color, channel='a')
    plt.imshow(lab_a, cmap = 'gray')
    
    ## To create a histrogram to obtain our threshold value using opencv
    histogram, bin_edges = np.histogram(lab_a, bins=256, range=(0, 255))
    fig, ax = plt.subplots()
    plt.plot(bin_edges[0:-1], histogram)
      
    
    # Explain how the value in threshold works in the image. Everything over or under is discarded? 
    # We use img color channels as gray_img. 
    thresh = pcv.threshold.binary(gray_img=lab_a, threshold=100, max_value=255, object_type='dark')
    plt.imshow(thresh, cmap = 'gray')
    
    # =============================================================================
    #  THIS IS PLANTCV histogram option. Creates a ggplot object. 
    #hist2 = pcv.visualize.histogram(img=crop,hist_data=True)
    # =============================================================================
    
    # Remove small background noise
    ## The fill function removes "salt" noise from the background by filtering white regions by size.
    
    # Inputs:
    #   bin_img = Binary image data
    #   size    = minimum object area size in pixels (integer), smaller objects will be filled
    a_fill = pcv.fill(bin_img=thresh, size=100)
    plt.imshow(a_fill, cmap = 'gray')
    
    # Identify the outlines of all plants
    ## The binary mask (all values are either white or black) that resulted from thresholding and filtering 
    ## the thresholded image is used to identify the polygons that define the outlines of every connected white region. 
    ## Objects (or contours) can be nested, so a hierarchy that defines the relationship between objects is also calculated.
    
    # Inputs:
    #   img  = input image
    #   mask = a binary mask used to detect objects
    # Is there a possibility to print both the img and the mask on top? 
    obj, obj_hierarchy = pcv.find_objects(img=color, mask=a_fill)
    
    
    # ROIS will create a list with all the 98 position in the seeding tray. 
    # Use len(rois) for the expected total seedling count. 
    rois, roi_hierarchy = pcv.roi.multi(img=color, coord=(138,160), radius=78, 
                                        spacing=(270, 278), nrows=4, ncols=6)
    
    # this one as well will have a len of the expected total seedlings but in range format. 
    plant_ids = range(0, len(rois))
    
    
```
    # Here we create a copy of the original crop image
    img_copy = np.copy(color)
    
    # Create a for loop to interate through every ROI (plant) in the image
    for i in range(0, len(rois)):
        # The ith ROI, ROI hierarchy, and plant ID
        roi = rois[i]
        hierarchy = roi_hierarchy[i]
        plant_id = plant_ids[i]
        # Subset objects that overlap the ROI
        # Inputs:
        #   img            = input image
        #   roi_contour    = a single ROI contour
        #   roi_hierarchy  = a single ROI hierarchy
        #   object_contour = all objects detected in a binary mask
        #   obj_hierarchy  = all object hierarchies
        #   roi_type       = "partial" (default) keeps contours that overlap
        #                    or are contained in the ROI. "cutto" cuts off
        #                    contours that fall outside the ROI. "largest"
        #                    only keeps the largest object within the ROI
        plant_contours, plant_hierarchy, mask, area = pcv.roi_objects(img=color, 
                                                                      roi_contour=roi, 
                                                                      roi_hierarchy=hierarchy, 
                                                                      object_contour=obj, 
                                                                      obj_hierarchy=obj_hierarchy, 
                                                                      roi_type="partial")
    
        # If the plant area is zero then no plant was detected for the ROI
        # and no measurements can be done
        if area > 0:
            # Combine contours together for each plant
            # Inputs:
            #   img       = input image
            #   contours  = contours that will be consolidated into a single object
            #   hierarchy = the relationship between contours
            plant_obj, plant_mask = pcv.object_composition(img=color, 
                                                           contours=plant_contours, 
                                                           hierarchy=plant_hierarchy)        
            # Analyze the shape of each plant
            # Inputs:
            #   img   = input image
            #   obj   = composed object contours
            #   mask  = binary mask that contours were derived from
            #   label = a label for the group of measurements (default = "default")
            img_copy = pcv.analyze_object(img=img_copy, obj=plant_obj, 
                                          mask=plant_mask, label=f"plant{plant_id}")
```




 The problem I'm having is related with the output being generated by pcv.analyze_object. When I show the image of each iterations after pcv.object_composition I can see that the plants that I want to filter are being selected (just the ones > 400 pixel). However when I include pcv.analyze_object, the output with the results will give me a dictionary with data for 24 objects (plant_ids) and not just my filtered plants

**Comment by HaleySchuhl** [comment]
Could you please send your whole workflow, an example image, which plantcv version you're using, and your current results output so I can try to replicate your problem? I don't currently see the `if area < 400` logic within the code you sent, so please send everything!

**Comment by JSCG95** [comment]
I apologize for the late reply. Yes you were right I uploaded the wrong code. However, in the paralelization the count worked as expected. Thanks anyways, it allowed me to realize were the error was.
