### ISSUE TITLE
Detect 2 objects close together as one without ROI

### ISSUE THREAD

**Issue by JSCG95** [danforthcenter/plantcv#988]
Hello! 
I'm having an issue with my code versatility when working with different grids or plant distributions. My intention is to assess first object count and then geometrical features from each object in a tray. However, when I use the function find_objects I figured out that the count of objects detected do not correspond to the number of seedlings I have in my growing tray. This is because usually from a single plant the two cotiledons are visible but because of the size of petiole they seem to be to independent objects (even though they are close together). On the image you can see that the objects in the original image are selected. However, in the first plant (for example) it will count two objects instead of 2. 

![image](https://user-images.githubusercontent.com/106388895/205552752-c0f0851e-2695-400b-a801-40c06b21a118.png)

My first question is: Do you have a solution to bring together the two cotiledons (that are a few mm away from each other) without the need of creating a ROI to enclose both objects? I want to avoid ROI since I'm working with different tray shapes, grids and distributions and one grid defined by roi.multi won't adapt to my plants when I want to run a high thruput measurement.  

Hope you can give me a clue on what I could do.

**Comment by HaleySchuhl** [comment]
Hmm good question @JSCG95 ,

I'd typically suggest some grid layout of ROIs but lack of consistency would totally make this more time consuming when there is no consistency of layout. Maybe you can aggressively [dilate](https://plantcv.readthedocs.io/en/latest/dilate/) to combine the structure so that you can loop over objects, and the erode the same amount right before measuring area and shape characteristics. Sometimes a slight blur can help to join objects as well. 

We also have the [auto_grid](https://plantcv.readthedocs.io/en/4.x/roi_auto_grid/) function in the v4.x branch which will allow for some level of shifting between images, but this still requires the nrows and ncols is known. This could be defined once per unique grid layout and then analyze all 4x2 images at once.

**Comment by JSCG95** [comment]
Yes, I read somewhere else morphological operations is the way to go. However: 
Do you think dilate function could potentially change my geometrical features values compared with a mask that didn't used dilation to segment objects?

**Comment by nfahlgren** [comment]
Spatial clustering might give you the best flexibility: https://plantcv.readthedocs.io/en/stable/spatial_clustering/. I think dilation is tricky to use for this purpose unless the objects are consistently very close together.

**Comment by JSCG95** [comment]
Thanks for your suggestions @HaleySchuhl . Dilation operation does improve the number of objects that the function _find_objects_ is identifying however is not the right number of plants yet (still over counting). Besides, it is overestimating the size of the plant after using  _'pcv.roi.from_binary_image(bin_img=dil_img, img=crop) '. I'm attaching an image that shows clearly the overestimation.

![image](https://user-images.githubusercontent.com/106388895/206300248-11357e28-e679-4060-9bac-ec3529047b56.png)


As an alternative, I tried to use @nfahlgren  suggestion. However, I'm not so familiarized with the arguments that spatial_clustering is taking, and I don't know how to adapt the arguments according to my image properties.  To be more specific, what is not clear for me after choosing the algorithm "DBSCAN" is what exactly the value of 0-1 for _min_cluster_size=_ , means.  I was considering using OPTICS, as I'm working with seedlings but since I'm having speed issues by running DBSCAN probably with OPTICS it would be worst when analyzing multiple images at the same time.  In fact, I was planning to send you my results after using DBSCAN with the default arguments however it gave me memory error:
![image](https://user-images.githubusercontent.com/106388895/206303999-0f3e054d-1880-4db5-b7e8-f54c8ef385fe.png)

Thanks again
