### ISSUE TITLE
ModuleNotFoundError: No module named 'plantcv'

### ISSUE THREAD

**Issue by rodrign2002** [danforthcenter/plantcv#991]
Hi, 

I am trying to run the code in Jupyter notebook, but when I try to upload the program, I get the following.

import os
import argparse
import matplotlib
import numpy as np
from plantcv import plantcv as pcv

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [5], in <cell line: 5>()
      3 import matplotlib
      4 import numpy as np
----> 5 from plantcv import plantcv as pcv

ModuleNotFoundError: No module named 'plantcv'

I would appreciate it if you could help me

Thank you os much

**Comment by nfahlgren** [comment]
Hi @rodrign2002,

Your code is correct so this means that either PlantCV is not installed or cannot be found by your Jupyter environment. I would need to know more about your setup (how you installed plantcv, jupyter, etc.) but my general approach is to create a `conda` environment for PlantCV with Jupyter dependencies:

```bash
conda create -n plantcv -c conda-forge plantcv jupyterlab nb_conda ipympl nodejs
```

I also like to have `nb_conda` installed in my base `conda` environment:

```bash
conda install -n base -c conda-forge nb_conda
```

Then when you start Jupyter `jupyter lab` you should see a notebook environment option for the environment named "plantCV".

Alternatively, if you are not using `conda` and/or don't want to do the above, you can install PlantCV using `pip` from within your Jupyter notebook. In one of the cells run:

```
%pip install plantcv
```

Hope that helps!
